osm2pgsql-dev/osm2pgsql

- configure.ac
- osmdata.cpp
- output.hpp
Fixes #199 
This could use checking on different combinations of boost and `--without-lockfree`
> Switch boost lockfree queue check into configure

- default.style
The `nocache` flag is depreciated and does nothing.
As `nocache` does nothing, there are no issues with updating and this is a change just to avoid confusion.
Fixes #235
> Remove nocache flag from religion

- configure.ac
- geometry-builder.cpp
Closes #250 
GEOS 2.x support is dead code, not being tested. Old GEOS is also a problem for non-robust geometry processing.
> Remove GEOS 2 support

- docs/usage.md
Also explicitly mentions that the null backend doesn't disable the
middle, only the backend
Fixes #260
Clarifies #243
> Mention multi backend in usage

- options.cpp
Arguments coming after an ifdef or otherwise in a new printf statement were often mis-aligned. This fixes that.
`make check` passes
> Clean up help spacing

- default.style
By using non-text types the columns are small, indexes are smaller, and inequality and range comparisons are possible.
> Add recommended types to columns for extra attributes

- configure.ac
- osmtypes.hpp
OSM IDs are high enough that 64 bit node IDs are needed everywhere.
Projects using osm2pgsql on non-OpenStreetMap data are not generally
dealing with large enough datasets to need 32 bit IDs, and not
generally building their own osm2pgsql with the 32 bit option anyways.
> Remove 32-bit node ID support

- table.cpp
osm2pgsql was running analyze twice on tables, once before indexes
and copying tables, once after. This first analyze wasn't needed.
The copying to new tables always runs a sequential scan, and
the index creation doesn't depend on planner statistics and also
forces a sequential scan of the table.
An analyze is run later on before osm2pgsql exits.
> Don't analyze before copying tables

- output-pgsql.cpp
This should stop thrown errors from aborting the thread without any message.
Fixes #298
> Catch exceptions in threads and print them upon join

- parse-o5m.cpp
- parse-pbf.cpp
- parse-xml2.cpp
OSM PostGIS databases are used not only for Mapnik. Some tools need tags like `source`. Most styles already have these keys in "delete" lists, so it won't change much.
Fixes #130.
> Do not forcefully delete created_by and source tags

- osmdata.cpp
- output.hpp
The lockfree queue requires a trivially assignable type which std::pair isn't, see #196.
I've confirmed that it compiles successfully against libc++ but could not actually run the tests because I don't have a clang-compiled boost available. Could somebody on OSX or FreeBSD check that this works?
cc @springmeyer
> convert pending_job_t to a simple struct

- .gitignore
- Makefile.am
- geometry-processor.cpp
- tests/test-output-multi-line-storage.cpp
- tests/test_output_multi_line_storage.osm
- tests/test_output_multi_line_trivial.lua
- tests/test_output_multi_line_trivial.style.json
This is the quick fix to #274, but includes a testcase.
With the testcase, fixing it properly would make a reasonable place for someone to start with osm2pgsql.
> Fix incorrect resizing of node cache in geometry processor

- output-multi.cpp
- tests/test-output-multi-line-storage.cpp
- tests/test_output_multi_line_trivial.lua
This fixes a regression in the std::vector changes and adds a test to fix a bug in checking #273.
The testcase is minimal, as nodes worked and should really be independently tested, as well as pgsql lua.
> Fix a bug where modified tags weren't being copied from Lua

- .gitignore
- Makefile.am
- output-multi.cpp
- tests/test-output-multi-poly-trivial.cpp
- tests/test_output_multi_poly_trivial.lua
- tests/test_output_multi_poly_trivial.osm
- tests/test_output_multi_poly_trivial.style.json
I think this is a fix for #336 - the re-use of `outtags` and passing the original relation tags to the member filter function rather than the previously filtered tags seems to have been causing missing tag values under some circumstances. Since this type of tag mangling is pretty common in multi-polygon processing, it's fairly likely that some missing tags would be fixed by this.
Also added a new test case which (hopefully) encapsulates the expected behaviour.
> Fix multi tags redeclaration

- configure.ac
- m4/ax_cxx_compile_stdcxx_11.m4
Second attempt to enable C++11. This could do with some testing with different compilers. I've already run into bugs with boost 1.49 (as used in Debian stable).
@pnorman could you test again with your clang setup? Please make sure to run `make distclean` before compiling.
> Optionally enable C++11

- node-persistent-cache.cpp
Blocks should be prefetched when they are not in the ram cache.
Might or might not be related to #351.
> node-cache: fix prefetching

- default.style
- empty.style
The behavior for columns without any flags is badly defined, and changing the lines above them can have odd results.
Passes the regression test.
Fixes part of #327
> Add column flags to sample .style files

- style.lua
This adds documentation to style.lua.
It also has some small changes to improve the legibility: it moves the configurable arrays to the top, and it changes some variable names.
> Add documentation and improve legibility style.lua

- .gitignore
- Makefile.am
- tests/common-pg.cpp
- tests/common-pg.hpp
- tests/test-output-multi-line.cpp
- tests/test-output-multi-point-multi-table.cpp
- tests/test-output-multi-point.cpp
- tests/test-output-multi-polygon.cpp
- tests/test-output-pgsql-tablespace.cpp
- tests/test-output-pgsql.cpp
* Moves the tablespace tests into their own file. Now everything except for test-output-pgsql-tablespace and regression_test.py can be run without a custom tablespace.
* Adds tests for `--latlong` mode
> Tablespace and latlong tests

- node-persistent-cache.cpp
- node-ram-cache.cpp
- node-ram-cache.hpp
Reduces preallocation of memory and implements more dense management structures for the ram node cache. For a planet import, the reduction in total memory is around 800MB. This helps a bit with #351 but won't completely fix it.
Passes the tests but still needs to be tested more thoroughly with different variations of ram cache configuration before merging.
> Reduce memory usage of node cache

- .gitignore
- Makefile.am
- tests/test-middle-flat.cpp
There's something odd with test_way_set, but the other tests work and pass.
I'm not quite happy with test_way_set, and think some smaller unit tests are needed for testing append mode.
> Extend node storage tests to flat nodes

- tagtransform.cpp
The C transforms used to turn the name tag into a route_name tag on
route relations, for reasons that are not entirely clear. This change
doesn't remove route_name, but does also populate the name column,
eliminating a source of confusion to users.
Fixes #315
> Populate name column for route relations

- options.cpp
After IRC discussion, the way forward with #213 is to error on append without slim.
If someone wants to implement `middle_ram_t::relations_using_way` they can do a pull request, but otherwise this closes #213 as wontfix.
> Relations using way

- .gitignore
- Makefile.am
- docs/migrations.md
- tagtransform.cpp
- tests/test-output-pgsql-z_order.cpp
- tests/test_output_pgsql_z_order.osm
Most maps prefer placing link roads below non-link roads. This allows them to do so without complex SQL or multiple layer solutions which break layer tag usage.
z_order per layer has also been increased from 10 to 100 to allow for this more fine-grained ordering.
Other types of roads (tracks, paths, etc) have been added. This does not impact those not using z_order for layers with these, but does allow their use.
It also removes highway=minor handling, which is a disused tag.
Fixes #132
@math1985, as you are more familiar with appropriate ordering of roads, could you review this? I'd like to deal with #132 for 0.88.0 which is probably coming soon.
I'm not attempting to replicate the osm-carto behavior for railways, as what we're doing with a `UNION ALL` is fairly specific and might not be …
> Change z_order of link roads and add tests

- configure.ac
These are some of the changes suggested by autoupdate.
It also suggested changing `AC_GNU_SOURCE` to `AC_USE_SYSTEM_EXTENSIONS`, but as I didn't understand that change I avoided doing it.
> Improve configure.ac syntax and quoting

- table.cpp
Although the tables are only growing and will not trigger autovacuum,
they may still trigger autoanalyze which is controlled by the same
storage setting.
This does not change the slim tables, which are part of middle-pgsql.
Closes #155 - for output pgsql tables. I'm not if the issue is applicable to gazetteer, and I'd rather not touch the middle tables
> Disable autovacuum on the rendering tables during import

- table.cpp
If the SRID of the existing tables don't match then any actions
that involve changing the geometry will generate an error. Deletes
are independent of SRID.
This makes an explicit SRID check not required, and the existing
check did not handle schemas correctly.
> Don't check the SRID of existing tables

- configure.ac
2.3 doesn't work correctly
Fixes #392
> Set the minimum protobuf-lite version

- middle-pgsql.cpp
- options.cpp
- options.hpp
- osm2pgsql.cpp
- output-gazetteer.cpp
- output-multi.cpp
- output-pgsql.cpp
- tests/common-pg.cpp
- tests/common-pg.hpp
- tests/test-hstore-match-only.cpp
- tests/test-middle-flat.cpp
- tests/test-middle-pgsql.cpp
- tests/test-output-multi-line-storage.cpp
- tests/test-output-multi-line.cpp
- tests/test-output-multi-point-multi-table.cpp
- tests/test-output-multi-point.cpp
- tests/test-output-multi-poly-trivial.cpp
- tests/test-output-multi-polygon.cpp
- tests/test-output-multi-tags.cpp
- tests/test-output-pgsql-tablespace.cpp
- tests/test-output-pgsql-z_order.cpp
- tests/test-output-pgsql.cpp
- tests/test-parse-options.cpp
* Uses a delegating constructor instead of `options_t::parse`
* Moves DB options into their own class
* Don't try to duplicate libpq logic for port
* Split up the giant parse function
* Default to number of hardware threads
> Refactor options_t

- .gitignore
- Makefile.am
- tests/common-pg.cpp
- tests/common-pg.hpp
- tests/test-hstore-match-only.cpp
- tests/test-middle-flat.cpp
- tests/test-middle-pgsql.cpp
- tests/test-output-multi-line-storage.cpp
- tests/test-output-multi-line.cpp
- tests/test-output-multi-point-multi-table.cpp
- tests/test-output-multi-point.cpp
- tests/test-output-multi-poly-trivial.cpp
- tests/test-output-multi-polygon.cpp
- tests/test-output-multi-tags.cpp
- tests/test-output-pgsql-schema.cpp
- tests/test-output-pgsql-tablespace.cpp
- tests/test-output-pgsql-z_order.cpp
- tests/test-output-pgsql.cpp
* Adds a passing test that if osm2pgsql is using the public schema it won't interfere with another schema not in the search_path
* refactors common pg test code into common-pg
I have a failing test I've written for using another schema, but I need to think about that behavior a bit more.
> Schema tests

- id-tracker.cpp
- id-tracker.hpp
- output-multi.cpp
- output-pgsql.cpp
If the pending tracker of output was ahead of the pending tracker
of middle when merging the two then an id coming from the middle
tracker was unconditionally added even if it was present in the
output tracker and therefore added from there.
Fixes #419
> avoid duplicates in job queues for pending ways and relations

- expire-tiles.cpp
- parse-o5m.cpp
Some warnings found with LLVM 3.4 `scan-build`
> Scan build analysis fixes

- m4/ax_append_flag.m4
- m4/ax_cflags_warn_all.m4
- m4/ax_cxx_compile_stdcxx_11.m4
- m4/ax_lua.m4
- m4/ax_require_defined.m4
The C++11 changes landed upstream, so replaces #434
Fixes #432
Other changes are fairly minor
> Update macros from autoconf archive

- middle-ram.hpp
- tests/test-expire-tiles.cpp
Recompilng on Visual Studio 2015 on Windows 10 x64 resulted in several errors.
Most of them were from my cmake scripts (now fixed), but two problematic places were found in the code.
> Fixes to restore MSVC compatibilty

- .travis.yml
This also turns CXXFLAGS into a variable, as there are still some warnings being produced on OS X.
> Enable OS X support for Travis

- node-persistent-cache.cpp
For setups without `HAVE_POSIX_FALLOCATE` there was an unused variable.
> Move variable declaration in #ifdef block its used in

- node-ram-cache.cpp
- tests/middle-tests.cpp
The dense cache has a fixed memory cost which is associated with the number of blocks needed. Increase the block size reduces the number of blocks, resulting in reduced memory usage. For this change on modern hardware it is a decrease from 1GB to 128MB. Large blocks are less efficient than small ones, but it turns out that this does not matter for planet imports, where the efficiency change is small and memory usage is actually slightly reduced, or for small imports, where the fixed cost change overwhelms anything else.
On large but not planet sized extracts (e.g. Europe) memory usage is slightly increased, by about 450MB, while the cache in total consumes about 18GB.
Changing the cache size did not have a measurable impact on performance in testing.
Fixes #439
----
I had considered other …
> Increase dense block size from 1k to 8k nodes

- parse-osmium.cpp
I hit this while processing a snapshot extracted from history which happened to contain [version 3 of node 7226378](http://www.openstreetmap.org/node/7226378/history), which has coordinates (83.4542914, 214.7483647). The API at the time didn't check this, and it has since been fixed, but it means that [the node parsing code](https://github.com/openstreetmap/osm2pgsql/blob/master/parse-osmium.cpp#L64-L65) will throw an exception.
(Notably, this doesn't kill the process, as it means the consumer thread waits on the Queue to finish processing, while the producer thread is waiting on the Queue to empty. But this is a separate issue.)
In this case it seems simple enough to just ignore any node which has an invalid location, which is effectively the same behaviour as setting the bbox to the …
> Ignore nodes with invalid coordinates.

- osm2pgsql.cpp
PostgreSQL 9.0 is 5 years old and will not have any new releases as
it is unsupported. This change doesn't remove support for 9.0, but
just the check with --unlogged that the server supports it.
If someone does try --unlogged with an older version, it will error
early in the process when it tries to create tables.
> Remove check for unlogged and PostgreSQL < 9.1

- docs/Doxyfile
Requires dot, but very useful for visualizing include graphs.
You are in a maze of twisty includes, all different
> Turn on doxygen graph support

- CONTRIBUTING.md
- middle-pgsql.cpp
- middle-ram.cpp
- node-persistent-cache.cpp
- node-ram-cache.cpp
- node-ram-cache.hpp
- osmdata.cpp
- output-gazetteer.hpp
- output-pgsql.cpp
- output.hpp
- parse-o5m.cpp
- parse-o5m.hpp
- parse.cpp
- parse.hpp
- reprojection.cpp
- sprompt.cpp
- tests/test-parse-xml2.cpp
This is not a complete cleanup, but what iwyu was reporting without errors on clang 3.4 and some earlier work with deheader.
Switching from `<stdio.h>` to <cstdio>` does apparently have some differences (include-what-you-use/include-what-you-use#226), but we weren't consistent about this before.
> Include cleanup

- output-gazetteer.cpp
After fixing include order, one include was missing for Visual Studio 2015. std::cerr needs explicit ``<iostream>``.
Could you please add it?
> add missing include for std::cerr

- CMakeLists.txt
This small PR affects only Windows and reduces a log of Debug build greately, eliminating .pdb related warnings like the following ones:
```
proj.lib(PJ_chamb.obj) : warning LNK4099: PDB 'proj.pdb' was not found with 'proj.lib(PJ_chamb.obj)' or at 'D:\winbuilds\osm2pgsql\build\tests\proj.pdb'; linking object as if no debug info
proj.lib(PJ_collg.obj) : warning LNK4099: PDB 'proj.pdb' was not found with 'proj.lib(PJ_collg.obj)' or at 'D:\winbuilds\osm2pgsql\build\tests\proj.pdb'; linking object as if no debug info
proj.lib(PJ_crast.obj) : warning LNK4099: PDB 'proj.pdb' was not found with 'proj.lib(PJ_crast.obj)' or at 'D:\winbuilds\osm2pgsql\build\tests\proj.pdb'; linking object as if no debug info
proj.lib(PJ_denoy.obj) : warning LNK4099: PDB 'proj.pdb' was not found with …
```
> MSVC: add flag to skip warings about missing .pdbs

- CMakeLists.txt
- tests/CMakeLists.txt
- tests/regression-test.py
Following https://github.com/openstreetmap/osm2pgsql/pull/475
Added -x exe_name option to python test script (./osm2pgsql by default) and passed `` -x $<TARGET_FILE:osm2pgsql>`` in cmake test.
Checked on Windows.
> Avoid executable file copying for regression tests

- CMakeLists.txt
- tests/CMakeLists.txt
Use the coding style used by the CMake project itself. This fixes the first half of #474.
> make CMake coding style more consistent

- node-ram-cache.hpp
- pgsql.hpp
Here is the cosmetic fix that reduces the number of MSVC warnings
https://github.com/openstreetmap/osm2pgsql/issues/470
(all warnings in hpps)
> explicit type conversions to reduce MSVC warnings

- .travis.yml
- node-ram-cache.cpp
- osm2pgsql.cpp
Tried to fix https://github.com/openstreetmap/osm2pgsql/issues/468 . Is this correct?
> fix printf formats for 64 bit values

- docs/multi.md
- output-multi.cpp
- output-multi.hpp
Fixes #270
This allows creation of polygon tables which consist of only polygons
> Use the polygon flag from the tagtransforms to change multi-backend 

- geometry-builder.cpp
- geometry-builder.hpp
- options.cpp
- options.hpp
- output-pgsql.cpp
- reprojection.cpp
- reprojection.hpp
- tests/CMakeLists.txt
- tests/test-output-pgsql-area.cpp
- tests/test_output_pgsql_area.osm
Supersedes #454 which is no longer mergable because of cmake and geometry-builder refactoring.
@woodpeck could you check that it still works for you? I've done some minor cleanup especially wrt resource management but functionally it should be the same.
> Add area reprojection facility

- expire-tiles.cpp
- expire-tiles.hpp
- geometry-builder.cpp
- geometry-builder.hpp
- output-gazetteer.cpp
- output-multi.cpp
- output-pgsql.cpp
- processor-point.cpp
- table.cpp
- table.hpp
Changes geometry-builder to emit WKBs. Nodes are still built as WKTs at the moment.
Improves performance by 15-20%.
Planet import with `./osm2pgsql -d gis -S ../default.style --flat-nodes osm2pgsql.flatnodes -s -C 24000 --drop planet-150624.osm.pbf` on 32GB RAM all-SSD system with 6x2 CPUs yields:
master:
```
Node stats: total(2926993226), max(3610010794) in 1064s
Way stats: total(295111882), max(355378385) in 12100s
Relation stats: total(3493735), max(5307354) in 15387s
Pending ways took 9523s at a rate of 20389.88/s
Osm2pgsql took 55724s overall
```
use-wkb branch:
```
Node stats: total(2926993226), max(3610010794) in 1065s
Way stats: total(295111882), max(355378385) in 9093s
Relation stats: total(3493735), max(5307354) in 11710s
Pending ways took 8320s at a rate of 23338.07/s
Osm2pgsql …
```
> Convert geometries to WKB instead of WKT

- node-ram-cache.cpp
- node-ram-cache.hpp
* fixed an error in `node-ram-cache.hpp`
* make the headers work with msvc on windows
These changes have only been tested on Windows x64 with Visual Studio 2015.
> Fix build without FIXED_POINT

- expire-tiles.cpp
- geometry-builder.cpp
- geometry-builder.hpp
- geometry-processor.cpp
- geometry-processor.hpp
- output-gazetteer.cpp
- output-gazetteer.hpp
- output-multi.cpp
- output-multi.hpp
- output-pgsql.cpp
- processor-line.cpp
- processor-line.hpp
- processor-point.cpp
- processor-point.hpp
- processor-polygon.cpp
- processor-polygon.hpp
- table.cpp
- table.hpp
Renames wkt_t to the more neutral pg_geom_t and gets rid of the shared_ptr wrapper for it.
> Rename and clean up wkt_t

- output-pgsql.cpp
- output-pgsql.hpp
In way_add() tags have been filtered and then forwarded to pgsql_out_way() where they will filtered again. Moved filtering code out of pgsql_out_way() to avoid filtering twice altogether.
> avoid double-filtering tags on ways in pgsql output

- geometry-builder.hpp
- geometry-processor.cpp
- options.cpp
- osm2pgsql.cpp
- output-gazetteer.cpp
- output-pgsql.cpp
- parse-osmium.cpp
- parse-osmium.hpp
- reprojection.cpp
- reprojection.hpp
- tests/test-options-parse.cpp
- tests/test-output-multi-line-storage.cpp
- tests/test-output-multi-poly-trivial.cpp
- tests/test-output-multi-tags.cpp
- tests/test-output-pgsql-area.cpp
- tests/test-output-pgsql.cpp
- tests/test-parse-diff.cpp
- tests/test-parse-xml2.cpp
- make use of osmium's proj wrapper CRS
- use virtual functions instead of switching over projection
- remove duplicate code (mainly WSG84 to mercator transformation)
- use custom projections also with --proj 4326 and 900913 (fixes #514)
> rework projection code

- node-ram-cache.hpp
This should fix #521, but I haven't tested with a full planet.
> Use long ints for tracking cache hits

- table.cpp
This breaks compatibility with PostgreSQL 9.0, which has been EOL for months.
This increases pending ways speed by 5.2% (5m of 1h34m)
> Use UNLOGGED for non-permanant tables

- pgsql.cpp
> pgsql_execPrepared: check for null pointers when printing error message

- default.style
- style.lua
Removing a tag from default.style is backwards compatible for osm2pgsql, as the column will just no longer be updated.
There are only 41 nodes with this tag, and all seem to be tagging errors.
> Remove entirely unused POI tag

- README.md
- docs/usage.md
- expire-tiles.cpp
- options.cpp
- options.hpp
Default value is still 20000
new lines in --help --verbose output"
```
-B|--expire-bbox-size Max size for a polygon to expire the whole polygon,
not just the boundary.
```
> add command line option for EXPIRE_TILES_MAX_BBOX instead of hard coded value of 20000

- table.cpp
This avoids expensive UTF sorting when all we need is sorting by byte order.
Fixes #581
> Use C collation for ST_GeoHash ordering

- id-tracker.cpp
- id-tracker.hpp
- osmdata.cpp
- output-multi.cpp
- output-multi.hpp
- output-pgsql.cpp
- output-pgsql.hpp
- output.cpp
- output.hpp
This PR is essentially more cleanup. Not having a shared pointer also allows the compiler to optimize a bit more but in the grand schema of things the speedup is marginal.
> Remove remove shared_ptr wrappers around private class members

- expire-tiles.cpp
- expire-tiles.hpp
- options.cpp
- options.hpp
- output-multi.cpp
- output-pgsql.cpp
- tests/test-expire-tiles.cpp
- use unique_ptr for subtile managment and get rid of explicit malloc/free
- only save required options instead of reference to options
- hand in filename and minzoom as parameters to output_and_destroy(), they are not needed otherwise
- fix formatting where code was changed
> make tile expiry a proper C++ class

- processor-line.cpp
- processor-line.hpp
A line table needs to be "interested" in relations to handle route relations, admin as lines, and potentially other relations.
Fixes #593, although by a slightly different route
> Process relations for line tables

- table.cpp
When running with `-j` or `HSTORE_ALL`, it can make sense not to have any other columns present.
> Allow no columns for HSTORE_ALL mode

- expire-tiles.cpp
When applying an empty diff, the dirty pointer was empty and would segfault when trying to output_and_destroy.
> Guard against segfaults on expiry of empty diff

- README.md
As a newbie, I went looking for the OSM data to load. This seems to be canonical place. I could be wrong. I _think_ a link would be helpful.
> Add link to readme to find OSM data

- middle-pgsql.cpp
- middle-pgsql.hpp
- pgsql.cpp
- pgsql.hpp
Replaces the different static and malloc'd buffers for psql input with one global buffer. The same buffer is now used for copy mode and insert mode. We just track the beginning of each item for insert mode in the paramValues array.
This is more for cleanup, the gain in processing time is minimal.
> Use a global buffer for middle-pgsql

- docs/osm2pgsql.1
- docs/usage.md
- options.cpp
Cache options depend on the number of nodes that make it past the bounding box filter, so it's better to speak of import size, not extract size.
Replaces #551
> Refer to small imports, not extracts

- options.cpp
`--rri` writes XML changesets (`--wxc`)
`osm2pgsql` needs to be told to read from stdin (`-`)
> Correct command for Osmosis-powered updates

- options.cpp
- parse-osmium.cpp
When throwing an exception because libosmium cannot detect the
file format, the check for auto detection was wrong and thus
a confusing message was printed.
Also adds an explicit format switch for the usage example for
updating the database because libosmium cannot autodetect formats
when reading from stdin.
> fix error for failed format dectection and format in usage example

- multi.style.json
- tests/test_output_multi_tags.json
Json does not allow for comments and starting with version
1.59.0 boost is no longer able to parse them.
Fixes #647
> remove comments in json configuration files

- table.cpp
- table.hpp
- taginfo.cpp
- taginfo.hpp
- taginfo_impl.hpp
Scans the style file for additional int and real data types
and mappes them all to the existing int and real conversion
routines.
Fixes #621.
> allow more numeric datatypes for table columns in C tagtransform

- output-gazetteer.hpp
fixes https://trac.openstreetmap.org/ticket/5434
> gazetteer: correctly escape backslashes

- parse-osmium.cpp
- parse-osmium.hpp
Update the progress report only once per second to avoid
too many costly printfs on fast machines.
> reduce verbosity when reading OSM data

- geometry-processor.cpp
- geometry-processor.hpp
- multi.lua
- output-multi.cpp
- output-pgsql.cpp
- tagtransform.cpp
- tagtransform.hpp
- tests/test_output_multi_poly_trivial.lua
Although it appears in our Lua API, it's only a positional arg so correcting the spelling doesn't break anything.
> Correct spelling of superseded

- CMakeLists.txt
Add PostgreSQL 9.6 to cmake additional search paths to ensure a smooth install if Postgres was installed from http://yum.postgresql.org/.
> Add Postgres 9.6 to cmake additional search paths

- CMakeLists.txt
This will break on newer CMake versions (>=3.3) since PostgreSQL_ADDITIONAL_SEARCH_PATHS is not honored there anymore. Use CMAKE_PREFIX_PATH instead, which is the generic solution that works with all versions of CMake and all find modules.
Tested on CentOS 7 with CMake 2.8.12.2 and 3.7.1.
> fix finding PostgreSQL from yum.postgresql.org with newer CMake versions

- .clang-format
- CONTRIBUTING.md
- middle-pgsql.cpp
Running clang-format on the current code touches about 5k lines, which is a bit excessive. So I would suggest to require running git-clang-format for all future PRs.
> Add config for clang-format

- docs/lua.md
- docs/osm2pgsql.1
- docs/usage.md
- options.cpp
- options.hpp
- tests/common-pg.cpp
- tests/test-options-database.cpp
- tests/test-options-parse.cpp
Instead of defaulting to gis, the default database is unspecified, and libpq will decide what to connect to in those cases. This will normally rely on `PGDATABASE` or its compiled defaults.
Fixes #561
> Do not assume a default database name

- osmium-builder.cpp
> Don't give a variable name for an exception nothing is done with

- output-gazetteer.cpp
Fixes #309
The test coverage of the gazetteer backend is lacking, but these are the type of changes which tend to cause obvious failures, not subtle ones.
> Use modern geometry types for gazetteer backend

- osmdata.cpp
Geos isn't used anymore, so this isn't needed.
Fixes #700
> Don't configure thread locale for geos

- options.cpp
- tests/test-options-database.cpp
This sets a default application name which then appears in DB logs and pg_stat_activity.
Fixes #707
Tested by watching pg_stat_activity while running the tests.
> Set fallback_application_name

- options.cpp
> disable --unlogged only when --append is explicitly given

- parse-osmium.cpp
There is a hard restriction in the pgsql middle tables, where relation members are indexed using a smallint. This change just restricts to the technical limit to fix the issue with the diff file.
Fixes #713.
> Ignore relations with more than 32k members

- osmium-builder.cpp
Fixes #724 
Git is trying to do something rather odd with the whitespace and the diff, https://github.com/openstreetmap/osm2pgsql/compare/master...pnorman:builder_scope?w=1 is a saner view of the changes
> Restrict the scope of osmium::builders

- middle-ram.hpp
> middle-ram: properly deallocate in clear() function

- middle-pgsql.cpp
- output-gazetteer.cpp
- pgsql.cpp
- pgsql.hpp
- table.cpp
- table.hpp
Wrap all instances of PGresult in a unique_ptr that automatically
calls PQclear on destruct to avoid accidental resource leaks.
Fixes #731.
> autodestruct PGresult

- output-gazetteer.cpp
- output-gazetteer.hpp
Removes all address columns and adds a generic hstore instead. This way, we have the origin for all address parts later in the geocoder.
> Gazetteer: use hstore column for address parts

- expire-tiles.cpp
- expire-tiles.hpp
- options.cpp
- options.hpp
- output-multi.cpp
- output-pgsql.cpp
- tests/test-expire-tiles.cpp
- tests/test-options-parse.cpp
This pull request contains the changes announced in #709.
This pull request is the first part of a rewrite of the tile expiry. It is a port of the tile expiry of [my own](https://github.com/Nakaner/Cerepso) PostgreSQL import tool to osm2pgsql which I wrote as part of my master thesis. I needed an importer with a tile expiry which handles relations in much different way than osm2pgsql does and the tile expiry had to be more exact.
Each tile is represented by a 64-bit integer (bits of Y and X index interleaved). The set only contains the tiles at the highest zoom level where the list of expired tiles should be generated. All lower requested zoom levels are calculated during writing the tile IDs to the output file by shifting the bits of the tile IDs.
I did a performance test with an import …
> Rewrite tile expiry (management of expired tiles)

- osmium-builder.cpp
- wkb.hpp
Calling the finish functions clears the internal
buffer of the WKB factory, so always call them even
if the geometry is not used afterwards.
Found while using planet updates on an extract import.
Also removes some unused functions from wkb factory.
> Finish wkb properly

- geometry-processor.cpp
- geometry-processor.hpp
- output-multi.cpp
- output-multi.hpp
- processor-line.cpp
- processor-line.hpp
- processor-point.cpp
- processor-point.hpp
- processor-polygon.cpp
- processor-polygon.hpp
Processors are shared between threads and therefore
cannot hold the stateful wkb builders. Keep them in
output-multi instead and hand them in when calling
the process functions.
Fixes #773.
> move builder from processors to output-multi

- table.hpp
The counter in wkb_reader was always initialized with 0 (`result` being nullptr after having just been moved to `m_result`). So expiry from_db() has not been doing anything for a long time now.
As a test, import a single way and then append a change which modifies a node on this way.
@Nakaner Would you mind running this change through your setup? It is more extensive then my tests when it comes to expiry.
Fixes #766.
> Fix counter initialisation in wkb_reader

- geometry-processor.cpp
- geometry-processor.hpp
- osmtypes.hpp
- output-multi.cpp
- output-pgsql.cpp
- style.lua
- tagtransform-c.cpp
- tagtransform-c.hpp
- tagtransform-lua.cpp
- tagtransform-lua.hpp
- tagtransform.hpp
Tags for ways of multipolygons are no longer prefiltered before handing them into the relation member filter function. For new-style MPs the tags are not relevant anyways. For old-style MPs, the filter now first creates a list of common tags and then filters the result with the standard relation tags filter.
I have adapted style.lua but noticed that old-style MPs are handled slightly differently. The tags of the MP are computed as the union of all tags on the out ways while the C transform computes them as the intersection of tags. I haven't touched multi.lua yet.
Tests pass but it could possibly do with visual verification that results are the same.    
Fixes #605 and #659.
> Don't pre-filter relation member tags

- README.md
* Adding additional libraries needed to build to Fedora install command
* Changing `yum` to `dnf`
* Adding specific Fedora versions using GEOS 3.5.1 by default in the package manager
* Adding a note as to why Fedora 26 has incompatible GEOS library, linking issue
> Update Fedora build instructions

- options.cpp
The lintian QA tool reported a spelling errors for 0.94.0-rc1:
* mimimum -> minimum
> Fix spelling errors.

- node-ram-cache.hpp
Compiling the current master on F27 gives the warning below. It turns out that the `set_used()` macro and the dirty bit handling is no longer used and can be removed.
<pre>In file included from /home/jburgess/osm2pgsql/options.hpp:4:0,
from /home/jburgess/osm2pgsql/expire-tiles.cpp:18:
/home/jburgess/osm2pgsql/node-ram-cache.hpp: In member function ‘void ramNodeBlock::set_used(int)’:
/home/jburgess/osm2pgsql/node-ram-cache.hpp:43:45: warning: ‘<<’ in boolean context, did you mean ‘<’ ? [-Wint-in-bool-context]
void set_used(int used) { _used = (used << 1) || (_used & 1); }
~~~~~~^~~~~
</pre>
All the tests pass after making this change.
> simplify ram node cache by removing unused dirty bit support

- osmdata.cpp
The pending processor holds shared_ptr references to the node caches. That prevents the caches from    being freed when mid::stop() is called. This change makes  sure the pending processor goes out of scope before indexing starts.
@StyXman This resolves the problem with not freeing cache memory. Turned out to be a completely different issue. So no further changes for the stop() function needed.
> Make sure cache is freed before starting indexing

- middle-pgsql.cpp
- middle-pgsql.hpp
- middle-ram.cpp
- middle-ram.hpp
- middle.hpp
- osmdata.cpp
- output-gazetteer.cpp
- output-gazetteer.hpp
- output-multi.cpp
- output-multi.hpp
- output-null.cpp
- output-null.hpp
- output-pgsql.cpp
- output-pgsql.hpp
- output.hpp
- tests/mockups.hpp
- tests/test-middle-flat.cpp
- tests/test-middle-pgsql.cpp
- tests/test-middle-ram.cpp
Use an Osmium worker pool instead of std::async and restrict the number of parallel instances to the number requested on the command line. Use the same pool for middle and output tables and make sure that the option --disable-parallel-indexing is also respected for middle tables.
> Rework multi-threading during indexing

- options.cpp
This option is now so frequently used that it deserves a
short option and to be listed more prominently in the help.
Also adapted the size.
> add short option for flat-node file

- appveyor.yml
The windows builds available as appveyor artifacts has some issue. So some enhancement added to fix these issues. The main reason for these changes, is issue #812. Because of old zlib (1.2.8) version used for builds, the created binary is not running on windows 7. This pull request fix issue #812 by changing the zlib from 1.2.8 to 1.2.11 (latest). Also other libraries are updated. Finally,  windows 32 bit version also will be built (fixes issue #803).
List of changes:
1. Update libraries:
- expat: 2.2.0 -> 2.2.5
- lua: 5.1.5 -> 5.3.4
- zlib: 1.2.8 -> 1.2.11
- wingetopt (Build both x86 and x64 by myself using [https://github.com/alex85k/wingetopt](https://github.com/alex85k/wingetopt))
2. Build matrix for both x86 and x64 builds.
PostgreSQL 9.4.7 lib used to build. But PostgreSQL 9.6 used …
> Appveyor enhancement

- appveyor.yml
The downloaded packages are causing trouble with appveyor. Postgis has changed versions and does not leave older versions available and sourceforge is unbearably slow. I've put copies of the packages on the OSM dev server which appveyor now uses. There is a README in the download directory that explains where they originally came from, so that we can get updates when necessary.
> appveyor: use locally cached packages

- CMakeLists.txt
- options.cpp
On Windows the default is now to look for the style in
the working directory. This can be changed via a cmake
variable if somebody wants to provide a version that
is installed into the system directories.
> make default style configurable and change default for WIN32

- appveyor.yml
Fix the issue that mentioned https://github.com/openstreetmap/osm2pgsql/pull/820#issuecomment-368642226
Now the artifacts can be accessed using below URLs:
- x86: [https://ci.appveyor.com/api/projects/openstreetmap/osm2pgsql/artifacts/osm2pgsql_Release_x86.zip?job=Environment%3A%20arch%3Dx86](https://ci.appveyor.com/api/projects/openstreetmap/osm2pgsql/artifacts/osm2pgsql_Release_x86.zip?job=Environment%3A%20arch%3Dx86)
- x64: [https://ci.appveyor.com/api/projects/openstreetmap/osm2pgsql/artifacts/osm2pgsql_Release_x64.zip?job=Environment%3A%20arch%3Dx64](https://ci.appveyor.com/api/projects/openstreetmap/osm2pgsql/artifacts/osm2pgsql_Release_x64.zip?job=Environment%3A%20arch%3Dx64)
Also the "platform" environment variable renamed to "arch" because the collision with VisualStduio's …
> Appveyor artifacts fix

- options.cpp
- tests/test-options-parse.cpp
Changes:
* add support to parse `-e 12` (no maximum zoom level given)
* better error messages
* more unit tests for parsing the argument of `-e`
This fixes #830.
> Fix parsing of command line option "-e 12" (no expiry maxzoom given)

- CMakeLists.txt
- cmake/FindOsmium.cmake
- cmake/FindProtozero.cmake
Scripts are copied from libosmium 2.14.0. The protobuf script will properly check for the headers and allow to include an external version.
Require libosmium 2.14 because of the external protobuf library.
> update Osmium cmake script and add one for protobuf

- output-gazetteer.cpp
Fixes https://github.com/openstreetmap/Nominatim/issues/823.
> gazetteer: ignore name:suffix tag

- osmdata.cpp
- tests/test-parse-xml2.cpp
- tests/test_output_multi_line_storage.osm
- tests/test_output_multi_poly_trivial.osm
When adding objects call output backends only when there
are any tags. Only works for the initial import. When updating
data, all objects need to be forwarded in case they need to
be deleted. That also means that output backends still must
be able to handle untagged objects.
Fixes #706.
> Skip output for untagged objects

- README.md
The artifact download links to Appveyor have changed due to the 32bit build.
> adapt windows download links

- tagtransform-lua.cpp
- tests/test-options-parse.cpp
Fixes #841
Returns new error message:
```
osm2pgsql version 0.95.0-dev (64 bit id space)
Using lua based tag processing pipeline with script openstreetmap-carto2.lua
Lua tag transform style error: cannot open openstreetmap-carto2.lua: No such file or directory
Error: Failed to initialise tag processing.
Error occurred, cleaning up
```
> Return error when Lua tag transform cannot be read

- cmake/config.h.in
- options.cpp
Now that we have a number of compile time options, `osm2pgsql -V` should print some more details about used libraries to facilitate future issue analysis.
```
osm2pgsql version 0.96.0-RC1 (64 bit id space)
Compiled using the following library versions:
Libosmium 2.14.0
Lua 5.2.4
```
```
osm2pgsql version 0.96.0-RC1 (64 bit id space)
Compiled using the following library versions:
Libosmium 2.14.0
Lua 5.1.4 (LuaJIT 2.0.4)
```
```
osm2pgsql version 0.96.0-RC1 (64 bit id space)
Compiled using the following library versions:
Libosmium 2.14.0
Lua support not included
```
> Command line option "-V" to include library versions

- table.cpp
Names are hardcoded now, but that leads to #847 in unfortunate event when tables were renamed but their respective indexes still have previous name, that you need to import once again.
> Let postgres resolve non conflicting index names itself

- tests/CMakeLists.txt
`LUA_FOUND` is only set in case of a Lua interpreter, but not for LuaJIT. By using `HAVE_LUA` we can find out about Lua support regardless of the actual implementation used.
> Use HAVE_LUA to check for Lua availability

- osmdata.cpp
- osmdata.hpp
- tests/CMakeLists.txt
- tests/test-parse-extra-args.cpp
Also adds a test for parsing with extra-attributes enabled.
Fixes #849.
> Always fully parse objects when extra attributes are requested

- docs/pgsql.md
> make clear that slim tables are an internal implementation detail

- middle-pgsql.cpp
- middle-pgsql.hpp
- middle-ram.cpp
- middle-ram.hpp
- middle.hpp
- osmdata.cpp
- tests/mockups.hpp
Rewrite get_instance() to receive the shared pointer as a parameter
and get rid of the no_delete() hack which essentially renders the
shared pointer mute.
Also get rid of const for middle_query_t. There is no point in
adding this as the middle_query_t interface is completely const
already.
> Refactor getting read-only middle object

- middle-pgsql.cpp
- middle-pgsql.hpp
- middle-ram.cpp
- middle-ram.hpp
- middle.hpp
- tests/mockups.hpp
commit() does exactly the same and is the one used.
> remove unused middle::end()

- middle-pgsql.cpp
- middle-pgsql.hpp
- middle-ram.hpp
- middle.hpp
- osmdata.cpp
- osmdata.hpp
- parse-osmium.cpp
- parse-osmium.hpp
- tests/mockups.hpp
Introduce flush when type of import object changes, which replaces the endCopy operation in the middle_t
read functions. These functions are const and never should have called a function that changes state.
Instead of falling out of copy then, all copy operations are finished, when processing of an OSM type is done. Read functions should never be called when actually processing the same table, so the one-time end-copy is sufficient.
Also remove vector of table_desc and use a fixed sized array instead. Remove the pointer indirections to the vector entries and use index consts into the array.
> middle-pgsql: Flush between type changes

- middle-pgsql.cpp
- middle-pgsql.hpp
* Convert table_desc into a full class that also provides functions for most of the SQL accesses.
* Convert C strings for SQL commands into std::string. Fixes #731 .
* Remove SQL command strings that are fixed for all tables and replace them with wrapper functions.
> Middle-pgsql: cleanup table access code

- middle-pgsql.cpp
- middle-pgsql.hpp
- middle-ram.hpp
- middle.hpp
- osmdata.cpp
- osmdata.hpp
- parse-osmium.cpp
- tests/mockups.hpp
#889 moved the end of copy for middle tables away from query functions but did so a little bit to eagerly. The result is that copy mode is never used for ways and relations. This changes the behaviour to only throw tables out of copy mode that may actually be used by the OSM type next being read.
> middle-pgsql: be less eager with ending copy mode

- .travis.yml
- CONTRIBUTING.md
- tests/CMakeLists.txt
- tests/fixture-tablespace-cleanup
- tests/fixture-tablespace-setup
This mostly requires fixtures to create and destroy the test tablespace. pg_virtualenv itself needs to be wrapped around the call to ctest. The old way of running on the main database on the system still works as before.
Currently enabled for posix-like systems only. For travis only enabled for tests on Linux.
Fixes #234.
>  Tests: enable running tests inside pg_virtualenv

- table.cpp
A geometry can be valid in OSM but invalid in whatever projection is chosen. This will raise a NOTICE in postgres, which is just noise and can potentially confuse users.
Fixes #838
> Avoid notice noise about geom validity

- middle-pgsql.cpp
- middle-pgsql.hpp
- middle-ram.cpp
- middle-ram.hpp
- middle.hpp
- osm2pgsql.cpp
- osmdata.cpp
- tests/common.hpp
- tests/middle-tests.hpp
- tests/mockups.hpp
- tests/test-middle-flat.cpp
- tests/test-middle-pgsql.cpp
- tests/test-options-parse.cpp
- tests/test-output-multi-line.cpp
- tests/test-output-multi-point-multi-table.cpp
- tests/test-output-multi-point.cpp
- tests/test-output-multi-polygon.cpp
- tests/test-output-pgsql.cpp
This PR changes middle-pgsql to have separate implementations for middle_query_t and middle_slim_t. The main advantage of this setup is that the query class is much more lightweight and opens only one connection to the database. This means that we save 2*num_thread connections in the processing phase (improves on #885).
Given that output now also receive a middle_pgsql_query instance, some structural changes were necessary:
* Tables need to be created before the query instance is created because of prepared queries. They are set up during construction of the query instance and that requires that the table the prepared query references has already been created. Therefore middle::start() has been moved to osm2pgsql.cpp and is now done before output are set up.
* As the data is queried on a …
> Split pgsql middle into query and insertion class

- output-multi.cpp
- output-multi.hpp
- output-pgsql.cpp
- output-pgsql.hpp
- tagtransform-c.cpp
- tagtransform-c.hpp
- tagtransform-lua.cpp
- tagtransform-lua.hpp
- tagtransform.cpp
- tagtransform.hpp
- tests/test-options-parse.cpp
This PR cleans up two things:
* Convert tables member to std::array. The size of the array is known at compile time and does not change, so a vector is not necessary here.
* export_list is moved to the transform classes. The style file is only used by output-pgsql to create the columns. During the actual import it is only handed to the transforms on every filter call. Moving the export_list to transforms makes the filter calls more more readable and also gives us the freedom to change the style description format independently for the transforms.
Have a look at the individual commit for each change.
> Some cleanup for output-pgsql members

- output-multi.cpp
- output-pgsql.cpp
- output.cpp
- table.cpp
- table.hpp
Moves some of the parameters to start() and stop(). As some of them are only used locally in the function, they can even be removed as members.
Also removes index on the temporary table. This should never be needed on the initial import. It is created on the final table in stop() again, where it is needed for later updates
> Split table_t constructor

- node-ram-cache.cpp
- options.cpp
When -C 0 is given, none of the management structures of node caches will be created, saving another 600 MB of memory.
Only allow when using slim mode. Advisable to be used only in conjunction with flat node storage.
> Allow to truely disable the RAM node cache

- table.cpp
- table.hpp
> Prepare get_wkb on copy connections as well

- db-copy.hpp
- gazetteer-style.cpp
- gazetteer-style.hpp
- output-gazetteer.hpp
`--extra-attributes` is now supported by Gazetteer output. This pull requests writes all metadata fields to as to the `extratags` column.
If an OSM object lacks a metadata field (empty string or 0 as value) which is/will be common with usual OSM planet dumps and extracts, the field will not be written to the output.
Users can control whether they want all metadata fields or only specific ones. If the Nominatim style file (the new one, see #1277) contains a catch-all rule at the end, that catch-all rule will apply on all available metadata fields and they will be written to the `places` table. If one or many of the metadata fields are mentioned in an `extra` rule and no catch-all rule is present, only that field will be written.
**Example 1: write all tags and all metadata fields to the …
> Add support for --extra-attributes to Gazetteer output

- README.md
Proposed updated for README.md to include instructions on how to enable LuaJIT. 
Follow up for https://github.com/openstreetmap/osm2pgsql/issues/801#issuecomment-471168931
> Adding LuaJIT instructions to README

- gazetteer-style.cpp
- gazetteer-style.hpp
- output-gazetteer.cpp
When downgrading an unnamed object from SF_MAIN to SF_MAIN_NAMED,
the object needs to be deleted. Finding that condition in has_data()
is a bit expecsive, so instead catch the condition when copying
the data out. If there are multiple main tags, then
delete_unused_classes() needs to remove the instance as well.
Adapt has_place() for that.
Fixes #933.
> gazetteer: handle updates of unnamed places

- table.cpp
- tests/CMakeLists.txt
- tests/test-output-pgsql-int4.cpp
- tests/test_output_pgsql_int4.osm
- tests/test_output_pgsql_int4.style
Fixes #955
This approach also avoids undefined behaviour when using sscanf, and changes the mean calculation to avoid overflows.
As part of the development of this patch I made [a sample osm.xml file with a variety of numbers and ranges](https://gist.github.com/gravitystorm/409b5f651f013ac5a49ff71f84b82d37), to check that everything was working properly.
> Avoid crashing on out-of-range inputs for int4 columns

- options.cpp
Parallel processing is used only when indexes are created and
in the second processing stage of updates. In both cases the
number of parallel threads should not be too high. Indexing
requires a lot of memory and having too many in parallel running
actually slows down the process. Updates are generally run in
parallel with other load (like rendering) and should therefore
also not take up too many CPUs.
Fixes #885.
> Reduce max number of default parallel threads to 4

- db-copy.cpp
- db-copy.hpp
If PostgreSQL is much slower than the data processing, the queue can become very large and lead to out-of-memory errors.
> limit the number of buffers that are in the copy queue

- CMakeLists.txt
The `FIXED_POINT` macro was used earlier, but isn't used any more in the current code.
> Remove unused definition

- node-ram-cache.cpp
Adds `assert` to document place that need to be fixed.
See #965
> Add assert to show where fix is needed

- .clang-tidy
- CMakeLists.txt
This changes the CMake config to add a target "clang-tidy". It also adds a very basic clang-tidy config that will run almost all available checks. This is only to get us going. We'll probably want to disable some clang-tidy checks in the future.
> Add clang-tidy make target and basic clang-tidy config.

- id-tracker.cpp
- id-tracker.hpp
- node-ram-cache.hpp
- reprojection.hpp
In C++11 we can express this in better way.
> Remove use of boost::noncopyable

- tagtransform-lua.cpp
- tests/data/test_output_multi_line_trivial.style.json
- tests/data/test_output_multi_poly_trivial.style.json
- tests/data/test_output_multi_tags.json
Note that this is a breaking change. Users might have to change the file
names of their lua scripts in the style files.
See #321.
> Look for lua script relative to style.json file.

- tests/CMakeLists.txt
- tests/test-options-projection.cpp
Removes the last relative style location from the projection tests and removes the working directory for catch tests from the ctest configuration.
This means that now all tests except the regression test can be executed directly from the build directory.
Fixes #540.
> Make test execution of catch tests independent of working directory

- src/db-copy-mgr.hpp
- src/db-copy.cpp
- src/db-copy.hpp
- src/gazetteer-style.cpp
- src/gazetteer-style.hpp
- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/output-gazetteer.cpp
- src/output-gazetteer.hpp
- src/table.cpp
- src/table.hpp
- tests/test-db-copy-mgr.cpp
- tests/test-db-copy-thread.cpp
Objects so far have been deleted directly from the main thread in gazetteer. This may lead to deadlock as the updates in the copy thread trigger SQL triggers which may touch an object currently being deleted.
Gazetteer objects are now deleted in the copy thread in a batch just like we do for all other tables. For this we need a different kind of deleter as the primary key is different for gazetteer's place table. For this, delete lists become first class objects and the copy manager becomes responsible for adding the right deleter to the copy buffer object.
Fixes #964.
> Fix deletion on update in gazetteer

- src/output-gazetteer.cpp
- src/output-gazetteer.hpp
Addendum for #1008.
With deletion pushed to the copy thread, there is no need to keep a connection open in the main thread.
> gazetteer: remove connection for main thread

- src/osmdata.cpp
- src/osmdata.hpp
The result of these functions is not used, so they can be void. This is the first part of a refactoring, the same will be needed for the functions in the outputs called by the functions here.
> Change return type of osmdata member functions to void

- src/gazetteer-style.cpp
- src/gazetteer-style.hpp
- src/output-gazetteer.cpp
- src/output-gazetteer.hpp
- tests/common-import.hpp
- tests/test-output-gazetteer.cpp
Filtering of main tags (i.e. handling of named-only tags or fallback tags) must happen before the actual output because the filtered list is already needed when computing the list of classes to keep. Currently the function that creates the  class list does its own filtering and is inconsistent with  what the output function does.
Also fixes use of new_line().
> Gazetteer: move main tag filtering into processing function

- src/db-copy-mgr.hpp
- src/db-copy.hpp
- src/gazetteer-style.hpp
As we have to issue a delete for each and every untagged node,
the number of scheduled deletes can become quite large even for
a small change file. It is better to send off the copy buffer
a bit earlier in this case to ensure that the deletes can already
run in parallel with the parsing of the file. The change also
ensures that the memory usage of the deleter is bound.
> Limit the number of scheduled deletes

- src/osmdata.cpp
- src/osmdata.hpp
- src/output-gazetteer.cpp
- src/output-gazetteer.hpp
- src/output-multi.cpp
- src/output-multi.hpp
- src/output-null.cpp
- src/output-null.hpp
- src/output-pgsql.cpp
- src/output-pgsql.hpp
- src/output.hpp
- tests/test-parse-osmium.cpp
This is the second batch of changes after #1020 switching the return type of some functions from int to void where the result is never used.
> Make some functions return void instead of int

- src/gazetteer-style.cpp
In a domain-specific key like `bridge:name`, we'd only want to cut the tag prefix, i.e. `bridge:`.
> gazetteer: fix keys for domain-specific naming

- src/node-ram-cache.cpp
This is triggered in some of our tests.
> Fixes UB (division by zero)

- src/middle-pgsql.cpp
- src/pgsql.cpp
- src/pgsql.hpp
- src/table.hpp
- tests/common-pg.hpp
Refactor low-level PostgreSQL code in the tests to use the low-level PostgreSQL code used in the application. This gives us simpler and better tested code and we can use convenience functions originally only implemented in the test code.
This also marks the tempdb_t constructor noexcept.
> Refactor tests pg code

- src/node-ram-cache.cpp
This fixes a memory leak in the node cache reported when compiling with clang sanitizers and running the tests. I am not sure though, whether this is a correct fix, because I don't understand all the code around it.
> Fix memory leak in node cache

- src/output-gazetteer.cpp
- src/output-gazetteer.hpp
- tests/test-output-gazetteer.cpp
There was still a case were a delete function was called on an unprepared buffer leading to a segfault. This PR attempts to fix that once and for all.
Move prepare() call into delete functions to make sure that it is really called. Also reorganise how the delete functions are called to ensure that only one delete is executed per object.
Also adds a test for full delete of a node.
> Gazetteer: reorganize deletion of objects

- .travis.yml
The osx build has been broken for unknown reasons for the last two weeks and is a blocking point for pending PRs. See also #1035.
> travis: disable build on osx

- src/gazetteer-style.cpp
Country and postcodes have their own flag in the style file and
need special treatment. They are, however, eventually added to
the hstore of address tags. So we need to make sure that they
are not overwritten by ordinary address tags.
See also https://github.com/openstreetmap/Nominatim/issues/1606
> gazetteer: exclude country and postcode from address tags

- src/db-copy.cpp
- src/db-copy.hpp
The finish_copy() method was called from the main program and from the
copy thread leading to a race condition.
I have fixed not only this but clearly separated out everything
happening in the main thread from everything in the copy thread by
putting the code for the latter into its own class. This way a
problem like this can not happen again.
> Bugfix: Threading problem in db_copy_thread_t

- tests/test-output-gazetteer.cpp
Parametrize gazetteer tests so that not only nodes are imported but also ways and relations. Geometries are created at random. For relations a simple tetragon from a single way is used.
> Extend gazetteer tests to ways and relations

- .travis.yml
- README.md
- tests/CMakeLists.txt
- tests/regression.py
Complete restructuring of the test setup:
* No longer use the postgresql service infrastructure provided by travis. Completely run inside pg_virtualenv instead.
* Make postgres and postgis versions configurable.
* Test oldest (on xenial) and newest (on bionic) for each supported compiler.
* Test all supported versions of postgis and postgres.
Given that the postgres version is not relevant for compiling osm2pgsql (the client library
is always the newest available), we can do the last point in one go after compiling once. Only drawback is that the travis now runs about twice as long.
This change also increases the minimum required versions of gcc (5.0), clang (3.5), postgresql (9.3) and postgis (2.2). These are the oldest versions we run. If the EOL versions of postgresql or postgis fail …
> Move travis to xenial/bionic

- tests/data/gazetteer-test.style
- tests/regression.py
- tests/test-output-gazetteer.cpp
These test check that tags are processed according to the import style configuration options. Most of the tests already existed in a very similar form as part of the [Nominatim test suite](https://github.com/openstreetmap/Nominatim/blob/master/test/bdd/osm2pgsql/import/tags.feature). The goal is to remove the osm2pgsql-only tests there and have them here instead.
Requires a small adaption to the regression test numbers as the gazetteer test style has changed a bit to be able to accommodate all test cases.
> Add more tests for the gazetteer configuration options

- src/pgsql.hpp
- src/table.cpp
Refactor the last place where a PQ* function was used directly outside
pgsql.[ch]pp.
> Refactor call of PQfnumber function

- src/output-pgsql.cpp
xid2 is filled but never used.
> Remove dead code

- src/osmdata.cpp
- src/output-pgsql.cpp
- tests/test-options-parse.cpp
Inside the pgsql output (and only in that output) we checked whether we
are in append mode in (the node|way|relation)_(modify|delete) functions.
This is not needed because oms2pgsql checks early on that option -a
isn't used without -s.
This can also be seen because at the callsite of those functions we are
doing an unchecked dynamic_cast that would have failed and returned a
nullptr if we are not in slim mode. So we would have never reached those
checkes. I have added assert()s to make clear we are relying on those
dynamic_casts to work.
> Remove superfluous checks for append mode.

- CONTRIBUTING.md
- tests/common-pg.hpp
If you have failing tests and want to look at the test database to
figure out what's happening, you can now set the environment variable
`OSM2PGSQL_KEEP_TEST_DB` to anything. This will disable the database
cleanup at the end of the test.
> Disable test db cleanup by setting OSM2PGSQL_KEEP_TEST_DB env var

- .travis.yml
Executing ctest multiple times against different postgres versions in a for loop means that travis only sees the result of the final run. Change the code to exit with an error immediately when a ctest run fails.
Note that this also means that the 'after_failure' trigger is not executed on such a failure. Given that it only tries to recompile, we don't care much about it anyway.
> travis: fail everything when ctest fails

- src/geometry-processor.cpp
- src/osmium-builder.cpp
- src/osmium-builder.hpp
- src/output-gazetteer.cpp
- src/output-gazetteer.hpp
- src/output-multi.cpp
- src/output-pgsql.cpp
- src/processor-polygon.cpp
- src/processor-polygon.hpp
With the old code the decision whether to generate many single polygons
or one multipolygon is done when creating the osmium_builder_t object
(based on a command line argument). This change optionally allows this
to be set when each (multi)polgyon is build. This flexibility will be
used later to allow setting this on a table-by-table basis.
> Allow decision on single/multi geometry for each geometry

- CMakeLists.txt
- cmake/config.h.in
- src/CMakeLists.txt
- src/options.cpp
- src/reprojection-generic-none.cpp
- src/reprojection-generic-proj4.cpp
- src/reprojection.cpp
- src/reprojection.hpp
- tests/common-options.hpp
- tests/test-options-projection.cpp
If the proj library cannot be found by cmake, do not offer
the option to use arbitrary projections.
Also changes reprojection interface to return managed pointers
for the projection.
Fixes #1065.
> make PROJ library optional

- flex-config/README.md
This fixes the link in the documentation to have the correct target path.
> Fix relative path link to main flex documentation

- tests/data/test_output_flex_fail.lua
- tests/data/test_output_flex_uni.lua
"table" is a predefined name in Lua, overwriting it could be confusing
> Use "test_table" instead of just "table" for Lua variable names

- src/osm2pgsql.cpp
- src/parse-osmium.cpp
- src/parse-osmium.hpp
This way we always get the correct relations count and more correct
count per second.
Fixes #1115
> Always write processing stats after all parsing is done

- src/id-tracker.cpp
- src/id-tracker.hpp
- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/middle-ram.cpp
- src/middle-ram.hpp
- src/middle.hpp
- src/osmdata.cpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/output-multi.cpp
- src/output-multi.hpp
- src/output-pgsql.cpp
- src/output-pgsql.hpp
- src/output.cpp
- src/output.hpp
- tests/test-middle.cpp
- tests/test-parse-osmium.cpp
Also refactors `pending_count()` into `has_pending()` because the count is never used.
> Tests for middle around id-tracker

- src/lua-utils.cpp
- src/lua-utils.hpp
- src/output-flex.cpp
- src/output-flex.hpp
Closes #1136
Almost exactly the same code that is in use in the Lua interpreter, except for the signal handling: https://github.com/lua/lua/blob/master/lua.c#L109-L142
> Provide a stack trace on a lua error with flex backend

- src/middle-pgsql.cpp
- src/osmdata.cpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/output-gazetteer.hpp
- src/output-multi.cpp
- src/output-multi.hpp
- src/output-null.hpp
- src/output-pgsql.cpp
- src/output-pgsql.hpp
- src/output.hpp
- tests/test-middle.cpp
Refactoring of the dependency tracking code split between middle and outputs. This basically just removes some code that wasn't used anyway in several steps in each commit. Further work will follow.
> Refactor dependency tracking step1

- src/db-copy.hpp
Because of the std::mutex inside the class. This makes this clear.
> Move constructor/assignment of db_copy_thread_t is deleted anyway

- .travis.yml
- src/lua-utils.cpp
> luaL_traceback is not supported in Lua 5.1, except for LuaJIT

- src/CMakeLists.txt
- src/dependency-manager.cpp
- src/dependency-manager.hpp
- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/middle-ram.hpp
- src/middle.hpp
- src/osm2pgsql.cpp
- src/osmdata.cpp
- src/osmdata.hpp
- src/output.hpp
- tests/common-import.hpp
- tests/test-middle.cpp
- tests/test-output-multi-point-multi-table.cpp
- tests/test-parse-osmium.cpp
The new dependency manager takes over some of the responsibilities of the middle. This way we decouple the dependency tracking from the object storage. It makes the code easier to understand and to change.
There are more refactorings coming after this.
> New dependency manager

- .travis.yml
Ubuntu 20.04 (Focal) is available on Travis. This PR adds a job for Postgres 12, Postgis 3, LuaJIT and gcc 9 on Focal.
> Travis: add Ubuntu 20.04

- src/osm2pgsql.cpp
- src/osmdata.cpp
- src/osmdata.hpp
- tests/common-import.hpp
Give options to `osmdata_t` constructor instead of getting them from outputs.
> Get options into osmdata

- .clang-tidy
Lots of warnings that we don't want are disabled now.
> Extend the clang-tidy config to make it more usable

- src/options.cpp
- src/options.hpp
- src/osm2pgsql.cpp
- src/parse-osmium.cpp
* Rename option "input_reader" to "input_format".
* Also rename a parameter from "fmt" to "format" because "fmt"
is used as namespace for the format library we are using.
* Change default setting for autodetecting the file format from
"auto" to simply the empty string. This matches the way the
underlying osmium library does it.
> Rename file format option and simplify default (auto) case

- src/flex-table.cpp
- tests/test-output-flex-uni.cpp
- tests/test-output-flex-update.cpp
Tables that can take different OSM types have a type and an id column,
because the expire functionality needs to find and remove rows by type
and id. The query that does this was broken, so it never found anything.
> Fix flex backend expire for tables with type/id columns

- src/osm2pgsql.cpp
- src/osmdata.cpp
- src/osmdata.hpp
- src/parse-osmium.cpp
- src/parse-osmium.hpp
- tests/common-import.hpp
This leaves only the functionality as Osmium handler in parse_osmium_t.
This commit also leverages the ability of osmium::io::Reader to read
from either a file or a buffer when it is called with an
osmium::io::File parameter. By creating the osmium::io::File outside the
process_file() function, we don't need the special class test_parse_t
any more.
> Move file reading functionality from parse_osmium_t to osmdata_t

- docs/flex.md
- flex-config/with-schema.lua
- src/init.lua
This way users can keep using the simpler versions of the function in
more cases.
> Add optional options parameter to define_*_table() functions

- src/CMakeLists.txt
- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/middle-ram.cpp
- src/middle-ram.hpp
- src/middle.hpp
- src/osmdata.cpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/output-gazetteer.hpp
- src/output-multi.cpp
- src/output-multi.hpp
- src/output-null.hpp
- src/output-pgsql.cpp
- src/output-pgsql.hpp
- src/output.hpp
- src/thread-pool.hpp
- tests/test-parse-osmium.cpp
If a function run in the thread pool throws an exception, this exception
was never "collected", it was silently ignored. This commit fixes this
by wrapping the osmium::thread::Pool class in a class of our own that
keeps track of the futures returned by submit() and allows checking
them.
> Fix: Results of tasks run in thread pool were not checked

- docs/flex.md
- docs/lua-lib.md
- flex-config/route-relations.lua
- src/init.lua
- src/middle-pgsql.cpp
- src/osmdata.cpp
- src/osmdata.hpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/output.hpp
- tests/data/test_output_flex_extra.lua
- tests/regression.py
- tests/test-output-flex-extra.cpp
(This is a replacement for #1208.)
The multi-stage processing in the flex output has some problems when
updating data, for instance when relations are deleted after their
member ways use their tags.
This commit reorganizes how the multi-stage processing is done to
address these problems.
1. The way "marking" of objects is done is now different. Instead of
doing this in the process_* Lua functions a new Lua function
"mark_relation_members()" is introduced. This will be called not only
for all new relations but also for deleted relations, or when a relation
changed, for the old relation. This is needed so that we also mark and
then re-create way entries in the database that used to depend on a
parent relations tags, but don't do that any more. This function
must return the way ids that need …
> Fix multistage processing (take 2)

- flex-config/compatible.lua
The specialized route handling is probably not needed any more by
anybody, so we'll disable it by default.
> Disable legacy route handling by default in compatible.lua

- src/CMakeLists.txt
Every documentation I have found of CMake only put .cpp files in this
place. They might have been added for some kind of dependency management
reason, but cmake doesn't even do that, that's done by "make". So I
believe they are not necessary and only clutter up the config.
> Remove hpp files from CMake config as source files

- src/dependency-manager.cpp
- src/dependency-manager.hpp
- src/osmdata.cpp
- tests/data/test_output_flex_stage2_alt.lua
- tests/test-output-flex-stage2.cpp
- tests/test-parse-osmium.cpp
These were needed for old-style multipolygons but are not needed any more.
> Remove legacy calls from dependency manager

- src/input-handler.cpp
- src/input-handler.hpp
Negative ids for OSM objects never worked correctly in all cases and
will not be supported in future versions of osm2pgsql.
See #1097
@pnorman Can you please review?
> Check for negative object ids in input files and output a warning

- src/middle-pgsql.cpp
- src/pgsql.cpp
- src/pgsql.hpp
They are known to have problems with the int arrays.
See #1045
> Disable PostgreSQL JIT and parallel workers in middle

- appveyor.yml
This only raises the version of libpq which osm2pgsql is linked against. Tests are still run against a Postgresql 9.6 installation. I was not able to get a later version running with Postgis.
@janhec Any chance that you could test that the new zip file works for you without deleting libpq.dll? A successfully compiled version can already be found in the [appveyor runs of the branch](https://ci.appveyor.com/project/openstreetmap/osm2pgsql/builds/34316139/job/jwh4ywwt26y03nvt/artifacts).
Fixes #1199.
> appveyor: package libpq 11

- .github/workflows/ci.yml
- .travis.yml
This resurrects the OXS builds on Github Actions. This even has a Postgresql database installed, so that we can now run the full suite of tests. 
For a successful CI run, see https://github.com/lonvia/osm2pgsql/actions/runs/192937489
Fixes #1035.
> CI: move OSX build to Github Actions

- tests/data/test_output_flex_validgeom.lua
- tests/test-output-flex-validgeom.cpp
Instead of reusing the one from the area test.
> Make test-output-flex-validgeom use its own config file

- .github/workflows/ci.yml
- .travis.yml
- CMakeLists.txt
- CONTRIBUTING.md
- README.md
- docs/CMakeLists.txt
- docs/manpage.template
- docs/osm2pgsql.1
- docs/osm2pgsql.md
This makes the man page easier to update and it can be included more
easily into the documentation on the osm2pgsql website.
It uses pandoc which is readily available as packages on all major Linux
distributions to compile the man page into the special format for man
pages.
This will probably not work on Windows, but man pages aren't used there
anyway. Making the man page available on the web should make it easier
for Windows people to access it anyway.
> Keep the man page in markdown format and compile it with pandoc

- src/pgsql.cpp
From the documentation:
"Note that these functions will always return a non-null object pointer,
unless perhaps there is too little memory even to allocate the PGconn
object."
> Add a paranoia check to the database connection

- docs/flex.md
- flex-config/compatible.lua
- flex-config/geometries.lua
- src/flex-table-column.cpp
- src/flex-table-column.hpp
- src/flex-table.cpp
- src/flex-table.hpp
- src/output-flex.cpp
- src/output-flex.hpp
- tests/CMakeLists.txt
- tests/data/test_output_flex_area.lua
- tests/data/test_output_flex_area_3857.lua
- tests/data/test_output_flex_area_4326.lua
- tests/data/test_output_flex_area_mix.lua
- tests/data/test_output_flex_bbox.lua
- tests/data/test_output_flex_invalid_geom.lua
- tests/data/test_output_flex_line.lua
- tests/data/test_output_flex_stage2.lua
- tests/test-output-flex-area.cpp
- tests/test-output-flex-bbox.cpp
- tests/test-output-flex-invalid-geom.cpp
- tests/test-output-flex-line.cpp
- tests/test-output-flex-nogeom.cpp
- tests/test-output-flex-stage2.cpp
The projection set on the command line with -l|--latlong, -m|--merc, or
-E|--proj is now ignored in the flex output. Instead you can set it
individually on all geometry columns using the `projection` option which
either takes an EPSG code or a few commonly understood string values
such as "merc", "latlong", or "WGS84".
This also makes the flex output ignore the --reproject-area option.
The area is now calculated in web mercator by default and you can
change this by setting the `projection` option on the area column.
(This currently only allows setting 4326 and 3857, other projections
will not work. We have to fix this later. This is due to the way
the area is calculated from the WKB geometry.)
The osm2pgsql.srid variable is not set any more in the Lua config.
So there are some breaking …
> Set projection in flex output in column config

- docs/osm2pgsql.md
- src/options.cpp
- tests/regression.py
Optionally allow a PostgreSQL conninfo string in the -d/--database
option instead of just a database name. Similar to what the psql comand
does.
Fixes #1242
> Allow conninfo string in -d/--database option

- docs/bucket-index.md
- docs/osm2pgsql.md
- src/middle-pgsql.cpp
- src/options.cpp
- src/options.hpp
OSM ways have a locality property that we can use to reduce the size of
the index looking up ways a node is in: they are often made up of
sequential node ids. If node N is contained in the way, then there is a
good chance that N+1, N+2, ... are contained in it as well. Thus, if we
group nearby nodes and create an index from node groups to ways, the
index will be significantly smaller. The drawback is that a lookup in
such an index returns false positives, i.e. ways that do not contain the
node of interest. So the smaller index is paid for with a performance
loss for updates.
"Grouping" the ids happens by shifting the id a few bits to the right.
How many exactly can be configured with the
OSM2PGSQL_WAY_NODE_INDEX_ID_SHIFT environment variable.
This commit sets the default shift for the …
> Way node index using shifted node ids

- docs/osm2pgsql.1
- docs/osm2pgsql.md
Add missing options to man page and do some light editing/formatting. This is only a step in bringing the man page more up to date.
In a future PR I want to split the options into several sections, so I haven't taken that into account much when adding the three missing options.
> Extend manpage

- src/osm2pgsql.cpp
- src/output-pgsql.cpp
Other outputs don't use the projection from the command line any more,
so it might be confusing to print that in main.
> Move output of projection used from main to pgsql output

- src/output-flex.cpp
- tests/data/test_output_flex_types.lua
For tables without geometry column, this allows writing
some_table:add_row() in addtion to some_table:add_row({}) or
some_table:add_row{} which makes it a tiny bit more usable.
> Make the Lua add_row() functions 2nd parameter optional

- src/pgsql.cpp
When using the UPDATE notation then the value of the setting comes before the name.
> Fix order of parameters in set_config()

- .travis.yml
- CMakeLists.txt
Remove the parts that set explicit directories for the Postgresql repository and rely on PostgreSQL_ADDITIONAL_VERSIONS instead. This is now set to all version we support.
> clean up cmake code for PostgreSQL detection

- src/db-check.cpp
- src/middle-pgsql.cpp
- src/pgsql.cpp
- tests/regression.py
Also checks in append mode whether the table is there. If not and there
is no --flat-nodes option specified, osm2pgsql will stop with an error.
Fixes #39
> Do not create planet_osm_nodes table if flat nodes are used

- src/output-flex.cpp
- tests/data/test_output_flex_uni.lua
- tests/test-output-flex-uni.cpp
When using a table in the flex output which can take any type of OSM
object, the setting of the type_column name did not work. It always used
the default. The test only checked setting this to the default value, so
it didn't fail.
> Bugfix: Setting of type_column in flex backend did not work

- src/flex-table.cpp
- src/flex-table.hpp
- src/output-flex.cpp
- tests/data/test_output_flex_uni.lua
- tests/test-output-flex-uni.cpp
Osm2pgsql needs to keep track of all objects it writes into the output
tables by their id, so it can remove/update them when the database is
updated. In the flex output there were two options:
* Use tables with nodes, ways, or relations only. Then we can write
the id of those objects "as is" into those tables.
* For area tables, ways can use positive ids and relations negative
ids.
* For tables which can take more than one type of object, we use
two columns, one for the object type ("N", "W", or "R"), one for
the id.
The second option has the drawback that we need to have two columns
which might take more space and also makes some operations more
difficult. Some programs might also need a single unique id column.
So we added a new option here: Just have a single id column and,
similarly …
> Add option to how flex output handles ids in output tables

- src/init.lua
- tests/lua/tests.lua
Adds Lua helper functions has_prefix() and has_suffix(). This is useful
for checks like osm2pgsql.has_prefix(some_tag, 'addr:').
Also add functionality to the osm2pgsql.make_clean_tags_func() function
to also check for suffixes, so '*:sources' will check for all tags
with suffix ':sources'.
> Add starts_with()/ends_with() and suffix check in make_clean_tags_func

- src/middle-pgsql.cpp
When a flat node file is used we don't create the middle nodes table any
more since cd9770b2. So with --dump we got an error when we tried to
delete it.
Fixes #1302
> Bugfix: No error --dump mode when flat node file in use

- src/flex-table.cpp
- src/flex-table.hpp
- src/output-flex.cpp
The flex output could create two id indexes on the same table. This
happened for tables without geometry when 2-stage processing was used.
This fix keeps track of the id indexes on tables and never creates
an index if it already has one.
Fixes #1312
> Fix: Flex output could create two id indexes on the same table

- src/CMakeLists.txt
- src/flex-table.cpp
- src/middle-pgsql.cpp
- src/osm2pgsql.cpp
- src/osmdata.cpp
- src/output-flex.cpp
- src/table.cpp
- src/util.cpp
- src/util.hpp
- tests/test-util.cpp
osm2pgsql prints the duration of several bits of processing. This used
to be just something like "3723s". For large numbers this is
inconvenient. The new output keeps the seconds, but if the duration is
longer than 59 seconds, adds a better readable duration: "3723s (1h
2m 3s)".
> Output durations in more human readable form

- docs/osm2pgsql.1
- docs/osm2pgsql.md
- src/CMakeLists.txt
- src/db-check.cpp
- src/db-copy.cpp
- src/expire-tiles.cpp
- src/expire-tiles.hpp
- src/flex-table.cpp
- src/gazetteer-style.cpp
- src/geom-transform.cpp
- src/input-handler.cpp
- src/logging.cpp
- src/logging.hpp
- src/middle-pgsql.cpp
- src/node-persistent-cache.cpp
- src/node-ram-cache.cpp
- src/options.cpp
- src/options.hpp
- src/osm2pgsql.cpp
- src/osmdata.cpp
- src/output-flex.cpp
- src/output-pgsql.cpp
- src/pgsql.cpp
- src/progress-display.cpp
- src/table.cpp
- src/taginfo.cpp
- src/tagtransform.cpp
This improves the logging output in several ways:
* New logging functions log_debug/info/warn/error(). Almost all
output now uses one of these functions.
* Log messages start with timestamp.
* Log messages of level warn/error are printed in red when
logging to console.
* New command line option: --log-level to set log level. Default
is "info". The option -v, --verbose does the same as
--log-level=debug.
* New option --log-progress=true/false/auto. The default is `auto`
which enables progress logging on the console and disables it
when stderr has been redirected to a file.
* Extra functions to log SQL commands/SQL COPY data. These can
be activated by command line options --log-sql and --log-sql-data,
respectively, instead of the compile time setting. Output is
printed in blue when logging …
> Improved logging output with timestamps, level settings and more

- src/flex-table.cpp
This code was basically copied over from the pgsql output. It is a
half-measure that can detect some needed changes in your database tables
when you change the config after import. But this was never tested
properly and what is implemented is not enough to make this a useful
feature. So lets get rid of it.
> Flex output: Remove code that alters table in append mode

- src/table.cpp
This code is a half-measure that can detect some needed changes in your
database tables when you change the config after import. But this was
never tested properly and what is implemented is not enough to make this
a useful feature.
Fixes #1329
> Pgsql output: Remove code that alters table in append mode

- src/output-flex.cpp
Without tables defined there isn't anything to do. So this means
something is wrong with your configuration. Possibly you are using a Lua
transform config for the pgsql output instead of a flex config.
Fixes #1332
> Check that you have any output tables defined in the flex config

- README.md
- docs/osm2pgsql.1
- docs/osm2pgsql.md
Removed the somewhat outdated section on running osm2pgsql from the
README and refer to the manual instead.
> Various cleanups in man page and README

- src/middle-pgsql.cpp
We are not enabling this by default at the moment, this would only
confuse users.
> Log missing bucket index not as warning but as debug message

- src/logging.hpp
Always use color when writing to console and no color otherwise.
> Decouple color output from log settings

- src/osm2pgsql.cpp
Only works on Linux. On other systems it just does nothing.
> Print memory usage at the end of running osm2pgsql

- README.md
- cmake/FindLua.cmake
Hey,
I was building osm2pgsql in an Alpine container and due to Alpine's popularity I figured it couldn't hurt to add Alpine build instructions while I'm at it.
I may have included a bit too much detail, but I was hoping it could save someone some time of troubleshooting why CMake is only finding part of the Lua "dependencies" (no unversioned symlink to `/usr/lib/lua5.3/liblua-5.3.{so|a}` under `/usr/lib`).
Thanks
> Simplify build on Alpine

- CMakeLists.txt
- docs/CMakeLists.txt
@joto suggested a different variant for #1413, where we simply don't add the install target when osm2pgsql is being included as a subproject. I think that's more elegant.
> Disable install targets when osm2pgsql is inside a subdir

- scripts/osm2pgsql-replication
Setups that process expiry data need to do that after each run of osm2pgsql. The new option provides the means to insert additional operations via a script when osm2pgsql is run multiple times.
@tomhughes would this option be sufficient for the render servers to run their expiry? When you use the `--diff-file` option, then the update script explicitly leaves the diff file around, so you should be able to run the custom expiry on it.
> Add a post-processing option for the update script

- src/middle-pgsql.cpp
- src/table.cpp
- tests/test-middle.cpp
PostgreSQL handles plain tables name differently than it handles quoted
names. So `CREATE TABLE DEU_nodes;` is different than `CREATE TABLE
"DEU_nodes";`. In the first case the name is canonilcalized to lower
case. This quotes names in all places so we get exactly the name we ask
for.
Fixes #1420
> Use double quote on all table names etc. in middle

- src/expire-tiles.hpp
- src/output-flex.cpp
I create mode we never need to create an expire list. But as a side
effect of the two-stage processing we created such a list which costs a
lot of time and RAM. This disables this which speeds up an import
considerably.
See #1436
> Disable expire in create mode

- src/progress-display.cpp
The lower number was not enough in some cases.
> Use more spaces (90 instead of 78) to clear progress display

- src/node-ram-cache.cpp
Reading from uninitialized memory is undefined behavior, and triggers valgrind memory error messages as per #1442.
Fixes #1442
(supersedes #1443)
> Avoid reading from empty sparseBlock

- src/middle-pgsql.cpp
Indexes are always created in the same schema as the table.
Fixes #1447
> Bug fix: Remove schema name from CREATE INDEX

- CMakeLists.txt
This only makes a difference when osm2pgsql is used as a subproject (i.e. in Nominatim). PROJECT_SOURCE_DIR refers to the subproject while CMAKE_SOURCE_DIR refers to the overall one.
> cmake: use PROJECT_SOURCE_DIR when getting git version

- src/node-persistent-cache.cpp
- src/node-persistent-cache.hpp
Storing a pointer to a string that might go away isn't a good idea.
Using std::string instead. Also slightly improved logging.
> Remove possible dangling pointer from node_persistent_cache

- src/node-persistent-cache.cpp
This is already set from cmake/FindOsmium.cmake .
Superseeds PR #1452
> Remove unnecessary define (already set in CMake config)

- src/output-pgsql.cpp
- src/tagtransform-c.cpp
- src/tagtransform-c.hpp
- src/tagtransform-lua.cpp
- src/tagtransform-lua.hpp
- src/tagtransform.hpp
After the removal of the multi output there are some functions which don't use all their parameters any more. These three commits clean up those functions and some related code.
> Cleanup some code after removal of multi output

- .clang-tidy
hicpp-special-member-functions is an alias for
cppcoreguidelines-special-member-functions, so we need both in the
config file.
> Disable more clang-tidy warnings

- src/expire-tiles.cpp
- src/expire-tiles.hpp
- src/output-flex.cpp
- src/output-pgsql.cpp
A `std::string` reference contains more information, specifically the length of the string which is lost when using `c_str()`. So it is better to keep working with a std::string reference where possible.
> Directly use std::string reference instead of calling c_str()

- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/middle-ram.cpp
- src/middle-ram.hpp
- src/middle.hpp
- src/output-flex.cpp
- src/output-gazetteer.cpp
- src/output-pgsql.cpp
- tests/test-middle.cpp
It should not be the job of the middle to extract the roles from the
relation it retrieves. This removes the role list parameter from
rel_way_members_get() function.
But a quirk of the pgsql output is that the roles of all available
member ways of a relation are available in the Lua
"filter_tags_relation_member" callback function. This is probably not
used very often (if at all), but we need to keep that functionality
available for backwards compatibility.
So this adds a new function get_rolelist() to the pgsql output which
creates this role list.
> Remove role list parameter from rel_way_members_get()

- flex-config/generic.lua
We "split" up the relations based on the type onto different tables here
and there is no case where the type tag will be useful in the database
and everything without type is dropped anyway.
Fixes #1441
> Slight improvement of generic.lua config

- .github/workflows/ci.yml
Otherwise we get the default "RelWithDebInfo".
> Explicitly set build type to "Debug" in some CI builds

- src/wkb.hpp
These commits refactor some of the WKB code step by step to
* make it cleaner
* pull generation of points geometries out of the `ewkb::writer_t` class to make its use faster and simpler (we'll use this in the upcoming new pgsql middle)
* fix potential buffer overflow in `ewkb::parser_t`
This leaves the WKB code a bit cleaner, there is still the `get_area()` function etc. to clean up which doesn't really belong in the `parser_t` class and some of the code should probably be moved into a `.cpp` file, but I leave that for another day.
> Refactoring of WKB code

- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/middle-ram.cpp
- src/middle-ram.hpp
- src/middle.hpp
- src/output-flex.cpp
- src/output-gazetteer.cpp
- src/output-pgsql.cpp
- tests/test-middle.cpp
In the future we want the middle to be able to return not only way
members of relations but any type of member. This renames the
function rel_way_members_get() to rel_members_get() and adds an extra
parameter that specifies which types of members we are interested
in. The ram middle already supports accessing non-way members, but
the pgsql middle still only supports way members.
> Refactor middle interface to get relation members

- .github/workflows/ci.yml
- README.md
Up from 9.3. We need to go to at least 9.4 because we will need the
JSONB datatype. 9.5 is used by Ubuntu 16.04. 9.6 is the oldest
version currently still supported by the PostgreSQL project.
> Document PostgreSQL 9.5 as oldest supported version.

- src/output-pgsql.cpp
- src/output-pgsql.hpp
To be consistent with the rest of the codes, class members should have prefix `m_`.
> Fix member names of pgsql output

- src/expire-tiles.cpp
- src/expire-tiles.hpp
- src/output-pgsql.cpp
- src/table.cpp
- src/table.hpp
Removes wkb_reader helper class and expire_tiles::from_db() function.
The wkb_reader class does nothing more than iterate over the results of
a database query but that can be done in an easier way
> Simplify code around expiry

- src/ordered-index.cpp
- src/ordered-index.hpp
So we don't have to recalculate.
If we want to ask how much memory the index currently needs to keep
it under some limit, we will call capacity() quite often.
> Keep track of capacity of an ordered index

- src/middle-ram.cpp
The delta encoded ids are, of course, sometimes positive, sometimes
negative. The zigzag encoding makes sure this is efficiently encoded.
> Use zigzag encoding for way node lists

- flex-config/attributes.lua
- flex-config/data-types.lua
- flex-config/generic.lua
- flex-config/geometries.lua
- flex-config/route-relations.lua
- flex-config/simple.lua
- flex-config/unitable.lua
- flex-config/with-schema.lua
- tests/CMakeLists.txt
* Test more of the flex config files
* Use jsonb instead of hstore in most flex config files
> Flex config

- tests/common-pg.hpp
- tests/test-db-copy-mgr.cpp
- tests/test-db-copy-thread.cpp
- tests/test-options-projection.cpp
- tests/test-output-gazetteer.cpp
- tests/test-output-pgsql-int4.cpp
- tests/test-output-pgsql-z_order.cpp
One less dependency and UB sanitizer warns that boost::lexical_cast has
undefined behaviour.
Fixes #1028
> Remove use of boost::lexical_cast

- flex-config/attributes.lua
- flex-config/data-types.lua
- flex-config/route-relations.lua
- src/flex-table-column.cpp
- src/flex-table-column.hpp
- src/flex-table.cpp
- src/flex-table.hpp
- src/lua-utils.cpp
- src/lua-utils.hpp
- src/output-flex.cpp
- tests/data/test_output_flex_types.lua
The "type" field in a flex output column definition really does two
things:
1. It defines the way Lua values are transformed into PostgreSQL
values.
2. It defines which PostgreSQL type should be used in a the CREATE
TABLE statement for a particular column.
This commit adds a new "sql_type" field which takes over the second
meaning. If it is not specified, the default is still defined by
the "type" field. The default for the type field is "text".
The result is that in most cases you use only the "type" field as before
and it does the right thing. If you need a special SQL type, use the
"sql_type" field instead or in addition to the "type" field.
Note that this is a breaking change, but still allowed because the flex
output is still marked experimental.
> Add sql_type column field in flex output

- src/flex-table.cpp
Tables created with the flex output that were marked `cluster: "no"`
were created as unlogged tables. This should only be done for tables
which will be replaced by their clustered copy later on.
See #27
> Bugfix: Do not create table as unlogged if it is not clustered

- src/output-flex.cpp
The directory where the Lua config file was read from is now available
in the osm2pgsql.config_dir variable. This is useful, for instance, when
we want to include other files into our config file.
> Expose config dir in osm2pgsql.config_dir Lua var in flex output

- src/input.cpp
- src/input.hpp
- tests/test-check-input.cpp
Two versions of the same object are not allowed in the input data. This
can, for instance, happen when reading un-simplified change files.
> Fix input data check: Two versions of same object are not allowed

- src/ordered-index.cpp
- src/ordered-index.hpp
When importing a planet file or a huge extract, something with more than
about 1 billion nodes, the new RAM node location could overflow a 32bit
"offset" value which meant that the node locations would not be found
again. The result were missing features, because osm2pgsql just ignores
features with geometries that can not be built due to missing node
locations.
This fix has two parts: First, it fixes the typo which made the max
block size too large. This typo lead to a doubling of the max block size
which directly lead to the bug. The other fix is to check the "offset"
value and, if it becomes too large, start a new block. This probably
isn't necessary for "normal" OSM data which should usually work with the
new max block size, but it provides a safety net in case some the block
size …
> Bugfix: Nodes not stored in node location store correctly

- src/pgsql-helper.cpp
It is not clear how exactly the volatility classification works in
trigger functions, so it is better to be on the safe side here and not
declare the function IMMUTABLE (which makes it the default VOLATILE
instead).
https://www.postgresql.org/docs/current/xfunc-volatility.html
> Remove IMMUTABLE volatility classification from trigger function

- scripts/osm2pgsql-replication
Older versions don't have .fromisoformat() function
> support older versions of python with osm2pgsql-replication

- docs/osm2pgsql-replication.1
- scripts/osm2pgsql-replication
Regular osm2pgsql takes -p as an alias for --prefix, so make them match
> Add -p (for --prefix) argument for osm2pgsql-replication too

- CONTRIBUTING.md
- docs/osm2pgsql-replication.1
Update `CONTRIBUTING.md` with how to generate the `osm2pgsql-replication` man page, to ensure it's always the same the next time someone else does a PR. 😉
I also ran argparse-manpage to regenerate the `osm2pgsql-replication.1` doc.
I do not know how to get rid of the `AUTHORS` bit from the manpage.
> Update docs on making `osm2pgsql-replication` man page

- docs/osm2pgsql-replication.1
- scripts/osm2pgsql-replication
This patch adds an `info` command which prints readable summary of the state of replication:
```
$ osm2pgsql-replication info -U osm -d gis
2021-08-04 14:12:28 [INFO]: Using replication service 'https://download.geofabrik.de/europe-updates/'. Current sequence 3052 (2021-08-03T20:21:39Z).
2021-08-04 14:12:28 [INFO]: Server is at sequence 3052 (2021-08-03T20:21:39Z)
2021-08-04 14:12:28 [INFO]: Server's most recent data is 17 hour(s) 50 minutes(s) old
2021-08-04 14:12:28 [INFO]: Database is up to date with server
2021-08-04 14:12:28 [INFO]: Database's most recent data is 17 hour(s) 50 minutes(s) old
```
with the `--json` option, the output is in JSON format, which is useful for writing scripts to detect if the replication has stopped, or to graph how far behind the server is:
`$ …
> add a 'status' command which prints the lag (& in JSON)

- src/middle-pgsql.cpp
The message "Done postprocessing on table '{}' in {}" was logged twice
when `--drop` is used. This changes one of the log messages to the
more specific "Table '{}' dropped in {}".
> Fix confusing log message

- src/osm2pgsql.cpp
- src/osmdata.cpp
- src/output-flex.cpp
- src/output-gazetteer.cpp
- src/output-pgsql.cpp
- src/output.cpp
- src/output.hpp
The outputs have a shared pointer to the middle_query_t to access the data held by the middle. This in turn holds pointers to potentially large datastructures and the flat node file. We need to release those pointers after we don't need them any more so that if and when the middle doesn't need those data structures any more they get cleaned up.
In effect this releases the memory used for the cache and flat node store earlier.
Fixes #1563
The second commit cleans up the code a bit using a proper accessor in `output_t` to access the `mid` pointer.
> Clean up pointers to middle_query_t in outputs to release memory

- .github/workflows/ci.yml
- README.md
These images are no longer available on the Github CI. This means that we won't be testing gcc < 7 and clang < 8 anymore, so add a note to that end in the prerequisites section.
> remove CI runs on Ubuntu 16 images

- .github/workflows/ci.yml
- remove LUA_VERSION env for macos build, https://github.com/Homebrew/homebrew-core/pull/82233 (it builds/runs fine with lua 5.4?)
- remove `test-wrapper` input arg (use the default value as it already did)
- fix the job ref for `ubuntu20-pg13-gcc10-release`
> ci: improve the workflow

- .github/actions/win-build/action.yml
- .github/actions/win-cmake/action.yml
- .github/actions/win-getopt/action.yml
- .github/actions/win-install/action.yml
- .github/actions/win-test/action.yml
- .github/workflows/ci.yml
So far this only compiles osm2pgsql on Windows. Only tests without database are run. We can later add functionality to export the compiled result as artefact, test that etc.
> Github action: Add Windows CI build

- src/logging.cpp
- src/logging.hpp
- src/progress-display.cpp
When there is an active progress display, log messages show up after the progress display instead of the next line. This adds the necessary newline character to fix that.
> Fix logging while progress display is on

- CMakeLists.txt
Otherwise some versions of CMake will fail with error:
try_compile() works only for enabled languages.
Fixes #1600
> CMake config: Also set C as additional language in project()

- src/osmdata.cpp
- tests/regression.py
Reintroduce fix from 8763ce951bddee2af553fab6ce4e1f4e79eeaaa0 which got
moved to the wrong place in some refactoring.
> There is a hard restriction in the pgsql middle tables, where
> relation members are indexed using a smallint. To remain
> consistent, drop all relations which exceed this size.
Fixes #1607
> Again: ignore relations with more than 32k members

- scripts/osm2pgsql-replication
Print a helpful error message with instructions what to do when loading the psycopg or osmium libraries fails.
The second commit enables the script to work with psycopg>=3.0. (It will still prompt you to install psycopg2, just so that people who are on stable distributions are not confused.)
> Replication script: better checking for external libraries

- .github/workflows/test-install.yml
- CMakeLists.txt
This also adds a new Github actions workflow which tests the
installation of osm2pgsql and osm2pgsql-replication.
> Install osm2pgsql-replication script/man page on make install

- .github/workflows/ci.yml
So we see if there is a difference in the built results if one fails.
> Github action: Disable fail-fast for Windows matrix build

- tests/common-pg.hpp
- tests/test-output-flex-way-change.cpp
- tests/test-output-flex-way-del.cpp
- tests/test-output-gazetteer.cpp
Due to unsigned integer underflow.
> Fix undefined behaviour in test

- src/reprojection-generic-proj6.cpp
- tests/test-reprojection.cpp
The test was never run so we did not notice that the projection did not
work correctly.
Code modelled after https://proj.org/development/migration.html .
> Fix reprojection when using Proj version 6 and above

- tests/CMakeLists.txt
- tests/data/test_output_flex_area_25832_25832.lua
- tests/data/test_output_flex_area_25832_3857.lua
- tests/data/test_output_flex_area_25832_4326.lua
- tests/data/test_output_flex_area_3857_25832.lua
- tests/data/test_output_flex_area_3857_3857.lua
- tests/data/test_output_flex_area_3857_4326.lua
- tests/data/test_output_flex_area_4326_25832.lua
- tests/data/test_output_flex_area_4326_3857.lua
- tests/data/test_output_flex_area_4326_4326.lua
- tests/data/test_output_flex_area_mix.lua
- tests/data/test_output_flex_multigeom_geometry.lua
- tests/data/test_output_flex_multigeom_geometry_split.lua
- tests/data/test_output_flex_multigeom_multipolygon.lua
- tests/data/test_output_flex_multigeom_multipolygon_split.lua
- tests/data/test_output_flex_multigeom_polygon.lua
This is possible because we added the ?osm2pgsql.config_dir` variable a while back.
> Simplify tests that include Lua files

- src/node-persistent-cache.cpp
- src/taginfo.cpp
`std::strerror()` is not thread-safe, so it is best avoided. Also the output of the error messages will be more uniform this way.
There is one other case where we use `strerror()` (in [expire-tiles.cpp](https://github.com/openstreetmap/osm2pgsql/blob/master/src/expire-tiles.cpp#L44)) but that's only a warning, so we can't replace it by `system_error`, although maybe it shouldn't be a warning? Leaving that for later, the expire code needs some work anyway.
> Use std::system_error instead of runtime_error/strerror

- CMakeLists.txt
- cmake/config.h.in
- src/util.cpp
Now that we are using C++17, we can use `__has_include()`
> Simplify termios.h check

- src/output-flex.cpp
This allows the filename that will usually be concatenated to the
directory name in the Lua code to be written without the trailing
separator (usually '/'). This will make it work if there is no directory
used in the -S option.
> Add directory separator to end of config_dir

- tests/test-middle.cpp
Compiling with UB sanitizer shows an overflow in the fmt library triggered by our code:
fmt/format-inl.h:1984:56: runtime error: unsigned integer overflow: 100000000 * 9876243 cannot be represented in type 'unsigned int'
This change fixes that.
And actually tests that locations read back are the same as original
ones.
> Fix overflow in fmt lib in middle test

- src/output-flex.cpp
- src/output-flex.hpp
This refactors the somewhat difficult to understand code in the flex output that handles getting and caching ways and their nodes, and relations and their members. The changes are in several steps, each in their own commit.
> Refactor of way/relation "cache" in flex output

- flex-config/bbox.lua
- src/middle-pgsql.cpp
- src/output-flex.cpp
- src/output-flex.hpp
The `get_bbox()` function now works for relations, too. Only node and way members are taken into account. The data is cached properly so that it is only requested from the database once even if `get_bbox()` and/or `add_row()` are called multiple times.
Part of this change is that we'll get the location of all nodes members of relations. This is new, we used to only get the way members and the locations in those ways. Getting all the node members keeps the code simpler, but has some overhead. It should be fairly small though compared to getting all the way members of the multipolygon and boundary relations which make up the bulk of what we are using.
> Get bbox relation

- src/tagtransform-lua.cpp
- src/tagtransform-lua.hpp
- src/tagtransform.cpp
This fixes a memory leak of a Lua context. In the process quite some refactoring needed to be done and some more checks on the data osm2pgsql receives from Lua scripts. See the individual commits.
> Fix memory leak in Lua-related code

- src/flex-table.cpp
- src/flex-table.hpp
- src/output-flex.cpp
For these tables a (temporary) index is created but an ANALYZE might
help to speed up things.
> Call ANALYZE on tables with ids when two-stage processing is used

- CMakeLists.txt
- CONTRIBUTING.md
- tests/run-behave.in
If run with `-p` as first option it will wrap the call to `behave` in a
call to `pg_virtualenv` for your convenience. All other command line
parameters of `run-behave` will be passed through to behave.
> Add run-behave script for convenience

- flex-config/simple.lua
- src/output-flex.cpp
- tests/bdd/flex/extra-attributes.feature
This is either "node", "way", or "relation". Sometimes useful in scripts.
> Add "type" attribute to Lua "object" callback parameter

- src/geom-from-osm.cpp
- src/geom-from-osm.hpp
All functions are now available in two variants: one taking a pointer to
an existing geometry as output parameter, and the second which returns a
new geometry instead. The first is faster if the geometry object already
exists, the second is more convenient in places where it doesn't.
> All geometry creation functions are now available in two variants

- tests/common-buffer.hpp
- tests/test-geom-lines.cpp
It doesn't matter which function we use as long as we don't use the
return value from them. So the existing cases aren't a problem, but
this way this will not happen in the future where it might be a
problem.
> Add assertions so we are not using the wrong func by accident

- src/geom-functions.cpp
- src/geom-functions.hpp
- tests/test-geom-linestrings.cpp
For linestrings only. For polygons we'll need something else.
> Add geom::simplify() function

- src/output-flex.cpp
- src/output-gazetteer.cpp
- src/output-pgsql.cpp
When you are feeding ways without nodes to osm2pgsql, which should never
happen in normal operation, osm2pgsql will break without this check.
> way.is_closed() should only be called when there are way nodes

- src/geom-functions.cpp
- tests/test-geom-linestrings.cpp
The simplification function can generate a linestring with a single
point in it, which wouldn't be a line any more. Return a null geometry
in that case.
> Ensure that the result of geom::simplify() is a valid geom or null

- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/middle-ram.cpp
- src/middle-ram.hpp
- src/middle.hpp
- tests/test-middle.cpp
Before we had only a function to retrieve a list of locations from a
list of nodes which is inconvenient if you only need a single location.
The new function is needed in the context of retrieving locations for
member nodes of relations.
There are probably ways to improve on this:
* We are using the get_node_list prepared statement to get the single
id when a simpler prepared statement would do. But then we'd need
another prepared statement.
* When using this it might be possible to first assemble a list of
several ids and get them all in one go. But its more difficult to
write code like this and there aren't that many relations around
that have lots of node members, so we'll leave it at that and
optimize this later if needed.
> Add get_node_location() function to middle

- src/db-copy-mgr.hpp
- tests/test-db-copy-mgr.cpp
This way we can start to write a COPY line and, while writing it, change
our mind and cancel that line. This is useful if we detect errors only
while writing something out.
> Add rollback function to COPY manager

- src/geom.hpp
- tests/test-geom-linestrings.cpp
- tests/test-geom-multipoints.cpp
* Use extra functions for each type to be moved into `geometry_t` to avoid a template matching in the wrong places.
* It turns out we actually need a modifiable iterator so that we can move members out of the collection.
> Fiddling with the geometry_t type

- src/geom-functions.cpp
- src/geom-functions.hpp
- src/geom.hpp
- src/output-flex.cpp
- src/output-pgsql.cpp
Also removes an unneccessary cast from int to uint32_t and back.
> Refactor split_multi() so it doesn't copy

- src/gazetteer-style.cpp
- tests/test-output-gazetteer.cpp
std::atoi only parses a string to the first non-digit with the result that fractions like 2.5 end up being parsed despite not being a correct integer. Use strtol instead to check that the whole string gets parsed.
See https://github.com/osm-search/Nominatim/discussions/2787 for the issue.
> gazetteer: parse full admin_level string only

- flex-config/new-insert-syntax.lua
- src/CMakeLists.txt
- src/flex-lua-geom.cpp
- src/flex-lua-geom.hpp
- src/flex-table-column.cpp
- src/flex-table-column.hpp
- src/flex-table.cpp
- src/flex-table.hpp
- src/init.lua
- src/middle-ram.cpp
- src/output-flex.cpp
- src/output-flex.hpp
- tests/bdd/flex/geometry-collection.feature
- tests/bdd/flex/geometry-function-area.feature
- tests/bdd/flex/geometry-iteration.feature
- tests/bdd/flex/geometry-null.feature
- tests/bdd/flex/geometry-processing.feature
- tests/bdd/flex/invalid-lua.feature
- tests/lua/tests.lua
This is the future of geometry processing in Lua. Geometries are not something happening magically behind the scenes as before, but they are (mostly) normal objects that can be manipulated in Lua. There are several functions to create those geometry objects from the OSM objects:
* as_point() (for nodes)
* as_linestring() (for ways)
* as_polygon() (for ways)
* as_multilinestring() (for relations)
* as_multipolygon() (for relations)
* as_geometrycollection() (for relations)
Geometries can be manipulated with the following functions (all based on their equivalents in PostGIS):
* area() (for polygons)
* centroid() (for polygons)
* geometries() for iterating over (multi)geometries
* geometry_n() return the nth geometry from a (multi)geometry.
* geometry_type() returns type as string ('POINT', …
> Add geometry functions in Lua / new insert syntax

- src/output-flex.cpp
- tests/bdd/flex/geometry-linestring.feature
> Wrap geometries in multi if needed and check geom type compatibility

- .github/workflows/ci.yml
Homebrew started distributing versioned postgresql packages with a non-standard directory layout that breaks cmake's scripts for finding postgresql. Work around the issue by adding symlink hacks.
See https://github.com/actions/runner-images/issues/6176 for more information.
> Actions: work around broken macos postgresql

- CMakeLists.txt
- scripts/osm2pgsql-replication
This PR collects some smaller improvements to the osm2pgsql-replication script to harden it against potential security issues:
* Use psycopg2's SQL module for correct quoting of PostgreSQL identifiers like table names. This includes fixing one spot where there was a SQL code injection possible via the `--prefix` parameter. Note that the threat level for the injection is low because the attacker would still need credentials for the database.
* When installing the script with `make install`, the default osm2pgsql binary will no longer be searched via PATH. Instead a hard-coded path to the installed osm2pgsql is used.
* Document that the script accepts connection parameters via libpq environment parameters and point to pgpass files for handing in passwords. Also fixes the script to work when …
> Improvements to osm2pgsql-replication script

- src/options.cpp
- src/output-flex.cpp
- src/pgsql.cpp
- src/pgsql.hpp
- src/table.cpp
We already consistently quote all identifier used in SQL strings in the code to avoid SQL injection issues. The quoting works on the assumption that there are no double quotes in the string itself. The flex output already checked all user-supplied strings for conformance.
This PR adds the same check to the prefix and schema command-line parameters which are used as SQL identifiers and for the column names and types from the pgsql style file.
> Check more user-supplied strings used as SQL identifier

- tests/test-geom-polygons.cpp
That test doesn't do what it is supposed to do, test "polygon geometry with inner". Obviously just a copy from the test above. But tests covering polygons with inner rings come later, so we can just remove this.
> Remove a duplicated tests

- src/geom-from-osm.cpp
- tests/bdd/flex/geometry-collection.feature
- tests/test-geom-collections.cpp
If a geometry collection is created from a relation, any way member will normally end up as linestring relation. But if there is only a single point in the resulting linestring (because the way only contained a single node or multiple nodes with the same position), that linestring would be invalid. In this case create a point geometry instead.
> Fix: Create point geometry from collection with single-node way

- src/middle-pgsql.cpp
- src/output-flex.cpp
- src/pgsql.hpp
- tests/bdd/flex/geometry-collection.feature
- tests/test-middle.cpp
Relation members were not returned in order from rel_members_get() when using the pgsql middle.
This also fixes an anomaly where node members where returned as a WayNodeList instead of as normal nodes.
> Bugfix: Return relation members in order from pgsql middle

- src/geom-from-osm.cpp
- tests/bdd/flex/geometry-collection.feature
- tests/test-geom-collections.cpp
This reverts commit 748fc0ab5bf4d9b459f2cbab54f4523c7b09624a.
Turns out this wasn't such a good idea, see #1767 for details.
The gist of it is that we always return NULL geometry when there are problems and so this should be the case here also for consistency.
> Revert "Fix: Create point geometry from collection with single-node way"

- flex-config/unitable.lua
Also switch to geometrycollection for saving relations. This way all non-empty relations are captured.
> Switch unitable example to insert()

- src/geom-from-osm.cpp
- src/geom-from-osm.hpp
They are now always called "buffer" in .hpp and .cpp file. Document the fact that the input buffer can contain other object types which will be ignored.
> Consistent naming of buffer paramater in create_*() calls

- src/geom-functions.cpp
- tests/test-geom-collections.cpp
Implement the `area()` function also for geometry collections and switch from our own implementation to using the one from boost::geometry.
> Area function for collection and switch to using boost::geometry

- flex-config/attributes.lua
- flex-config/data-types.lua
- flex-config/places.lua
- flex-config/with-schema.lua
Modernize some of the flex config examples. See individual commits.
> Modernize flex config

- src/geom-from-osm.cpp
- src/geom-functions.cpp
- src/geom.cpp
- src/geom.hpp
- tests/test-geom-linestrings.cpp
- tests/test-geom-multilinestrings.cpp
We already have an implementation for linestring, which is slightly improved in this commit. Simplification for anything other than (multi)linestring is not supported.
In the first commit there is also a refactor of the `fill_point_list()` function which makes the code more readable and consistent.
> Add implementation of simplify function for multilinestrings

- src/geom-from-osm.cpp
- tests/test-geom-multilinestrings.cpp
- tests/test-geom-multipoints.cpp
Handle the case specially where there is a only a single point/linestring in a multipoint/multilinestring geometry due to missing input data.
> Fix: Handle special single-geom case for multipoint/linestring

- flex-config/attributes.lua
> Add note about use of timestamp/timestamptz to example

- src/output-flex.cpp
The light userdata doesn't have an associated metatable which limits its usefulness.
> Use "real" userdata, not light userdata for table reference

- src/flex-table.cpp
- src/flex-table.hpp
Only very simple accessor-type functions should be defined directly in .hpp file.
> Move some more complex functions from .hpp into .cpp file

- src/geom-from-osm.cpp
- src/geom.hpp
Without it the std::move() does not work, but a copy is needed.
> Add non-const accessor to multigeometry members for performance

- .github/workflows/ci.yml
- .github/workflows/test-install.yml
Avoids a warning about outdated nodejs 12.
> Github actions: update versions of external action scripts

- src/flex-table-column.cpp
- src/output-flex.cpp
- src/util.hpp
- tests/test-util.cpp
This finds an item by name in some kind of container. The only requirement on the item is that it has a `name()` method.
We will need this function in more places in the future, so makes sense to factor this out.
> Add find_by_name() utility function

- src/osmdata.cpp
Worker handling for parallel processing of pending items has quite a large overhead of around 1s. This is not much of a problem when handling larger update files. It is noticable in the tests where we process update batches with one or two items only.
This avoids parallel processing entirely when only a few items are involved. I've set an completely arbitrary limit of 100 items.
> Avoid parallel execution for pending items when there are only a few of them

- src/pgsql.cpp
This allows us to use exec_prepared() with commands such as DELETE which set status to PGRES_COMMAND_OK. Before the change only SELECT commands were supported with set the status to PGRES_TUPLES_OK. Both indicate a successful completion of the command.
> Allow PGRES_COMMAND_OK as well as PGRES_TUPLES_OK status

- src/flex-table.hpp
- src/middle-pgsql.hpp
- src/table.hpp
- src/thread-pool.cpp
- src/thread-pool.hpp
- src/util.cpp
- src/util.hpp
We can use the timer in more places if we have better resolution. For places where we don't need the resolution it doesn't matter because it will just get rounded. While we are at it we also use microseconds in the thread_pool code so that we use the same unit everywhere.
The timer is restartable now, by repeatedly calling start/stop() we can add up the times.
Also we are trying, as much as possible, to keep to the time types supplied by chrono. This gives us automatic correct time output with the fmt library which knows about those types. And it should make time conversions easier.
> Make timer_t use microseconds and make it restartable

- src/output-flex.cpp
- src/output-flex.hpp
- src/output-gazetteer.cpp
- src/output-gazetteer.hpp
- src/output-null.cpp
- src/output-null.hpp
- src/output-pgsql.cpp
- src/output-pgsql.hpp
- src/output.cpp
- src/output.hpp
This code was a bit of a mess. Now the implementations of the derived classes are more similar and a bit simpler.
We'll use the "rule of five" in `output_t` and derived classes, so copy and move constructors and operators as well as (virtual) destructor are all spelled out.
As far as possible constructors etc. are made private/protected. We only ever create those classes though the  `create_output()` function or the `clone()` function. But we are using `std::make_shared()` internally so some constructors need to be public because, while conceptually the objects are created from inside the class itself, it is the `make_shared` function that actually does this and it can only use the public interface.
> Cleanup output construction

- src/options.cpp
- tests/test-options-database.cpp
Doesn't hurt and might prevent some problems, because osm2pgsql is always dealing with UTF8 data.
Note that, just as with the fallback_application_name, this setting isn't set in all cases, but we don't want to meddle with the user settings too much to not break the connection info.
> Force database client encoding to UTF8

- src/output-flex.cpp
- src/output-flex.hpp
- src/output-gazetteer.hpp
- src/output-pgsql.cpp
- src/output-pgsql.hpp
- src/output.cpp
The output derived classes can create the copy_thread themselves. They just need the options which they have anyway.
> Remove copy_thread parameter from output constructors

- src/json-writer.hpp
- tests/test-json-writer.cpp
JSON doesn't allow pseudo-numbers such as NaN and Inf. They are written out as "null" instead.
> Handle non-normal floating point numbers in JSON writer

- src/flex-lua-geom.cpp
- src/geom-functions.cpp
- src/node-locations.cpp
- src/progress-display.cpp
- src/tagtransform-lua.cpp
- src/util.hpp
- src/wkb.cpp
- tests/test-parse-osmium.cpp
In places where MSVC gives us warnings.
> Do some explicit number conversions

- flex-config/indexes.lua
- src/CMakeLists.txt
- src/flex-index.cpp
- src/flex-index.hpp
- src/flex-table.cpp
- src/flex-table.hpp
- src/lua-utils.cpp
- src/output-flex.cpp
- src/output-flex.hpp
- tests/CMakeLists.txt
- tests/bdd/environment.py
- tests/bdd/flex/lua-index-definitions.feature
The table definitions have a new (optional) field called "indexes" now which takes a list of index definitions. If the field is not there, we fall back to what we did before, a GIST index on the only/first geometry column of table is created. To disable indexes, set to an empty array.
See the flex-config/indexes.lua Lua config for some usage examples.
See #1780
> Flex: Add support for configuring table indexes in the Lua config

- src/flex-lua-index.cpp
- src/pgsql-capabilities-int.hpp
- src/pgsql-capabilities.cpp
- tests/CMakeLists.txt
- tests/test-flex-indexes.cpp
Add testing capability to pgsql capability code and use it to test flex index setup.
The second commit  refactors the flex_lua_setup_index() code to avoid having to count numbers of values on the Lua stack.
> Test flex indexes

- src/db-copy.cpp
- src/middle-pgsql.cpp
- src/pgsql-capabilities.cpp
- src/pgsql-helper.cpp
- src/pgsql.cpp
- src/pgsql.hpp
- tests/common-pg.hpp
- tests/test-db-copy-mgr.cpp
- tests/test-output-gazetteer.cpp
- tests/test-pgsql.cpp
It was always confusing to me that there were two functions `query()` and `exec()` to send SQL commands to the server and which one to use when. This PR cleans that up and leaves only `exec()`. Some other smaller cleanups along the way, see individual commits.
> Pgsql cleanup again

- src/flex-table.cpp
- src/osmdata.cpp
- src/output-flex.cpp
These are not needed, because the `log_*()` functions already do the formatting for us.
> Remove extra _format() in log statements

- CMakeLists.txt
Use of rapidjson was already removed in
059f5d551341cd0cb3e701347f1cd71dbad36af5, but the CMake config still referred to it.
> Remove remnants of rapidjson in CMake config

- src/output-flex.cpp
- tests/test-expire-from-geometry.cpp
- tests/test-flex-indexes.cpp
- tests/test-parse-osmium.cpp
Biggest problem here are the warnings for access of objects after std::move() in the SECTIONs in the tests. Those are not valid, because for each test only one section is ever run, but it was easiest to silence the warning this way.
> Various small fixes for problems found by clang-tidy

- README.md
- src/options.cpp
New versions of Nominatim don't need it any more but use the flex output.
> Mark gazetteer output as deprecated

- src/expire-tiles.cpp
- src/flex-lua-index.cpp
- src/flex-table-column.cpp
- src/flex-table.cpp
- src/flex-write.cpp
- src/format.hpp
- src/geom-transform.cpp
- src/input.cpp
- src/lua-utils.cpp
- src/options.cpp
- src/output-flex.cpp
- src/output.cpp
- src/pgsql-capabilities.cpp
- src/pgsql.cpp
- src/reprojection-generic-proj6.cpp
- src/reprojection.cpp
- src/table.cpp
- src/taginfo.cpp
- src/tagtransform-lua.cpp
- src/wkb.cpp
This adds the fmt_error() function as a convenient wrapper that creates std::runtime_errors from a formatted error message.
See also #1859
I am not totally happy with the function name `fmt_error()`, because is looks a bit like the error is about formatting in some way, when it only means "format the error message using the `fmt` library". But I can't think of a better name.
> Add fmt_error() function that uses fmt lib to format error message

- src/middle-pgsql.cpp
This way we don't need the weird "formatting" of a single id and the query might even be more efficient.
> Slightly better implementation to get node from database

- src/flex-index.cpp
- src/flex-table-column.cpp
- src/flex-table.cpp
- src/flex-write.cpp
- src/node-persistent-cache.cpp
- src/output-flex.cpp
- src/output-gazetteer.cpp
- src/pgsql-capabilities.cpp
- src/pgsql-helper.cpp
- src/progress-display.cpp
- src/reprojection-generic-proj4.cpp
- src/reprojection-generic-proj6.cpp
- src/table.cpp
- src/taginfo.cpp
- src/util.cpp
- tests/common-buffer.hpp
- tests/common-pg.hpp
- tests/test-db-copy-mgr.cpp
- tests/test-middle.cpp
- tests/test-output-gazetteer.cpp
- tests/test-output-pgsql-z_order.cpp
This replaces most uses of the ""_format literal with function calls to fmt::format(). The latter form is available in all versions of the fmt library, while the ""_format literal is deprecated in version 8 and removed in version 9.
This might cost us some performance and early error detection, because in at least some versions of the fmt library the _format() construct was used to compile the format patterns at run time. That's why there are some uses of the literal left in places where performance might be more critical, they need a closer look.
See #1859
> Use fmt::format() function instead of ""_format literal

- src/wkb.cpp
- src/wkb.hpp
The reason for this is that the new parser gets a `string_view` instead of a `string`. Down the line this makes it possible to remove a string copy which is currently needed.
> Refactor ewkb parser to use string_views instead of iterators

- src/flex-table.cpp
- src/flex-table.hpp
- src/output-flex.cpp
- tests/bdd/flex/lua-index-definitions.feature
- tests/bdd/steps/steps_db.py
If the user always needs the id index, they can force the index build even in non-slim (or slim+drop) mode by setting the `create_index` option of the `ids` setting in the define_table() Lua command to `always`. The default is `autpo` which means: Only build the index in slim mode.
See #1854
The test runner (`steps_db.py`) has been extended so that the table_exists() check also checks for views, so that we can access the data in the `pg_catalog.pg_indexes` view.
> Add option to always build id index

- src/pgsql.cpp
- src/pgsql.hpp
This also logs new connections with the PID of the backend used and when the connection is closed.
> Give each database connection a unique id and use it for logging

- src/geom-pole-of-inaccessibility.cpp
- tests/test-geom-pole-of-inaccessibility.cpp
https://wiki.sei.cmu.edu/confluence/display/c/FLP30-C.+Do+not+use+floating-point+variables+as+loop+counters
> Avoid type double for loop variable

- .github/workflows/test-install.yml
- scripts/osm2pgsql-replication
The parameter needs to be used, when querying the middle way table and needs to be forwarded to osm2pgsql when updating.
Adds a test installation with middle schema to the CI.
Fixes #1818.
> Correctly apply middle-schema parameter in replication script

- src/geom-pole-of-inaccessibility.cpp
That logging made some sense for developers but is probably too much for users. We don't have a way to enable extra verbose debug logging for specific subjects, so commenting it out.
> Remove some excessive logging in debug mode

- src/db-copy-mgr.hpp
- src/flex-table.hpp
- src/osmdata.cpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/output.hpp
In most cases database tables are filled based on OSM object types, so after we have read all nodes nothing will be added to node-type tables any more etc. So it makes sense to explicitly flush the COPY making sure this data is written to the database. If more data is later added, maybe because of second-stage processing, it doesn't matter, the COPY will be reopened.
> Flush COPY between nodes/ways and ways/relations respectively

- src/flex-table.cpp
- src/flex-table.hpp
- src/output-flex.cpp
Count for each table how many rows were inserted and how many were not inserted due to a NOT NULL constraint. Write out those counters to the debug log.
> Add row insert and not-null error counter to tables

- src/osmdata.cpp
- src/osmdata.hpp
- tests/test-parse-osmium.cpp
These were already not processed in create mode. In append mode we do need to remove any rows with those ids in the output tables, but we don't have to create new rows in any tables.
> Don't process objects without tags in pgsql/flex output in append mode

- tests/bdd/steps/steps_osm_data.py
If an input file was read first and in another step inline OSM data, the context still knew about the file and re-read it.
> Remove input file from BDD test context when reading inline OSM data

- flex-config/tilesets.lua
- src/CMakeLists.txt
- src/expire-config.hpp
- src/expire-tiles.cpp
- src/expire-tiles.hpp
- src/flex-lua-table.cpp
- src/flex-lua-table.hpp
- src/flex-lua-tileset.cpp
- src/flex-lua-tileset.hpp
- src/flex-table-column.cpp
- src/flex-table-column.hpp
- src/flex-table.cpp
- src/flex-table.hpp
- src/flex-tileset.cpp
- src/flex-tileset.hpp
- src/flex-write.cpp
- src/flex-write.hpp
- src/lua-utils.cpp
- src/lua-utils.hpp
- src/output-flex.cpp
- src/output-flex.hpp
- tests/CMakeLists.txt
- tests/bdd/flex/lua-expire.feature
- tests/bdd/flex/lua-index-definitions.feature
- tests/bdd/flex/lua-tileset-definitions.feature
- tests/bdd/flex/run-with-expire.feature
*This should be merged only after the next (bugfix) release.*
Tilesets are defined with `define_tileset()` in the Lua config file. They have a name, min and max zoom levels, and a filename or table name (optionally with schema). The filename or table specify where the contents of the tilesets are written to at the end of an osm2pgsql run.
Tilesets are referenced from geometry columns of database tables. A new `expire` field allows setting any number of tilesets and some additional parameters. In append mode, any geometry written to those columns triggers an entry in the corresponding tileset(s). Deletes also trigger these entries.
For backwards compatibility an expire config set with -e/--expire-tiles and -o/--expire-output is automatically added to all tables. Those command line options …
> Add tilesets to flex output allowing more flexible expire configuration

- src/flex-lua-expire-output.cpp
- tests/bdd/flex/lua-expire-output-definitions.feature
This would clash with the empty name used for the expire output created from the command line options.
> Check that expire output name is not empty

- flex-config/expire.lua
- src/debug-output.cpp
- src/debug-output.hpp
- src/expire-output.hpp
- src/flex-lua-expire-output.cpp
- src/flex-lua-table.cpp
- src/output-flex.cpp
- tests/bdd/flex/lua-expire-output-definitions.feature
- tests/bdd/flex/lua-expire.feature
- tests/bdd/flex/run-with-expire.feature
Expire outputs are now directly referenced from table column definitions as if they are Lua objects, not by using their name. In fact they don't even have a name any more.
> Reference expire outputs as Lua objects, not as strings with their names

- src/db-copy.cpp
- src/flex-table.cpp
- src/middle-pgsql.cpp
- src/output-flex.cpp
- src/pgsql.cpp
- src/table.cpp
There are more and more places where we used to change this setting. Instead we do it once on connection for everything and only if not in debug mode.
> Do "SET client_min_messages = WARNING" on all db connections

- docs/manpage_from_python.py
- docs/osm2pgsql-replication.1
While ArgParse correctly substitutes the program name in help text, argprse-manpage doesn't seem to respect that. Simply do our own replacement.
Fiexes #1946.
> Fix program name substitution in man page

- src/gen/osm2pgsql-gen.cpp
Actually implements the -V/--version option (that was already in the man page) and use that instead of --cimg-info. Add -S/--style option to help text.
> Fix inconsistencies in osm2pgsql-gen command line argument

- src/flex-lua-table.cpp
- src/osm2pgsql.cpp
- src/pgsql-capabilities.cpp
- src/pgsql-capabilities.hpp
So far we have only been checking schemas used in flex output. This now also checks that the schemas used for middle and pgsql output (if any) are available.
> Add function to check existence of database schema and use it

- src/middle-pgsql.cpp
- src/output-flex.cpp
- tests/bdd/flex/extra-attributes.feature
- tests/bdd/regression/extra-attributes.feature
- tests/test-middle.cpp
The middle stores OSM attributes (version, timestamp, changeset, uid, user) in "osm_*" pseudo-tags. When we get data back from the middle, we used to just leave them in there. This commit changes that behaviour: We pull the data out and put it into the proper attributes and remove the special tags. This is how the flex output needs the data and this is how a new middle (we are currently working on) will provide the data.
The pgsql output puts the pseudo-tags in already, because it had to do that on import anyway.
This also fixes a problem where the "osm_*" pseudo-tags were visible in the Lua config file of the flex output.
> Refactor middle: Pull special osm_* tags out of the tag list

- scripts/osm2pgsql-replication
When doing osm2pgsql-replication, if there's a network error, print that error to stdout & exit with failure code.
Previously, the `osm2pgsql-replication` would do this:
```
$ osm2pgsql-replication update -U osm -d "gis"  -- --multi-geometry  --hstore  --flat-nodes /nvme/flatnodes-tile/flatnodes.dat --style /srv/openstreetmap-carto/openstreetmap-carto.style --tag-transform-script /srv/openstreetmap-carto/openstreetmap-carto.lua  --middle-way-node-index-id-shift 5
2023-06-05 05:47:27 [INFO]: Using replication service 'https://planet.openstreetmap.org/replication/minute/'. Current sequence 5589863 (2023-05-25 10:05:54+02:00).
Traceback (most recent call last):
File "/usr/bin/osm2pgsql-replication", line 531, in <module>
sys.exit(main())
File "/usr/bin/osm2pgsql-replication", line 524, in …
```
> If there is a network error when trying to get replication status, print a more useful error message, and then exit

- src/middle-pgsql.cpp
- src/middle-ram.cpp
- src/middle-ram.hpp
- src/middle.hpp
- tests/test-middle.cpp
- tests/test-parse-osmium.cpp
The middle should always be called with these functions in the right order if the middle data is changed in any way, because there might be postprocessing done or buffers flushed etc.
This adds some code that checks in the middle that it is in the correct state. This code is only compiled in in debug mode.
> Call middle::after_nodes/ways/relations() in tests in right order

- scripts/osm2pgsql-replication
A handful of minor improvements to the `osm2pgsql-replication` output in this PR.
Here's what the (new) output looks like. changed lines in **bold**:
2023-06-15 11:48:39 [INFO]: Using replication service 'https://planet.openstreetmap.org/replication/minute/'.
**2023-06-15 11:48:39 [INFO]: Local database is at sequence 5619810, which is data up until 5 minute(s) ago (354 seconds ago, 2023-06-15T09:42Z).**
**2023-06-15 11:48:39 [INFO]:  Remote server is at sequence 5619815, which is data up until <1 minute ago (54 seconds ago, 2023-06-15T09:47Z).**
**2023-06-15 11:48:39 [INFO]: There are 5 sequence(s) on the remote server which will be applied locally. This represents 5 minute(s) (300 sec) of changes.**
2023-06-15 11:48:40  osm2pgsql version 1.4.1
2023-06-15 11:48:40  Database version: 12.9 …
> Improve the human readility of the `osm2pgsql-replication`

- src/logging.cpp
- src/logging.hpp
The (singleton) logger can be called from multiple threads at once, but it writes the m_needs_leading_return member variable. This commit turns that variable into an atomic to fix this.
This also moves some logic out of the generate_common_prefix() function so that we can make it const. This makes it easier to see that the code is now thread-safe.
> Fix: Fix threading issue in logger

- src/CMakeLists.txt
- src/command-line-parser.cpp
- src/command-line-parser.hpp
- src/middle-pgsql.hpp
- src/middle-ram.hpp
- src/middle.hpp
- src/options.hpp
- src/osm2pgsql.cpp
- src/osmdata.hpp
- src/output-flex.hpp
- src/tagtransform.hpp
- tests/test-options-parse.cpp
- tests/test-options-projection.cpp
Removes all code from the options_t class and makes it into a simple struct. All code parsing and checking the command line is now in command-line-parser.hpp/cpp.
> Split command line parser code from options

- src/command-line-parser.cpp
- src/flex-lua-geom.cpp
- src/geom-transform.hpp
- src/lua-utils.cpp
- src/lua-utils.hpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/tagtransform-lua.cpp
- src/tagtransform-lua.hpp
- tests/test-flex-indexes.cpp
- tests/test-lua-utils.cpp
There was a bit of a mess of different (types of) includes. We now only use '#include <lua.hpp>' which includes all Lua C headers correctly and also works for LuaJIT.
Technically it might include more than we need in some cases, because lua.hpp includes several C headers some of which are only needed sometimes, but the largest one (lua.h) is the one we always need, the others are tiny.
> Clean up lua includes

- scripts/osm2pgsql-replication
Some people would rather have non-approximate times ([e.g.](https://github.com/openstreetmap/osm2pgsql/pull/1975#pullrequestreview-1486491844)). This patch makes the times always show seconds.
I don't have a strong preference. I am OK with this patch being accepted or not.
> Make the display of time intervals show seconds.

- flex-config/generic.lua
This columns isn't magically filled any more since we switched from add_row() to insert().
> Remove "area" column in generic.lua example

- src/middle-pgsql.cpp
We only every use the name "id" for the middle tables, so it's totally fine that this is hardcoded here.
> Remove comment about hardcoded id

- src/middle-pgsql.cpp
They can not be set in the command.
> Fix: Index names are always in the same schema as their tables

- src/dependency-manager.cpp
- src/dependency-manager.hpp
- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/middle.hpp
- src/osmdata.cpp
- src/pgsql-helper.cpp
- src/pgsql-helper.hpp
- tests/test-middle.cpp
In append mode osm2pgsql has to find all parent ways and relations of changed nodes and parent relations of changed ways. This is done by with one query per object read from the input file which is quite wasteful. This changes the code to only do a single query for all dependencies. The list of all changed ids is COPYied into a temporary table. Then parent objects ids are found and written into another temporary table and then retrieved. (We could this without the extra temporary tables, but this could allow us later to use the content of those tables somewhere else, so I chose to do it this way. Should make a big difference perfomance-wise.)
These PR also fixes #423, the longstanding problem that ways and relations that are in the input file AND parents of changed objects were process …
> Middle: Get dependencies with single queries

- tests/data/test_multipolygon_diff.osc
OSM diffs usually do not contain members or tags for deleted objects.
> Fix test file: Remove members/tags from deleted objects

- src/pgsql.cpp
This fixes the build to handle v10 of the fmt library - the bundled version is currently v9 but an external version might not be.
Implicit conversion of enums to the underlying type has been removed in v10 so this makes the conversion of the libpq status enum to the underlying type explicit
> Fix build with v10 of the fmt library

- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- tests/test-middle.cpp
Only send one SQL command per exec(). This should fix a problem with the Pgpool-II connection pool server which doesn't support multi-statement queries. It also makes it hopefully a bit more obvious that there are several statements sent to the server. To that end I have also removed the semicolons at the end of the queries in all places, because they should never be needed any more.
I tested this with Pgpool-II and, at least in my quick test, everything ran through, which it doesn't without this patch.
Fixes #1994
> Don't do multi-statement queries

- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
When osm2pgsql runs in append mode it deletes all objects for which it gets new versions from the middle tables before then adding the new version. For a typical diff many of these deletes will be unnecessary because the objects are new. With this commit the behaviour changes slightly: We first get the maximum id from the nodes/ways/relations middle tables. This operation is fast, because the PostgreSQL max() function is aware of the btree index on those tables. Later, before we delete an object we check the id against that maximum id, if it is larger the object can't be in the table and we don't do the delete.
(Note that in theory we could use the fact that an object has version number 1 to figure out that it must be new. But this is much less robust than what we are doing here, for …
> Append mode: Do not try to delete objects that can't exist in middle

- src/db-copy.cpp
Without the cast to char(1) the index is not used.
In one case I have here this cut processing time in half! Not sure why this did not show up before (or why nobody noticed).
> Fix: Make sure index is used for type/id indexes in flex output

- src/output-flex.cpp
- src/output-pgsql.cpp
Postprocessing (like building indexes) on output tables happens in parallel. If there is a problem an exception is thrown which is forwarded to the main thread. Here the normal exception handling will clean up everything including the table datastructures still used by the postprocessing of the other tables which might still be in flight.
We fix this by storing the exception, waiting for all threads to finish and only then passing on the exception.
It is rather unlikely that we'll see this problem in the pgsql output because tables are more or less hardcoded there. It is more likely in the flex output, where users have many options of creating some havoc with unusual table definitions or so. In the flex output we store the table name so that there is at least a chance of narrowing down …
> Fix a crash when an exception is thrown in postprocessing

- flex-config/geometries.lua
- src/flex-lua-geom.cpp
- src/geom-functions.cpp
- src/geom-functions.hpp
- tests/test-geom-multipolygons.cpp
- tests/test-geom-polygons.cpp
To calculate the "real" area of a (multi)polygon. This is still an approximation. Results are similar to what ST_Area(geography, false) calculates in PostGIS. Accessible from Lua.
> Add spherical_area() function

- src/middle-pgsql.cpp
To be consistent with the naming scheme used by PostgreSQL.
> Use a name with _idx suffix for the indexes we create

- docs/osm2pgsql.md
- src/command-line-parser.cpp
- src/db-copy.hpp
- src/expire-output.hpp
- src/flex-lua-expire-output.cpp
- src/gen/gen-base.cpp
- src/gen/gen-tile-builtup.cpp
- src/gen/gen-tile-builtup.hpp
- src/gen/osm2pgsql-gen.cpp
- src/middle-pgsql.cpp
- src/options.hpp
- src/osm2pgsql.cpp
- src/pgsql-capabilities.cpp
- src/pgsql.cpp
- src/properties.cpp
- src/table.cpp
- tests/bdd/flex/lua-expire-output-definitions.feature
- tests/test-middle.cpp
- tests/test-pgsql-capabilities.cpp
- tests/test-pgsql.cpp
- tests/test-properties.cpp
Until now the default schema was empty and the PostgreSQL search path was used to find tables etc.
We now set the default schema for the middle and the pgsql and flex outputs to 'public'.
This simplifies the code, because we don't have to handle the case without schema specially any more. More importantly it makes it easier for the user to reason about what osm2pgsql is doing, because it does not depend on the setting of the search path in the PostgreSQL session.
This fixes a problem where osm2pgsql could not find the osm2pgsql_properties table it created itself, because it was created in a different schema than expected (#2010).
The behaviour of the gazetteer output has not changed. It still uses unqualified names.
This will be a breaking change for those users who rely on the old …
> Set default schema to 'public' and use qualified names everywhere

- docs/osm2pgsql-replication.1
- scripts/osm2pgsql-replication
- tests/bdd/command-line/replication.feature
- tests/bdd/command-line/replication_legacy.feature
- tests/bdd/environment.py
- tests/bdd/steps/replication_server_mock.py
- tests/bdd/steps/steps_db.py
- tests/bdd/steps/steps_execute.py
osm2pgsql-replication will now use the property table if available to store the replication state. If it is not available, it keeps using its own table.
Also adds a new option `--start-at` which allows to set an explicit start date and ignore the information in the database or to change the rollback timespan used when guessing the date from the data in the database.
All functions are now properly tested through BDD tests. This required changing how osm2pgsql-replication is called. It is now loaded as a module instead of run as a separate process. This way it is possible to monkeypatch the replication functions and simulate a fake replication service for the tests.
> Add support for osm2pgsql_properties table to osm2pgsql-replication

- src/db-copy.hpp
This is actually not required for COPY operation, only for DELETEs. The flex output can create tables without id.
> Fix: Remove assert for the id column

- src/command-line-parser.cpp
- src/expire-output.hpp
- src/flex-lua-expire-output.cpp
- src/flex-lua-expire-output.hpp
- src/flex-lua-table.cpp
- src/flex-lua-table.hpp
- src/flex-table.hpp
- src/gen/gen-base.cpp
- src/gen/osm2pgsql-gen.cpp
- src/options.hpp
- src/osm2pgsql.cpp
- src/output-flex.cpp
- tests/common-options.hpp
- tests/test-flex-indexes.cpp
This will be used as default for --middle-schema, --output-pgsql-schema, and for the different ways of setting a schema in the flex output and generalizer code.
This removes the last places where the schema was hardcoded to "public" (except as a default for this command line parameter and in some legacy gazetteer code).
> Add new command line parameter --schema that sets the default schema

- .github/actions/ubuntu-prerequisites/action.yml
- .github/workflows/ci.yml
- scripts/osm2pgsql-replication
- tests/bdd/environment.py
- tests/bdd/steps/steps_db.py
Avoids use of get_dsn_parameter() which is outdated anyway.
Also makes sure that the psycopg3 version is run in the CI. This in turn required to make the BDD tests work with psycopg3.
Fixes #2040.
> Fix running osm2pgsql-replication with psycopg3

- src/geom.hpp
- tests/test-expire-from-geometry.cpp
Points are small and not movable. Removes a complaint from clang-tidy about pessimizing std::move.
> Pass points as values, other geoms as reference to add_geometry()

- src/output-flex.cpp
- src/output-flex.hpp
This reverts a commit we recently did. Turns out we need the mutex to be around after the call to the function, because we are using the Lua stack after the function returns to get the results.
> Fix regression in select_relation_members()

- tests/bdd/flex/lua-expire-output-definitions.feature
This is a left-over from earlier use of the 'name' field.
> Clean tests: Remove 'name' field from expire which is never used

- CMakeLists.txt
For a long time we haven't officially supported 32bit architectures but not really disabled them. But this is giving us more problems lately and we can't test on 32 bit systems anyway, so this now gives us an up front check.
> Check in CMake config that we are building for 64bit architecture

- src/gen/gen-tile-builtup.cpp
- src/gen/gen-tile-raster.cpp
- src/gen/gen-tile-vector.cpp
So we either see the old or the new data. And we are saving transaction ids.
> Generalization: Wrap delete/upload of data in transaction

- src/gen/osm2pgsql-gen.cpp
Not only in singlethreaded more.
> Generalizer: Log tile being processed also in multithreaded mode

- src/gen/osm2pgsql-gen.cpp
In append mode we need to delete existing tiles. We need to set this parameter earlier, so the generalizer is initialized correctly.
> Generalizer bugfix: Set delete_existing earlier

- .github/actions/ubuntu-prerequisites/action.yml
- .github/actions/win-install/action.yml
- .github/workflows/ci.yml
- .github/workflows/test-install.yml
- CMakeLists.txt
- README.md
- src/gen/canvas.cpp
- src/gen/canvas.hpp
- src/gen/osm2pgsql-gen.cpp
Processing is an order of magnitude faster.
> Generalization: Switch from using CImg to OpenCV library.

- .github/actions/ubuntu-prerequisites/action.yml
- README.md
This package contains the CMake files needed to build osm2pgsql.
I was having build failures on a new server that I didn't have at home where it couldn't find the cmake file.
```
$ dpkg -S /usr/lib/x86_64-linux-gnu/cmake/opencv4/OpenCVConfig.cmake
libopencv-dev: /usr/lib/x86_64-linux-gnu/cmake/opencv4/OpenCVConfig.cmake
```
This showed it was part of libopencv-dev, which wasn't specified as required. The other opencv packages are dependencies of it.
It would be nice if the cmake files were part of a libopencv-core-dev or something so we didn't need to install all the libopencv-*-dev packages, but that's not how Debian packaged it.
> Require libopencv-dev on Debian systems

- src/middle-pgsql.cpp
This doesn't make much of a difference for the ways and rels table, but if we store all nodes in the database, it does make a huge difference, because most nodes don't have any tags. For a current planet, disk usage for the nodes table goes from 476 GB down to 409 GB saving 67 GB or nearly 15%.
Additionally it makes use of that table simpler. If you want to do any queries on tags, you need an index on the tags column on the nodes/ways/rels tables like this:
`CREATE INDEX ON planet_osm_ways USING gin (tags);`
But that is wasteful, because of the empty tags. We probably want to generate them as
`CREATE INDEX ON planet_osm_ways USING gin (tags) WHERE tags != '{}'::jsonb;`
But now all queries on those tables have to include that extra condition so that the query planner will use the index. …
> Use tags = NULL in middle tables if object doesn't have any tags

- .github/workflows/ci.yml
Because it doesn't work any more. Github actions output shows this message:
Error: You are using macOS 11.
We (and Apple) do not provide support for this old version. It is expected behaviour that some formulae will fail to build in this old version. It is expected behaviour that Homebrew will be buggy and slow. Do not create any issues about this on Homebrew's GitHub repositories. Do not create any issues even if you think this message is unrelated. Any opened issues will be immediately closed without response. Do not ask for help from Homebrew or its maintainers on social media. You may ask for help in Homebrew's discussions but are unlikely to receive a response. Try to figure out the problem yourself and submit a fix as a pull request. We will review it but may or may not accept it.
> Github action: Disable build on macOS 11

- .github/actions/win-install/action.yml
It is only needed for building osm2pgsql-gen but that also needs potrace which is not installed, because it isn't available as vcpkg.
> Github action: Remove OpenCV lib from windows build

- .github/workflows/ci.yml
Because it doesn't work due to some problem with Homebrew
> Github action: Disable build on macOS 13

- src/command-line-parser.cpp
- src/options.hpp
- src/osm2pgsql.cpp
- tests/common-options.hpp
- tests/test-options-projection.cpp
They were used to differentiate between empty and default value, but we can do that differently.
> Get rid of two boolean vars during comman line parsing

- man/osm2pgsql.1
- man/osm2pgsql.md
This should have been removed before version 1.10.0.
> Remove info that new middle db format is experimental from man page

- README.md
> Update dependency lists for linux distros in README.md

- src/middle-pgsql.cpp
When using the new middle format and --extra-attributes the SQL query was broken.
> Fix SQL query for updating a database

- src/db-copy.cpp
- src/expire-output.cpp
- src/flex-table.cpp
- src/gen/osm2pgsql-gen.cpp
- src/middle-pgsql.cpp
- src/osm2pgsql.cpp
- src/output-flex.cpp
- src/output-gazetteer.cpp
- src/pgsql.cpp
- src/pgsql.hpp
- src/properties.cpp
- src/table.cpp
- tests/common-pg.hpp
Adds a "context" parameter to database connection setup describing what this connection is for. This is something like "middle.query" or "out.pgsql". It will be added to the application name, so querying pg_stat_activity will show it like "osm2pgsql.middle.query/C2" etc.
> Use different application names for db connection to show context

- src/command-line-parser.cpp
These three commits add various checks for combinations of command line options which make no sense and so should not be used. For most of these warnings about ignored options are printed (which we can turn into hard fails in a later version of osm2pgsql). For the projection setting options (--latlong, -l, --merc, -m, --proj, and -E) an error is produced, because results are undefined if they are used together.
Fixes #142
> Add more checks of command line options

- src/db-copy.cpp
- src/flex-table.cpp
- src/pgsql.cpp
- src/table.cpp
This simplifies the code, because we don't have to decide whether to set this or not on each connection. And it doesn't matter much when setting this for read-only connections which don't need this.
Setting synchronous_commit = off speeds up writing to the database, because commis are not delayed until the WAL is written to disk. It can not lead to corruption of the database.
https://www.postgresql.org/docs/current/runtime-config-wal.html#GUC-SYNCHRONOUS-COMMIT
> Disable synchronous commit on all connections

- src/flex-lua-table.cpp
- src/flex-table.cpp
- src/flex-table.hpp
- src/output-flex.cpp
- src/output-flex.hpp
- tests/test-flex-indexes.cpp
Flex outputs uses a lot of connections, basically O(number of threads * number of tables). They are mostly idle but need resources on the server. And the PostgreSQL default max number of connections is often not large enough.
With these changes the number of connections is much smaller, connections are not open for such long a time.
* Use the same connection for all tables when creating the tables and various other setup tasks
* We have one extra connection for the COPYs
* Clustering, index creation is done in one connection per thread in the thread pool
There is probably more we can do here, closing some connections earlier or so. But this is a big step solving most of the problem.
> Significantly reduce number of db connection in flex output

- man/osm2pgsql.1
- man/osm2pgsql.md
- src/command-line-parser.cpp
> Mark command line option -i, --tablespace-index as deprecated

- man/osm2pgsql.1
- man/osm2pgsql.md
The option was deprecated before, but I neglected to update the man page.
> Mark --with-forward-dependencies as deprecated in man page

- src/expire-tiles.cpp
- tests/test-expire-tiles.cpp
- tests/test-reprojection.cpp
> Fix off-by-one error in expire code generating out of bounds tiles

- src/flex-table.cpp
- src/flex-table.hpp
- src/output-flex.cpp
They don't need anything from table_connection_t.
> Move analyze() and prepare() from table_connection_t to flex_table_t

- src/osmdata.cpp
Sync in after_relations() instead of in stop(). This makes the numbers of objects per second processed a bit more accurate.
> Sync output earlier for better objects/s numbers

- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
Make the member variables m_create_table, m_create_fw_dep_indexes, and m_prepare_queries private.
> Make member variables in table_desc private

- src/CMakeLists.txt
- src/dependency-manager.cpp
- src/dependency-manager.hpp
- src/idlist.cpp
- src/idlist.hpp
- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/middle.hpp
- src/osmdata.cpp
- src/osmdata.hpp
- src/osmtypes.hpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/output.hpp
- src/pgsql-helper.cpp
- src/pgsql-helper.hpp
- tests/common-buffer.hpp
- tests/test-middle.cpp
Refactor code that handles lists of ids. The old code used two datastructures, `idlist_t` which derives from the `std::vector` class and `osmium::index::IdSetSmall<osmid_t>`. The new code now only has one clean `idlist_t` class, which means there is less copying around of data.
> Refactor idlist

- .github/actions/ubuntu-prerequisites/action.yml
- .github/actions/win-install/action.yml
- .github/workflows/test-install.yml
- CMakeLists.txt
- README.md
- src/lua-setup.cpp
- src/osm2pgsql.cpp
- tests/common-cleanup.hpp
This changes the minimum GCC version supported from 7 to 8, because std::filesystem is only in glibc 8. All major distributions have support for this for a long time now.
> Use std::filesystem instead of boost::filesystem

- tests/bdd/flex/area.feature
- tests/bdd/flex/bbox.feature
- tests/bdd/flex/extra-attributes.feature
- tests/bdd/flex/invalid-geometries.feature
- tests/bdd/flex/line-splitting.feature
- tests/bdd/flex/multigeom.feature
- tests/bdd/flex/nocluster.feature
- tests/bdd/flex/nogeom.feature
- tests/bdd/flex/relation-changes.feature
- tests/data/test_output_flex.lua
- tests/data/test_output_flex_copy.lua
- tests/data/test_output_flex_stage2.lua
- tests/data/test_output_flex_stage2_alt.lua
- tests/data/test_output_flex_uni.lua
- tests/data/test_output_flex_validgeom.lua
- tests/data/test_output_flex_way.lua
This is in preparation for the removal of `add_row()`.
> Replace add_row() with insert() in tests

- .github/actions/win-install/action.yml
Removes now unneeded boost-property-tree and reduces the proj and bzip2 dependencies to the core build. proj depends on large libraries like curl and tiff by default, which in turn bring in lzma. None of them are required for the core functionalities of osm2pgsql.
This means that some more exotic features of proj are no longer available with the windows binary we distribute. You can still build your own, if you need them.
> Reduce dependencies for windows build

- src/output-flex.cpp
- tests/bdd/flex/missing-nodes.feature
A maximum of 100 missing nodes (with the ways they are missing from) are reported.
> Report missing nodes in the input

- src/db-copy.cpp
- src/db-copy.hpp
- src/expire-output.cpp
- src/expire-output.hpp
for database connections. Also use it as const ref instead of ptr.
> Consistently use db_connection as param/var name

- .github/workflows/ci.yml
PostgreSQL database is now installed in the runners home dir, because on macOS 14 the global install isn't allowed any more.
> Github actions: build on several macOS versions

- src/flex-lua-table.cpp
- src/flex-table.cpp
- src/flex-table.hpp
Specify with `create_index = 'unique'` in the `ids` field of the `define_table()` Lua function.
The user has to make sure not to insert multiple rows into such a table.
This can be useful if some program using the data has special handling for unique ids/primary keys, for instance when it needs unique ids to allow editing.
> Optionally build id index as unique index

- src/gen/gen-base.cpp
- src/gen/gen-base.hpp
- src/gen/gen-create.cpp
- src/gen/gen-create.hpp
- src/gen/gen-discrete-isolation.cpp
- src/gen/gen-discrete-isolation.hpp
- src/gen/gen-rivers.cpp
- src/gen/gen-rivers.hpp
- src/gen/gen-tile-builtup.cpp
- src/gen/gen-tile-builtup.hpp
- src/gen/gen-tile-raster.cpp
- src/gen/gen-tile-raster.hpp
- src/gen/gen-tile-vector.cpp
- src/gen/gen-tile-vector.hpp
- src/gen/gen-tile.cpp
- src/gen/gen-tile.hpp
- src/gen/osm2pgsql-gen.cpp
Running ANALYZE excessively can block the autovacuum daemon from ever finishing a vacuum. Better let the daemon handling analyzes and vacuums.
> All generalizers can now differentiate between create and append mode, use this to not run ANALYZE in append mode

- man/osm2pgsql.1
- man/osm2pgsql.md
- src/command-line-parser.cpp
Use --tablespace-slim-index and/or --tablespace-main-index instead.
> Remove the deprecated --tablespace-index option

- AUTHORS
Adds comma separating Martijn van Oosterhout and Sarah Hoffman.
> Change separation in AUTHORS

- src/debug-output.cpp
- src/flex-lua-index.cpp
- src/flex-table.cpp
- src/flex-table.hpp
- src/output-flex.cpp
Use accessor function flex_table_t::columns() to get to a vector of columns instead of having begin()/end() functions on flex_table_t.
> Remove somewhat magical way of iterating over table columns

- CMakeLists.txt
- src/gen/gen-create.cpp
- src/gen/gen-tile-sql.cpp
- src/gen/gen-tile-sql.hpp
It is named "tile-sql". Parameters are "name", "src_table", "dest_table", "zoom", and "sql", the command to be called. Use {ZOOM}, {X}, and {Y} in the command to set the zoom level and tile coordinates.
> Add tile-based generalizer calling SQL commands

- src/osmdata.cpp
- tests/bdd/flex/way-change.feature
New nodes or ways (ie with version=1) can't have parent ways or relations. So we don't have to add them to the list of "changed nodes" or "changed ways" to trigger re-processing of changed parents. This will save us a whole lot of effort looking for parents that are never there.
Note that we are checking for version != 1. In the (unlikely) case that there are no versions in the input file (making version == 0), everything will work as before.
> New nodes and ways can't have existing parents

- .github/actions/ubuntu-prerequisites/action.yml
- .github/workflows/ci.yml
Not sure abot the `--break-system-packages`, but that is the same fix we used on the new macOS builds.
Note that windows builds currently fail, this is unrelated. As far as I can tell it is already fixed in vcpkg, but Github needs to deploy the new vcpkg version.
> Add CI build on Ubuntu 24.04

- README.md
- src/flex-table.cpp
- src/osm2pgsql.cpp
- src/table.cpp
Ordering by geometry was done differently before PostGIS 2.4. This commit removed the old code and adds a check that PostGIS 3 is available.
For this specific case a check for PostGIS 2.4 or above would be sufficient, but PostGIS 3 is available for a long time now (it is in Debian Bullseye ("oldstable", released 2021) and Ubuntu 20.04).
> Remove special case for old PostGIS versions when clustering

- src/db-copy-mgr.hpp
- src/db-copy.cpp
- src/db-copy.hpp
- src/osmdata.cpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/output.hpp
Most output tables are only filled by either nodes or ways or relations. So it makes sense to close COPY operations after the last node/way/relation was found. Before this change active COPY operations could sometimes be open for a long time.
> Flush and sync COPYs after nodes, ways, and relations in flex output

- flex-config/indexes.lua
- src/debug-output.cpp
- src/flex-index.cpp
- src/flex-index.hpp
- src/flex-lua-index.cpp
Usually the name chosen by PostgreSQL for an index is fine, but sometimes you want to use a better name, especially if you are using expression indexes.
> Allow setting the index names in the flex output

- .github/workflows/ci.yml
Workaround for github/brew problem. Python is already install on the Github action runner and then homebrew comes along... See also: https://github.com/Homebrew/homebrew-core/issues/173191
> Remove python before brew install

- src/output-flex.cpp
- tests/bdd/flex/lua-basics.feature
No flex config file, or one that doesn't define any tables is usually not very useful. But it can be used in slim mode to have the middle tables only. Or it can be used to do some other processing or instead if the null output for testing.
We still output a warning, but no error any more if the style file is missing from the command line or if there are no tables defined.
> Allow empty config file in flex output

- src/db-copy-mgr.hpp
- src/db-copy.cpp
- src/db-copy.hpp
- tests/test-db-copy-thread.cpp
The second commit simplifies the code further.
> Refactor: Simplifiy code by using std::variant for copy mgr

- src/command-line-parser.cpp
- tests/bdd/environment.py
- tests/bdd/flex/lua-basics.feature
- tests/bdd/regression/properties.feature
- tests/bdd/steps/steps_execute.py
Lua is now always compiled into osm2pgsql, so there is no need to disable tests that require Lua. This should solve the issue where we accidentally keep disabling the tests without noticing.
Also reverts an accidental revert of the change that removes HAVE_LUA in the version printout. And fixes a test that unexpectedly succeeded (which we didn't see because the Lua-enabled tests didn't run).
> Remove option to disable BDD tests that require Lua

- scripts/osm2pgsql-replication
If a replication server becomes unavailable at an inconvenient time, it can happen that the replication script has retrieved a diff but cannot get the attached state file in order to determine the date of the data. Guess a date from the date in the diff file in such case. If that doesn't work either, simply leave the date in the status at whatever it was before.
Fixes #2195.
> Replication: guess date from file when state info is not available

- scripts/osm2pgsql-replication
- tests/bdd/command-line/replication.feature
- tests/bdd/command-line/replication_legacy.feature
- tests/bdd/steps/replication_server_mock.py
Adds checks to make sure that the requested state file actually still exists on the replication server and that the date of the state file is earlier than the requested start date.
These checks are mainly useful for the Geofabrik extracts servers which keep diffs only for a couple of months. If your extract is too old, the init command will now throw an error.
See also #2206.
> Replication: make sure that the computed start state is valid

- src/gen/osm2pgsql-gen.cpp
When generalizations are calculated by tile we need to know which extent to work on. If we are not working with a full planet we get that information from the (estimated) extent of the source layer. This adds support for determining the extent for raster-based source layers.
This is needed when we generalize source layers into rasters and then use those rasters as source for even lower level tiles.
> Generalization: Get extent of source layer also for raster layers

- src/output-flex.cpp
- src/output-flex.hpp
- tests/bdd/flex/lua-callbacks.feature
This allows some code to run after the initial stages of processing, i.e. between nodes and ways, ways and relations, and after relations.
> Add after_nodes/ways/relations() callback functions in Lua

- src/flex-lua-geom.cpp
- tests/bdd/flex/bbox.feature
Add new get_bbox() function for geometries in Lua. Like the get_bbox() function on OSM objects it returns the bounding box as four numbers in a Lua array (table). Having this function on geometries allows for more flexibility, you can call it on a centroid or a projected geometry for instance.
It is faster to call get_bbox() on the OSM object, because it removes the step of building the geometry first, so for those cases where this is good enough the old use is fine and is still supported.
See #2219
I have chosen the `get_bbox()` name instead of `envelope()`. a) this is consistent with `get_bbox()` on OSM objects and b) this leaves the option for adding a `envelope()` function later that returns a geometry, not a Lua array.
> Add get_bbox() function to geometries in Lua

- src/CMakeLists.txt
- src/geom-area-assembler.cpp
- src/geom-area-assembler.hpp
- src/geom-from-osm.cpp
- src/geom-from-osm.hpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/output-pgsql.cpp
- src/output-pgsql.hpp
- tests/test-geom-multipolygons.cpp
- tests/test-geom-polygons.cpp
The area assembler code we were using from libosmium was doing a few unnecessary things. This implements our own class which only does what's necessary.
We also reuse the memory buffer where we assemble the areas, which saves us from constant memory allocations.
Will not have a huge impact, but doing less work is always good.
> Refactor area assembler

- .clang-tidy
- .github/actions/build-and-test/action.yml
- .github/actions/clang-tidy/action.yml
- .github/actions/linux-cmake/action.yml
- .github/workflows/ci.yml
- .github/workflows/clang-tidy.yml
Currently CI will not fail if there are warnings from clang-tidy. This is, for the time being, only a way to easily see the messages.
Clang-tidy has its own workflow, so it doesn't interfere with the rest. But because it also needs cmake to run, the cmake run has been taken out of the 'build-and-test' action and put into its own.
This commit also disables some clang-tidy warnings we get from newer versions of clang-tidy.
> Github actions: Add clang-tidy run to CI

- src/command-line-parser.cpp
The option -C/--cache does nothing when used in non-slim mode, print a warning.
See #1501
> Add warning when --cache is used in non-slim mode

- src/node-persistent-cache.cpp
Use standard function instead of old unlink() function. Also add some error reporting.
> Remove flat node file using std::filesystem::remove()

- .luacheckrc
- flex-config/untagged.lua
- src/init.lua
- src/osmdata.cpp
- src/output-flex.cpp
- src/output-flex.hpp
- tests/bdd/flex/extra-attributes.feature
This is a backwards incompatible change in the way we are handling objects attributes (version, timestamp, changeset, uid, user) and the -x/--extra-attributes option in the flex output. The pgsql output is unaffected.
Old behaviour:
* If -x is set: attributes are available in Lua
* If -x is set: **all** objects are sent to the process functions, not only tagged objects
* If -x is set: Attributes are stored in middle tables in slim mode
New behaviour:
* Attributes are always available in Lua if they are in the data
* Only tagged objects are sent to the `process_node|way|relation` functions. There are new functions `process_untagged_node|way|relation` that are always called for untagged objects if they are defined.
* If -x is set: Attributes are stored in middle tables in slim mode (as …
> Changed handling of object attributes in flex output

- .clang-tidy
Reflect that in the comment in the clang-tidy config.
> We are not planning to litter the code with [[nodiscard]]

- src/command-line-parser.cpp
This was broken in 2449b294735c7cc59e4ee9acc4ef0473391175d4
> Add missing return in version output

- man/osm2pgsql.md
- src/command-line-parser.cpp
- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/options.hpp
Only supports bucket index which has been the default for a long time and works much better than the old one.
Also removes the command line option --middle-way-node-index-id-shift. The id shift can not be changed any more, it is hardcoded to 5 which was the default.
This is a potentially breaking change: Users with incompatible indexes have to do a reimport (or at least create the new index).
> Remove support for non-bucket index on middle way table

- src/gen/osm2pgsql-gen.cpp
- src/osm2pgsql.cpp
- src/properties.cpp
- src/properties.hpp
- tests/test-properties.cpp
(Changes to) Properties are stored at a later time in the database so the db is not changed if osm2pgsql fails for some reason. Basically we are trying to do as many checks as possible before actually writing the properties to the db. For instance the input file is now actually opened before properties are written,
This solves some cases already mentioned in PR #2085.
> Make property handling more robust

- src/gen/osm2pgsql-gen.cpp
No reason to use dynamically created format strings here.
> Simplify code showing timers in generalization code

- CMakeLists.txt
> Various version updates in cmake cfg

- flex-config/README.md
- flex-config/public-transport.lua
- src/init.lua
- src/middle-pgsql.cpp
- src/middle-pgsql.hpp
- src/middle-ram.cpp
- src/middle-ram.hpp
- src/middle.hpp
- src/osmdata.cpp
- src/output-flex.cpp
- src/output-flex.hpp
- src/output.hpp
This is completely analog to how way processing happens in the second stage. So from the select_relation_member() function in the Lua config file you can now also return a list of nodes that you request to process again.
Note that this will only re-process the member nodes themselves, ways which have these nodes as members are not re-processed. Also there is no way to mark member nodes of ways, only member nodes of relations. So this will allow processing, say, stop positions in public transport route relations but not, say, barriers on roads.
This change is now possible because we removed support for the old middle format which didn't allow storing the complete nodes (with tags).
> Add support for node processing in second stage

- .github/workflows/ci.yml
- src/command-line-parser.cpp
- src/output-pgsql.cpp
The check was in the wrong position. When running updates the output is read from the osm2pgsql_properties table which only happened after the check, so you'd still see the message even if you are using the flex output.
Sorry about that.
> Move pgsql deprecation check to right spot

- scripts/osm2pgsql-replication
- tests/bdd/command-line/replication_schema.feature
`--schema` and `--middle-schema` are now forwarded as-is to osm2pgsql.
Fixes #2259.
> Properly forward schema parameters from replication script

- src/middle-pgsql.cpp
- src/pgsql-params.hpp
- tests/common-import.hpp
- tests/common-options.hpp
- tests/test-output-flex-update.cpp
A temporary function `osm2pgsql_find_changed_ways` may be created during the update process, which has been placed under the `public` schema, regardless of any chosen custom schema. This is a problem if one implements security based on schemas, e.g., by assigning a custom schema for osm2pgsql and restricting it from accessing `public` elements (as mentioned at the end of [section 3.3](https://osm2pgsql.org/doc/manual.html#security-considerations) of the manual).
This PR fixes that by using the configured schema. Additionally, tests are added in which a situation like the above is simulated (e.g., a user that can only access a custom schema and not `public`). Please tell me if there's anything I should improve/change before this can be merged.
> Properly set schema for osm2pgsql_find_changed_ways()

- src/osmdata.cpp
- src/osmdata.hpp
Remove some functions and inline code.
> Simplify osmdata_t class

- src/expire-output.cpp
- src/flex-table.cpp
- src/middle-pgsql.cpp
- src/pgsql.cpp
- src/pgsql.hpp
- src/properties.cpp
- src/table.cpp
Introduce a new pg_conn_t::prepare() function which is now used in several places instead of pg_conn_t::exec() with a SQL PREPARE command.
This does not yet replace all places where PREPARE is used, the rest will come in a later commit.
This is to make osm2pgsql work with some connection poolers that have problems with prepared statements. For some background see https://github.com/osm2pgsql-dev/osm2pgsql/discussions/2118 and https://www.crunchydata.com/blog/prepared-statements-in-transaction-mode-for-pgbouncer
> Use protocol level prepare instead of PREPARE sql commands

- src/format.hpp
- src/gen/params.cpp
- src/gen/params.hpp
- src/gen/template.cpp
When including the fmt/std.h header the fmt library has support for formatting std::variant. So we don't need to do this ourselves.
> Refactor: Use fmt builtin functionality to format variants

- src/node-persistent-cache.cpp
In a flat node file the first location is that of node id 0, which does not exist. So the first location must always be the undefined location, otherwise we might be looking at a different kind of file.
This adds a check for forwards compatibility. If and when we change the file format, we can use the first 8 bytes to differentiate the file formats.
> Check flat node file format for forwards compatibility

- src/flex-lua-table.cpp
- src/flex-table.cpp
- src/flex-table.hpp
- tests/bdd/flex/lua-table-definitions.feature
This is basically just a small variant of the option to create unique indexes. But it documents the intention that the specified columns is supposed to be the primary key. Some programs (like pg_featureserv) use this information to handle the primary key specially.
> Add option to create primary key on flex tables

- .github/actions/win-postgres/action.yml
- .github/workflows/ci.yml
Doesn't use nyurik's postgis action directly but simply borrows the part of the code that downloads the postgis bundle from OSGeo. This seems to work nicely with the existing workflow.
Fixes #2285.
> Actions: use OSGeo downloads for Postgis on Windows and enable windows-2025

- src/middle-pgsql.cpp
- tests/bdd/flex/node-add.feature
- tests/data/test_output_flex_node.lua
In two-stage processing when getting nodes from the middle we are running the same SQL query as when getting the node locations. But that doesn't work. We need more information, the tags (and possibly the attributes). This fixes this by running a different prepared query in this case.
Fixes #2298
> Fix problem in slim mode with two-state processing of nodes

- .github/workflows/ci.yml
- .github/workflows/test-install.yml
- CMakeLists.txt
- README.md
- src/flex-lua-index.cpp
- src/osm2pgsql.cpp
Github Actions will pull the Ubuntu 20.04 images beginning of April, so it's time to update our test images to newer versions. This moves all tests previously done in 20.04 to 22.04 and the ones that already were on 22.04 to 24.04.
There are a couple of software versions we cannot test anymore, so they go out of support. New minimum supported versions are:
* PostgreSQL 11+
* PostGIS 3.0+
* gcc 10+
* clang 13+
Also updates minimum version of cmake to 3.10 because more recent cmake versions complain otherwise.
> Update Github Actions to newer Ubuntu versions

- src/middle-pgsql.cpp
- src/middle-ram.cpp
This is an additional fix to the fix in 8d1a55e5. If a flat node file is used, nodes are not stored in the database (unless `--middle-with-nodes` is specified, but also then only nodes with tags are stored in the database).
There are two problems here:
1. The "get_node" prepared statement was not prepared in this case, so it fails when executes. This is fixed by only executing that statement if `m_store_options.nodes` is set in the middle.
2. If there is no node in the database, there might still be one in the flat node file. So we need to try this and create the node from the information in there. (It will only have the node id and location in it, but at least we get the location.)
The second commit fixes essentially the same problem for non-slim mode. In that case we look into the (disk …
> Fix two-stage processing when flat node file is used

- .github/actions/ubuntu-prerequisites/action.yml
Postgresql's apt repository has slightly changed the setup rules for its postgres packages in Thursday's release: normally the package would automatically set up and start a database, if not exists for the version installed. The new behaviour seems to be to only set up the database if there is no Postgresql database set up at all. This new behaviour makes perfect sense, but breaks CI runs which so far have kept the already installed postgres from the default version around. The version we actually want to test against is not installed anymore. The fix is to purge the default version instead of just removing it.
The PR also switches to the Debian-supplied way of setting up the PostgreSQL apt repository and removes some code for a clang version which has long fallen out of support.
> github actions: fix setup of PostgreSQL

- src/db-copy.cpp
In 6bd67a749d890a092557c8812fd67c0d3f170dce we changed the code to not copy the connection parameters but the connection.
> Remove comment that doesn't apply any more

- src/middle-pgsql.cpp
- src/middle-ram.cpp
- src/node-persistent-cache.cpp
- src/node-persistent-cache.hpp
- tests/bdd/regression/properties.feature
- tests/test-persistent-cache.cpp
Also an extra commit that opens flat node file in binary mode on Windows.
> Do not create flat node files in append mode

- src/geom-boost-adaptor.hpp
These types/functions are used to let boost functions access our polygon/ring types. They are supposed to return (const) references.
I found the bug while doing more complicated geometry processing, working on some future code for osm2pgsql. It seems the buggy code does not produce any problems in current code, but I can not guarantee it. Theoretically it could lead to crashes. It might make some code slower, though, because of unnecessary copying.
> Fix inner/outer ring accessor boost::geometry adaptor types/functions

- .clang-tidy
- src/flex-lua-geom.cpp
- src/gen/gen-base.cpp
- src/gen/gen-rivers.cpp
- src/gen/raster.cpp
- src/output-flex.cpp
- tests/test-lua-utils.cpp
- tests/test-output-flex-example-configs.cpp
- tests/test-output-flex-update.cpp
> Various clang-tidy fixes

- src/geom-functions.cpp
- src/wildcmp.cpp
> Fix/disable some warnings generated by clang-tidy

- src/flex-lua-expire-output.cpp
- src/flex-lua-expire-output.hpp
- src/flex-lua-table.cpp
- src/flex-lua-table.hpp
- src/flex-lua-wrapper.hpp
- src/output-flex.cpp
- src/output-flex.hpp
The class output_flex_t is huge, output-flex.cpp with over 1000 lines is the largest source code file we have. This change moves some code out of there.
This change introduces a new templated wrapper base class (lua_wrapper_base) for wrapping C++ objects in Lua. It is then used for the "Table" and "ExpireOutput" Lua objects. Functions that are called from Lua on those objects are called through the wrapper on the underlying C++ objects using little wrapper functions in the wrapper classes. A new macro TRAMPOLINE_WRAPPED_OBJECT() is used to call these functions where we used the TRAMPOLINE() macro before.
One problem is though that more complex functions need more of the machinery in the output_flex_t class to work, specifically this is the "insert" function for tables which can not be …
> Refactor: Split out some code from output_flex_t class

- flex-config/README.md
- flex-config/simple.lua
- flex-config/unitable.lua
It is probably more confusing than useful here for the beginner. I have added something about the library to the manual instead.
> Don't mention the Lua inspect library any more in example configs

- src/flex-lua-expire-output.cpp
- src/flex-lua-expire-output.hpp
- src/flex-lua-locator.cpp
- src/flex-lua-locator.hpp
- src/flex-lua-table.cpp
- src/flex-lua-table.hpp
- src/flex-lua-wrapper.hpp
- src/gen/gen-discrete-isolation.cpp
- src/geom-box.cpp
- src/geom-pole-of-inaccessibility.cpp
- src/logging.cpp
- src/params.hpp
Found by clang-tidy. See individual commits.
> Various cleanups

- man/osm2pgsql.md
- scripts/osm2pgsql-replication
- src/command-line-app.cpp
This was inconsistent and documented wrong. We prefer the --username variant, because that is consistent with psql, but both work now everwhere.
See #2342
> Allow --username and --user in osm2pgsql and osm2pgsql-replication

- src/flex-lua-expire-output.cpp
- src/flex-lua-expire-output.hpp
- src/flex-lua-geom.cpp
- src/flex-lua-locator.cpp
- src/flex-lua-locator.hpp
- src/flex-lua-table.cpp
- src/flex-lua-table.hpp
- src/gen/osm2pgsql-gen.cpp
- src/output-flex.cpp
* Using uppercase, because they are constants
* Using the word "CLASS" because it is easier to understand then the generic "name" or the Luaish "metatable"
* Using char* not std::string_view, because its simpler use (no .data() needed)
This is for all the Lua "classes" that we use in flex config files:
* ExpireOutput
* Geometry
* Locator
* OSMObject
* Table
> Consistent naming and type for "Lua class names"

- src/output-flex.cpp
- src/output-flex.hpp
- tests/bdd/flex/delete-callbacks.feature
Trying to use the delete callbacks in practice it turned out that the naming is somewhat inconsistent with what we already have. Given a callback named `process_thing` and `processed_untagged_thing`, the more obvious naming is `process_deleted_thing`.
> Improve naming of delete callbacks

- src/db-copy-mgr.hpp
- src/geom-boost-adaptor.hpp
- src/geom-functions.hpp
- src/lua-utils.hpp
- src/output-pgsql.hpp
- src/params.hpp
- src/pgsql.hpp
- src/table.cpp
- src/taginfo-impl.hpp
- src/taginfo.cpp
- src/tile.hpp
> Various fixes for stuff found by clang-tidy

- src/expire-output.hpp
- src/flex-lua-expire-output.cpp
- src/flex-lua-expire-output.hpp
- src/flex-lua-locator.cpp
- src/flex-lua-locator.hpp
- src/flex-lua-table.cpp
- src/flex-lua-table.hpp
- src/lua-setup.cpp
- src/lua-utils.cpp
- src/lua-utils.hpp
- src/output-flex.cpp
- src/tagtransform-lua.cpp
> Miscellaneous refactorings

- src/flex-lua-expire-output.cpp
- src/flex-lua-geom.cpp
- src/flex-lua-locator.cpp
- src/flex-lua-table.cpp
- src/init.lua
- src/lua-utils.cpp
- src/lua-utils.hpp
- src/output-flex.cpp
There is a lot of duplication in that code.
> Refactor Lua metatable initialization

- tests/test-output-pgsql-int4.cpp
Fixes MSVC warning. This is due to the way integer literals are parsed.
> Workaround for int that is too large

- src/command-line-parser.cpp
- src/command-line-parser.hpp
- src/gen/osm2pgsql-gen.cpp
- src/osm2pgsql.cpp
- src/version.cpp.in
- src/version.hpp
To unify the way we print the version number on startup and when using --version for the osm2pgsql and osm2pgsql-gen commands, respectively.
Also show more libraries used with --version.
> Reorganize the way we are printing version numbers

- src/output-flex.cpp
- src/output-flex.hpp
- tests/bdd/flex/untagged.feature
- tests/data/test_output_flex_untagged.lua
When we introduced the "untagged" callbacks in bc87ea2c8b4ea0bcac09975627e78765fda8927e, we did not call the process_untagged_way/relation callbacks for untagged ways/relations  in stage 1b and 1c, but called the normal process_way/relation callbacks. That's not correct. So this is changed in this commit.
For stage2 processing the answer which callback to call is a bit more complicated: On first glance we should also call the "untagged" function for untagged objects. But if we call the "untagged" function in that case, we would have to implement that function and it would be called for the millions of untagged objects we are not interested in. So it is arguably better to call the normal processing functions here. After all we explicitly requested the processing function to be called with …
> Process untagged ways/relations in stage 1b/c correctly
