osm2pgsql-dev/osm2pgsql

middle-pgsql.cpp
Somehow the way the node-persistent cache was used, was really confused. New instances have been created but not in the new threads but in the old one and, what is worse, before the cache was actually commited to disk, so any reading would have been rather random. This commit now closes the cache used during the reading phase properly and then creates new instances for each thread. That's how the C code did it before.
There is also some strangeness in the way the cache is opened for reading only (using append mode instead of the cache_already_written variable) but that doesn't look fatal, so it's for another pull request.
Hopefully, fixes #229. @simonpoole would you mind trying it out?
=> use one instance of node-persistant-cache per thread

middle-pgsql.cpp
We do not support versions earlier than 8.4 anymore and have not for some time, so there's no need for the logic to handle old versions which didn't support the FASTUPDATE storage parameter.
Fixes #281
=> Remove FASTUPDATE hack to handle different PostgreSQL versions

docs/migrations.md
=> Add documentation on how to migrate between versions of osm2pgsql

README.md
With #282 we can use a simpler FreeBSD ./configure line
=> Update FreeBSD configure line

table.cpp
The geohash function on postgis 1.5. cannot handle empty geometries.
Just fixes the symptoms. Still need to find out why osm2pgsql is creating empty geometries in the first place.
=> check for empty geometries before using geohash

.gitignore, Makefile.am, tests/test-output-multi-tags.cpp, tests/test_output_multi_tags.json, tests/test_output_multi_tags.lua, tests/test_output_multi_tags.osm
These were created to try to debug #273, but they all pass. Regardless, they make a good regression test of functionality without existing coverage.
=> Add basic multi-backend tag processing tests

node-persistent-cache-reader.cpp
rebased #312, but I want to let Travis check it pre-merge
=> Merge woodpeck atoi

docs/multi.md, multi.lua, multi.style.json
This gives a demonstration of points, lines, and areas. It also shows a number of generic techniques that might be useful for others doing Lua conversions - multi-backend or otherwise.
Unfortunately, it exposes a bug in osm2pgsql with lines and the multi-backend. This is actually why I wrote it - to investigate that bug.
cc @zerebubuth @kevinkreiser 
also cc @systemed because lua.
=> Multi line example

geometry-builder.cpp, middle-pgsql.cpp, osm2pgsql.cpp, output-pgsql.cpp, tests/regression-test.py, tests/test-expire-tiles.cpp, tests/test-parse-options.cpp, tests/test-pgsql-escape.cpp
Does not change what's under discussion for https://github.com/openstreetmap/osm2pgsql/pull/299#discussion_r25123742
Unresolved is https://github.com/openstreetmap/osm2pgsql/pull/299#discussion_r25123613
=> Static analysis 2

README.md
Some additional packages were needed, and other ones covered as dependencies of the new ones.
=> Update package list for Fedora

multi.lua, multi.style.json
=> Fix builing typo in example multi style

docs/osm2pgsql.1, options.cpp, reprojection.cpp, reprojection.hpp, tests/test-parse-options.cpp
=> Remove oldmerc option

tests/middle-tests.cpp, tests/middle-tests.hpp, tests/test-middle-pgsql.cpp, tests/test-middle-ram.cpp
Based on https://github.com/openstreetmap/osm2pgsql/pull/360#issuecomment-116149307, but directly using the middle.
It does not check
* slim with zero cache
* slim with flat nodes
* out of order nodes
* negative IDs
* error conditions
This should probably be merged before #360
=> Storage tests expansion

geometry-builder.cpp
geometry-builder.cpp had a complex mix of tabs and spaces
Fixes #259
=> Fix whitespace errors in geometry-build.cpp

AUTHORS, CONTRIBUTING.md, README.md
cc @zerebubuth and @kevinkreiser since I'm adding their names to AUTHORS, both having significant number of commits.
Fixes #370
=> Add a readme for contributors

geometry-builder.cpp, middle-ram.hpp
This was just a drop-in replacement with no compile errors.
ref http://stackoverflow.com/questions/3451099/stdauto-ptr-to-stdunique-ptr, http://herbsutter.com/2013/05/29/gotw-89-solution-smart-pointers/
=> Switch from auto_ptr to unique_ptr

geometry-builder.cpp, geometry-builder.hpp, middle-pgsql.cpp, middle-pgsql.hpp, node-persistent-cache-reader.cpp, node-persistent-cache.cpp, node-persistent-cache.hpp, options.cpp, options.hpp, osmdata.cpp, output.cpp, parse.hpp, tests/test-middle-flat.cpp, tests/test-middle-pgsql.cpp, tests/test-output-multi-line-storage.cpp, tests/test-output-multi-line.cpp, tests/test-output-multi-point-multi-table.cpp, tests/test-output-multi-point.cpp, tests/test-output-multi-poly-trivial.cpp, tests/test-output-multi-polygon.cpp, tests/test-output-multi-tags.cpp, tests/test-output-pgsql-tablespace.cpp, tests/test-output-pgsql.cpp
I was going to implement a `table_options_t` (https://github.com/openstreetmap/osm2pgsql/pull/279#discussion_r24395675) but it's started to look more complicated, so I'm doing a PR on just the initial change.
=> Update on/off options to bool

middle-ram.cpp, middle-ram.hpp
=> use vectors of pointers in middle-ram to reduce memory footprint

expire-tiles.cpp, middle-pgsql.cpp, middle-ram.cpp, node-persistent-cache-reader.cpp, node-persistent-cache.cpp, node-ram-cache.cpp, node-ram-cache.hpp, options.cpp, osm2pgsql.cpp, osmdata.cpp, output-gazetteer.cpp, output-pgsql.cpp, parse.cpp, pgsql.cpp, reprojection.cpp, table.cpp, taginfo.cpp, tests/common-pg.cpp, tests/middle-tests.cpp, tests/test-hstore-match-only.cpp, tests/test-output-multi-line.cpp, tests/test-output-multi-point-multi-table.cpp, tests/test-output-multi-point.cpp, tests/test-output-multi-polygon.cpp, tests/test-output-pgsql-tablespace.cpp, tests/test-output-pgsql-z_order.cpp, tests/test-output-pgsql.cpp, tests/test-parse-options.cpp, tests/test-parse-xml2.cpp
This leaves alone the o5m code, geos, and libosmium. The former is hand-crafted C bit fiddling which is scary to touch and not covered by tests, while the latter are external libraries.
=> Move from NULL to nullptr

middle-pgsql.cpp, osmdata.cpp
I'm surprised it was so little used
=> Replace boost::unordered_map with std::unordered_map

geometry-builder.hpp, output-gazetteer.cpp, output-multi.cpp, output-pgsql.cpp, tagtransform.cpp, tagtransform.hpp
I didn't get all the way through tagtransform, as I realized the "tag" type would force me to choose bad variable names, not having a `_t` on the end, so I'm working on that in a different PR.
=> for each loop conversion

middle-pgsql.cpp, osmtypes.hpp, output-gazetteer.cpp, output-gazetteer.hpp, output-pgsql.cpp, parse-o5m.cpp, table.cpp, tagtransform.cpp
`tag_t` instead of `tag`, since I kept wanting to name variables the latter.
=> Rename tag type

id-tracker.hpp
This is based on @zerebubuth's comments in
https://github.com/openstreetmap/osm2pgsql/commit/aa1ff6e5d07b7a356bc88093d2673fc7929c2133#commitcomment-10961958
=> Add documentation to id_tracker

geometry-builder.cpp, node-persistent-cache.cpp, node-ram-cache.hpp, parse-o5m.cpp, pgsql.hpp, sprompt.cpp, table.cpp, tests/middle-tests.cpp, tests/test-options-parse.cpp
Here are the additions to https://github.com/openstreetmap/osm2pgsql/pull/484
I tried to patch only the most obvious parts anfd touch only local variables. 
https://github.com/openstreetmap/osm2pgsql/issues/470
Tried not to touch files from other PRs.
=> Fix more MSVC warnings related to size_t

.travis.yml, CMakeLists.txt, README.md, appveyor.yml, cmake/config.h.in, geometry-builder.cpp, middle-pgsql.cpp, middle-pgsql.hpp, options.cpp, osmdata.cpp, output-pgsql.cpp
=> Replace pthread and boost::thread with std::async

expire-tiles.cpp, geometry-builder.cpp, geometry-builder.hpp, processor-point.cpp
Includes refactoring of duplicated code into functions, removal of remaining deletes and some code style cleanup. Refer to individual commits for more information.
=> Cleanup geometry-builder

tests/test-output-multi-line.cpp
This fixes one of the tests. The other one needs a bit of redesign to still cover what it was doing
=> update test-output-multi-line numbers

CMakeLists.txt
=> regression: set DATA_DIR to defaut install directory

reprojection.cpp, tests/CMakeLists.txt, tests/common-pg.cpp, tests/common-pg.hpp, tests/test-options-projection.cpp
=> fix projection info for generic projection

README.md
=> Add information on distro options for osm2pgsql

docs/osm2pgsql.1
option "--melts-geometry" should be "--multi-geometry"
=> typo in man page

default.style
The original phrase was difficult to understand. I slightly changed to a more direct phrasing.
=> Small gramatic change

expire-tiles.cpp
=> update URL to example expire tiles script

tests/test-parse-xml2.cpp
Hopefully fixes the travis issues on #630.
=> fix copy constructor in test output class

docs/osm2pgsql.1, geometry-builder.cpp, options.cpp, tests/CMakeLists.txt, tests/test-output-pgsql-validgeom.cpp, tests/test_output_pgsql_validgeom.osm
This is a manual rebase of #428. I've just checked that it compiles and that the new test passes.
Fixes #427
=> Don't let invalid geometries into the database

geometry-builder.cpp
=> Fix double negation in geometry builder

table.cpp
=> Don't grant to PUBLIC by default

wkb.hpp
=> only skip srid in WKB header when srid flag is set

middle-pgsql.cpp, output-gazetteer.cpp, table.cpp
=> DROP TABLE ... CASCADE when cleaning up

taginfo.cpp
=> close style file on error

README.md
=> add link to Windows build for latest release

geometry-processor.cpp
This fixes an off by one error
Fixes #723
=> Iterate loop variable after access, not before

output-multi.cpp
Fixes #735
I'll backport this as it fixes a serious bug present in previous versions.
=> Use the same logic for queuing pending ways with multi and pgsql

CMakeLists.txt, appveyor.yml
=> Update appveyor libs

output-gazetteer.cpp
This is part of  https://github.com/openstreetmap/Nominatim/pull/703 by @roques. See PR for details.
=> Reorder columns for gazetteer place table

output-gazetteer.cpp
Fixes https://github.com/openstreetmap/Nominatim/issues/725.
=> gazetteer: add support for 'club' as primary tag

output-gazetteer.cpp
=> gazetteer: revert use of "char" type

.travis.yml
WIP - I need it to build on Travis
=> Use -fsanitize=address on travis

osmium-builder.cpp, osmium-builder.hpp, output-gazetteer.cpp, output-pgsql.cpp, processor-line.cpp
=> multi-output: reintroduce line spliting

table.cpp
Because libosmium only checks 4326 validity and osm2pgsql can
transform to a different projection, another validity check needs
to be done if a different projection is being used.
A trigger is not the only possible method, but something like
`INSERT ... ON CONFLICT ...` requires 9.5.
This PR removes some of the performance gains of libosmium geometries, but is still faster than 0.92.1.
Taking the combined geofabrik BC and WA extracts and importing with ``./osm2pgsql [-l|-m] -d gis -C 1200 --number-processes 4 ~/osm/planet/bc_wa-170908.osm.pbf -S ../default.style`` I get the following as median times from three runs
```
-m    -l
pr          121    94
0.94.0-RC1   99    95
0.92.1      161   155
```
I am testing with a larger extract to see if there are any scaling problems, but don't …
=> Use PostGIS to make sure geometries are valid

wkb.hpp
=> Use memcpy for potentially unaligned access to WKB

reprojection.cpp
Also switches to libosmium's projection function which uses a faster approximation for lower latitudes.
Fixes #793.
When importing Antarctica, the number of valid polygons increases from 64954 on master to 66949 in this change and the number of notices from postgresql wrt self-intersecting polygons decreases from many to 0. I have not checked the outcome visually.
=> Extend mercator projection to 89.99 latitude

tagtransform-c.cpp
=> fix uninitialised variable

CONTRIBUTING.md, README.md
=> document dependency on psycopg for testing

.travis.yml, CMakeLists.txt, cmake/FindLuaJIT.cmake
=> Added LuaJIT support

tagtransform-lua.cpp
I don't know exactly why errors in Lua processing are only sent to stderr and processing continues. There could be some nasty issues overflowing the stack and causing other types of corruption.
I have changed those messages to runtime errors now. Maybe there are some reasons why this doesn't make sense, in which case I'm happy to revert that part of this PR.
Also, I added some error handling for lua_tostring with details about incorrect data type. Instead of throwing some strange exception as in #664, processing now aborts with the following message.
_Osm2pgsql failed due to ERROR: Basic tag processing returned NULL value. Possibly this is due an incorrect data type 'boolean'._
Another example:
```lua
function filter_tags_generic(tags)
local foo = 0
local bar = {}
bar[123] = function() …
```
=> Lua function errors now trigger runtime exception

osmium-builder.cpp
=> catch exceptions by reference

osmdata.cpp
This step is one of the biggest step with no logging, it looks like osm2pgsql is stuck but actually it is processing these pending items. Now it'll display the number of pending items left to process instead of being silent :).
=> Display progress while processing pending relations/ways

output-gazetteer.cpp
See https://github.com/openstreetmap/Nominatim/issues/1176 for details.
=> gazetteer: restrict operator for amenity to restaurant and fuel

.travis.yml, CONTRIBUTING.md, tests/CMakeLists.txt, tests/regression-test.py
Switch to Python 3 since Python 2 is EOL at the end of the year.
=> Use Python 3 for regression-test.py.

.travis.yml, docs/osm2pgsql.1, docs/usage.md, middle-pgsql.cpp, options.cpp, options.hpp
=> Remove unlogged

options.cpp
=> Fix the name of the password environment variable.

docs/osm2pgsql.1, docs/usage.md, options.cpp
Recommend the size of the PBF file as this is agnostic to the database growth.
=> put different advise on cache size in sync

README.md
* Use https where possible
* Fix broken URLs
=> Readme URL updates

CMakeLists.txt, options.cpp
Removes the dependency on libgen including some CMake stuff for the
price of writing a small function ourselves.
=> Remove dependency on libgen.

middle-pgsql.cpp
This looks like a leftover from before.
=> Remove superfluous magic

tests/data/test_output_pgsql_int4.osm, tests/test-output-pgsql-int4.cpp
=> More Int4 tag value tests

src/db-copy.cpp, src/db-copy.hpp, src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/output-gazetteer.cpp, src/output-gazetteer.hpp, src/pgsql.cpp, src/pgsql.hpp, src/table.cpp, src/table.hpp
Uses a nice class with RAII and is much cleaner.
=> Refactor low-level PostgreSQL functions

src/output.cpp, src/taginfo-impl.hpp, src/taginfo.cpp, tests/CMakeLists.txt, tests/test-taginfo.cpp
Remove use of const_cast and strtok_r.
=> Refactor parse_tag_flags

src/osmtypes.hpp, src/output-multi.cpp, src/output-pgsql.cpp, src/table.cpp, src/tagtransform-c.cpp, src/tagtransform-lua.cpp
Removes some dodgy code including a const_cast and generally cleans up
the class.
=> Refactor taglist_t class

.gitignore, tests/regression-test.py.in
This is created by the new tests
=> Add tests/__pycache__ to .gitignore

src/pgsql.cpp, src/pgsql.hpp
PQfinish(m_conn) must also be called if the connection attempt fails.
By wrapping this into a unique_ptr with deleter, the code becomes
simpler, none of the special member functions is needed any more.
This also adds a little convenience function error_msg() which makes the
rest of the code somewhat cleaner.
=> Make sure PostgreSQL connection is cleaned up properly.

appveyor.yml, tests/CMakeLists.txt
Today, it's time for a little 🎅 🎄 🎁 ... 
Fixes #977
=> Appveyor: use Python 3.8.0

src/table.cpp
Follow-up for #1016. Use native geometry order for clustering but only for Postgis versions >= 2.4.
=> Don't use ST_GeoHash for ordering on Postgis >= 2.4

CMakeLists.txt, cmake/config.h.in, src/CMakeLists.txt, src/osm2pgsql.cpp, src/version.cpp.in, src/version.hpp
Better information about which version a bug reporter is using.
=> Put git commit into osm2pgsql version string

src/output.cpp, src/tagtransform-lua.cpp
=> Don't make tagtransform lua script relative to style when on cmd line

docs/multi.md, docs/osm2pgsql.1, docs/usage.md, src/options.cpp
=> add deprecation warnings for multi backend

src/db-copy.hpp, src/flex-table.cpp, src/flex-table.hpp, src/output-flex.cpp, src/output-flex.hpp
Fixes problem where several threads were using the same db connection objects.
Fixes #1080
=> Fix threading problem flex table take2

.travis.yml, CMakeLists.txt, docs/flex.md, docs/lua-lib.md, src/init.lua, tests/CMakeLists.txt, tests/lua/tests.lua
=> Add some Lua helper functions with docs, and tests for them

src/db-copy-mgr.hpp, src/db-copy.hpp, src/domain-matcher.hpp, src/expire-tiles.cpp, src/gazetteer-style.cpp, src/id-tracker.cpp, src/middle-pgsql.cpp, src/options.cpp, src/osm2pgsql.cpp, src/osmdata.cpp, src/osmium-builder.cpp, src/osmtypes.hpp, src/output-flex.cpp, src/output-multi.cpp, src/pgsql.hpp, src/processor-polygon.hpp, src/reprojection-generic-none.cpp, src/reprojection-generic-proj4.cpp, src/table.cpp, src/tagtransform-c.cpp, tests/test-db-copy-mgr.cpp, tests/test-expire-tiles.cpp
* Fix typos
* Modernize C++
* Fix clang-tidy warnings
* Formatting cleanups
=> Various code cleanups

flex-config/simple.lua, src/flex-table.cpp, src/output-flex.cpp, src/output-flex.hpp
Fix a bug introduced when the flex_table_t was split into flex_table_t and table_connection_t.
=> Bugfix table access

src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/middle-ram.cpp, src/middle-ram.hpp, src/middle.hpp, src/node-persistent-cache.cpp, src/node-persistent-cache.hpp, src/osm2pgsql.cpp, src/osmdata.cpp, tests/common-import.hpp, tests/test-middle.cpp, tests/test-output-flex-types.cpp, tests/test-output-multi-point-multi-table.cpp, tests/test-parse-osmium.cpp, tests/test-persistent-cache.cpp
Various refactoring of the middle code. See individual commits.
=> Refactoring middle

src/middle.hpp
Partial revert of d10bcfdf54f25102adab114187d4c9b907057fed
=> Define constructors of abstract base classes outside the class

src/middle-ram.hpp, src/node-ram-cache.cpp, src/node-ram-cache.hpp, tests/test-ram-cache.cpp
The node_ram_cache code shows its C legacy. This commit fixes some of
its more superficial problems leaving deeper refactorings for a later
time.
=> First pass at refactoring the node_ram_cache

src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/middle-ram.cpp, src/middle-ram.hpp
Add prefix `m_` to all members of `middle_ram_t` and `middle_pgsql_t`.
=> Rename members middle

src/output-flex.cpp, tests/data/test_output_flex_types.lua, tests/test-output-flex-types.cpp
If the string doesn't contain a valid number this will write NULL to
the database instead of 0.
Fixes #1107
=> Bugfix: Conversion of Lua strings to integers in database

src/osm2pgsql.cpp, src/osmdata.cpp, src/osmdata.hpp, tests/common-import.hpp
Various cleanups of osmdata_t class. See individual commits.
=> Osmdata class cleanup

src/table.cpp, src/table.hpp
=> Cleanup table class

src/middle-pgsql.cpp, src/node-ram-cache.cpp, src/node-ram-cache.hpp, src/osmtypes.hpp, tests/common-cleanup.hpp, tests/test-middle.cpp, tests/test-persistent-cache.cpp
Various refactoring and tests for the middle code. See individual commits for details.
=> Middle refactorings and tests

src/flex-table.cpp, src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/options.cpp, src/options.hpp, src/output-gazetteer.cpp, src/output.cpp, src/pgsql.cpp, src/pgsql.hpp, src/table.cpp, src/table.hpp
Cleans up code setting the TABLESPACE and one large C-style function...
=> Tablespace cleanup

src/middle-pgsql.cpp, src/middle-pgsql.hpp
And remove explicit index names
=> Make sql templates more readable

CMakeLists.txt
* Have better title
* Delete stats after building report so that the next run starts with
empty stats.
* Remove unnecessary exclude
=> Fiddle with coverage report

src/flex-table.hpp
=> Bugfix: Adding relations to "linestring" tables works now

src/output-flex.cpp
=> Bugfix: Check that define_table() isn't called in process callback

src/middle-pgsql.cpp, src/osmdata.cpp, src/osmdata.hpp, src/output-flex.cpp, src/output-flex.hpp, src/output-gazetteer.hpp, src/output-multi.cpp, src/output-multi.hpp, src/output-null.hpp, src/output-pgsql.cpp, src/output-pgsql.hpp, src/output.cpp, src/output.hpp, tests/test-middle.cpp
Step2 of the refactoring of the dependency code.
See individual commits
=> Refactor dependency tracking step2

src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/middle-ram.cpp, src/middle-ram.hpp, src/osmdata.cpp
=> Refactor dependency tracking step3

flex-config/geometries.lua, src/flex-table.cpp, src/flex-table.hpp
=> Bugfix: Flex backend tables w/o geometry were unlogged

src/flex-table.cpp, src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/pgsql.cpp, src/pgsql.hpp, src/table.cpp, src/table.hpp
=> Refactor exec_prepared

src/gazetteer-style.cpp, src/gazetteer-style.hpp, src/output-gazetteer.cpp, src/output-gazetteer.hpp
Mostly adding const and include fixes
=> Various cleanups in gazetteer code

docs/flex.md
=> Clarify docs regarding tablespace options ignored in flex backend

docs/flex.md
=> Added details get_bbox() documentation

src/geometry-processor.hpp, src/middle-ram.hpp, src/node-persistent-cache.hpp, src/options.cpp, src/options.hpp, src/output-multi.hpp, src/output.cpp, src/table.cpp, src/table.hpp, src/tagtransform-c.cpp, src/tagtransform.hpp, tests/test-output-pgsql-hstore-match-only.cpp
Various cleanups in the option handling code. See individual commits.
=> Cleanup options handling

docs/lua.md
c.f. https://github.com/openstreetmap/osm2pgsql/blob/master/src/tagtransform-lua.cpp#L200
=> member_superseded is obsolete

src/osmdata.cpp, src/osmdata.hpp
Split up the processing in osmdata_t into functions for each stage. This
better documents what is happening.
=> Split up processing into functions for each stage

src/output-flex.cpp, src/output-flex.hpp
The flex output calls several user-defined Lua functions. They are
"prepared" by putting the function pointers on the Lua stack and later
called. This change gets rid of magic numbers and uses more generic
names for the functions doing the preparing and calling.
=> Refactor functions calling back into Lua code

src/flex-table.cpp, src/flex-table.hpp, src/pgsql.cpp, src/pgsql.hpp, src/table.cpp, tests/test-pgsql.cpp
=> Pgsql related cleanups

docs/flex.md, src/init.lua, src/output-flex.cpp, src/output-flex.hpp
These are some preparatory commits for a cleanup/fix of multistage processing. See individual commits.
=> Prep for changes multistage proc

README.md
=> Don't mention deprecated multi backend in README any more

docs/flex-advanced-topics.md
=> Add documentation on creating unique ids in output tables

docs/flex.md
=> Extend flex docs, better documenting columns

docs/flex.md
=> Fix flex backend documentation regarding multi setting

src/osmdata.cpp
=> Refactor multithreaded_processor function calling

flex-config/compatible.lua
There are still some minor differences, but this should be usable as a
replacement. Also supports several of the old command line options
functionality through settings in the config file. This should give
users a good migration path from original pgsql output with C transform
to the flex output.
=> The "compatible.lua" config is now much more similar to c transform

flex-config/simple.lua, flex-config/unitable.lua, tests/CMakeLists.txt, tests/test-output-flex-example-configs.cpp
Just run them on the liechtenstein file and make sure they don't fail.
=> Add minimal testing of flex example configs

docs/analysis.md, docs/usage.md
=> Fix link for performance analysis for adding --multi-geometry and --hstore

.github/workflows/ci.yml, README.md
1. Rename from "CI" to "OSX CI"
2. Also run on pull requests
3. Add a batch to README.md
=> Fiddle with OSX action workflow

src/middle-pgsql.cpp, src/osmtypes.hpp, src/output-flex.cpp, src/output-multi.hpp, src/output-pgsql.hpp, src/table.cpp, src/taginfo-impl.hpp, src/taginfo.cpp, src/taginfo.hpp, src/tagtransform.hpp
Refactors some code in several steps. See individual commits.
=> Misc cleanup

.clang-tidy, src/flex-table.hpp, src/gazetteer-style.hpp, src/middle-ram.cpp, src/middle-ram.hpp, src/middle.hpp, src/options.cpp, src/output-flex.cpp, src/output-flex.hpp, src/output-null.hpp, src/output-pgsql.hpp, src/progress-display.hpp, src/table.hpp, src/tagtransform-c.cpp, src/tagtransform-lua.hpp, tests/test-db-copy-mgr.cpp, tests/test-middle.cpp
Fiddle with the clang-tidy config and add fixes.
=> Various cleanups and fixes based on clang-tidy reports

src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/middle-ram.cpp, src/middle-ram.hpp, src/middle.hpp
Cleaning up some unused queries and such in middle. See individual commits.
=> Middle cleanup queries

src/flex-table-column.cpp, src/gazetteer-style.cpp, src/geom-transform.cpp, src/lua-utils.cpp, src/node-persistent-cache.cpp, src/node-ram-cache.cpp, src/options.cpp, src/output-flex.cpp, src/output.cpp, src/pgsql.cpp, src/table.cpp, src/taginfo.cpp, src/tagtransform-lua.cpp, src/tagtransform.cpp
And a few other minor formatting changes for error messages.
=> Consistent error messages ending in . without newline

.github/actions/ubuntu-prerequisites/action.yml, README.md
This fixes the recent CI breaks.
=> Github Actions: fix CI badge and run apt update

flex-config/compatible.lua
=> Set correct default for hstore_match_only in compatible.lua

src/expire-tiles.cpp, src/flex-table.cpp, src/middle-pgsql.cpp, src/node-persistent-cache.cpp, src/node-ram-cache.cpp, src/options.cpp, src/osm2pgsql.cpp, src/osmdata.cpp, src/output-flex.cpp, src/output-pgsql.cpp, src/table.cpp, src/tagtransform.cpp
Going through all log messages and sort them into better and more
consistent log levels.
=> Sort out log levels of all log messages

src/input-handler.cpp, src/input-handler.hpp, src/middle-pgsql.cpp, src/node-ram-cache.cpp, src/node-ram-cache.hpp, src/options.cpp, src/osm2pgsql.cpp
=> Various Cleanups

docs/osm2pgsql.1, docs/osm2pgsql.md, src/options.cpp, src/osmdata.cpp
=> Various cleanups on help texts etc

src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/pgsql.cpp
=> Various cleanups in middle-pgsql

src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/node-persistent-cache.cpp, src/node-persistent-cache.hpp, tests/test-persistent-cache.cpp
=> Cleanup persistent cache

src/db-check.cpp, src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/node-persistent-cache.cpp, src/node-persistent-cache.hpp, src/options.cpp, src/options.hpp, tests/common-options.hpp, tests/test-middle.cpp, tests/test-persistent-cache.cpp
Simplify and clean flat node store code. See individual commits.
=> Flat node file option

tests/CMakeLists.txt, tests/test-check-input.cpp, tests/test-domain-matcher.cpp, tests/test-middle.cpp, tests/test-taginfo.cpp, tests/test-util.cpp
=> Refactor tests

src/CMakeLists.txt, src/flex-table.cpp, src/input.cpp, src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/middle-ram.cpp, src/middle-ram.hpp, src/middle.cpp, src/middle.hpp, src/osm2pgsql.cpp, src/osmdata.cpp, src/osmdata.hpp, src/pgsql-helper.cpp, src/pgsql-helper.hpp, src/table.cpp, tests/data/test_invalid_location.osm, tests/test-middle.cpp, tests/test-parse-osmium.cpp
Various refactorings of the middle, removing the slim_middle_t class etc.
=> Refactor middle

src/osm2pgsql.cpp
This commit pulls some code creating complex objects out of main. This
way the destructors are called at the end of the run() function and
memory is cleaned up and threads are all closed. This way the final
memory and timing output will happen after everything is shut down
properly.
=> Pull some code out of main so destructors are called earlier

src/format.hpp, src/middle-ram.cpp, src/osmtypes.hpp, src/progress-display.cpp, src/progress-display.hpp
Various small fixes and cleanups for stuff found by clang-tidy.
=> Fixes for stuff found by clang tidy

src/pgsql.cpp
=> Better check for PostGIS

src/options.cpp, src/options.hpp, src/osm2pgsql.cpp, src/output.hpp, tests/common-options.hpp, tests/test-options-parse.cpp
=> Options improvements

src/output-flex.cpp, tests/data/test_output_flex_types.lua, tests/test-output-flex-types.cpp
=> Fix empty string to real number conversion from Lua to Pg

README.md
cmake was not running without it.
=> add postgresql-dev to alpine installation

.github/actions/ubuntu-prerequisites/action.yml
Fixes https://github.com/actions/virtual-environments/pull/3091.
=> actions: reintroduce postgresql apt repo

.github/workflows/ci.yml, src/logging.hpp
Fix test for C++14 compile and then fix the compile.
=> Test c++14

.clang-tidy, CMakeLists.txt
=> Various clang-tidy updates

src/options.cpp
=> Add warning if --flat-nodes/-F is used in non-slim mode

src/middle-pgsql.cpp, src/middle-ram.cpp
They are available in the new libosmium version.
=> Use new accessor functions for osmium::nwr_array

src/flex-table-column.hpp, src/flex-table.cpp, src/pgsql-helper.cpp, src/pgsql-helper.hpp, src/table.cpp, tests/data/test_output_flex_schema.lua, tests/test-output-flex-schema.cpp
Always use trigger and don't check point geometries (in flex output).
=> Improved geometry IsValid check

src/db-copy.cpp, src/geom-transform.cpp, src/middle-pgsql.cpp, src/osm2pgsql.cpp, src/tagtransform-c.cpp, src/tagtransform.cpp, tests/common-import.hpp, tests/test-db-copy-thread.cpp, tests/test-parse-osmium.cpp
Now that we are using C++14, make_unique is available.
=> Use std::make_unique to make code cleaner

src/db-copy-mgr.hpp, src/middle-pgsql.cpp, src/middle-ram.cpp, src/progress-display.cpp, src/tagtransform-c.cpp, src/tagtransform-c.hpp, src/util.cpp, src/util.hpp
=> Fix some implicit signed-unsigned conversions

README.md, src/db-copy.cpp, src/thread-pool.cpp, tests/test-node-locations.cpp
=> Various very small changes

src/output-flex.cpp
=> Do not try to create indexes for tables without id

CMakeLists.txt, README.md
Update required libosmium version to 2.17.0 and document required library versions in README
=> Required libs

src/flex-table.cpp
The flex output supports "create_only" table columns which are only
created but not filled with any data. This can lead to problems in some
cases (for instance when a column of type SERIAL is used) because
osm2pgsql usually creates tables twice, first a temporary table, then a
final one. This commit changes the behaviour slightly: The "create_only"
column is only created in the final table.
Fixes #1522
=> Only create create_only columns in final table

tests/regression.py
Contrary to what one might expect, the connection context manager does not close the connection when leaving but just end the currently running transaction.
This commit removes all uses of the 'with' construct with connections and replaces them with a classic try/finally block, explicitly closing the connection on the way.
Fixes a breakage of the tests when used with the psycopg2 2.9 release.
=> Regression tests: fix usage of psycopg2.connect

src/options.cpp
=> Fix typo: disabled

src/middle-pgsql.cpp
=> Run ANALYZE on middle tables only in create mode

.github/actions/win-install/action.yml, src/tagtransform-c.cpp
Use our own implementation of starts_with() which is the only thing we
needed from that library.
=> Remove dependency on boost::algorithm

.github/actions/ubuntu-prerequisites/action.yml
Workaround not necessary any more
https://github.com/actions/virtual-environments/issues/3376
=> Github actions: Config clean up

src/expire-tiles.cpp, src/expire-tiles.hpp, src/tile.hpp, tests/test-expire-tiles.cpp, tests/test-tile.cpp
Various refactorings to clean up the expire code. See individual commits.
=> Refactor of expire code

.clang-tidy, src/flex-table-column.cpp, src/flex-table-column.hpp, src/format.hpp, src/gazetteer-style.hpp, src/middle-pgsql.cpp, src/middle-pgsql.hpp, src/options.cpp, src/options.hpp, src/output-flex.cpp, src/output-gazetteer.cpp, src/output-gazetteer.hpp, src/output-null.cpp, src/output-pgsql.cpp, src/output.cpp, src/output.hpp, src/pgsql.cpp, src/table.cpp, src/table.hpp, src/taginfo.hpp, src/tagtransform-c.cpp, src/tagtransform-c.hpp, src/wkb.cpp, tests/test-expire-tiles.cpp, tests/test-middle.cpp, tests/test-output-gazetteer.cpp, tests/test-output-pgsql-style-file.cpp, tests/test-parse-osmium.cpp
=> Misc code cleanup

src/db-copy-mgr.hpp, src/db-copy.hpp, src/expire-tiles.cpp, src/expire-tiles.hpp, src/flex-table-column.cpp, src/flex-table.cpp, src/gazetteer-style.cpp, src/gazetteer-style.hpp, src/output-flex.cpp, src/pgsql-helper.cpp, src/table.cpp, tests/test-middle.cpp, tests/test-output-flex-types.cpp, tests/test-output-flex-way-add.cpp, tests/test-output-flex-way-change.cpp, tests/test-output-flex-way-del.cpp, tests/test-output-flex-way-relation-add.cpp, tests/test-output-flex-way-relation-del.cpp, tests/test-output-pgsql-z_order.cpp, tests/test-persistent-cache.cpp
=> Misc code cleanups

src/pgsql.cpp, src/pgsql.hpp, tests/test-pgsql.cpp
This way we don't need to hardwire any types.
Also adds some docs and tests.
=> Use templates to make writing data to PostgreSQL more generic

src/geom-from-osm.hpp, src/geom.hpp, src/wkb.hpp
Cool new shit now in C++17. Maybe this will save us from some problems later on.
=> Sprinkle [[nodiscard]] around the geometry code

src/geom-functions.cpp, src/geom.hpp, src/wkb.cpp, tests/test-wkb.cpp
Cleans up the API of that class.
=> Make multigeometry_t not derive from std::vector

src/geom.cpp, src/geom.hpp
std::vector has operator==() and operator!=() which work fine for us here.
=> Simplify equality operators

src/output-flex.cpp, tests/bdd/flex/lua-basics.feature, tests/bdd/steps/steps_execute.py
This is useful when we want to mess with details of the Table class (which is used for database tables) from Lua.
Also fixes a type in the BDD runner.
=> Make table class accessible from lua

src/output-flex.cpp, src/output-flex.hpp
This function will be used by many other functions in the future.
=> Refactoring: Add helper function to check Lua function parameters

src/options.hpp
=> Enable lossy way-node index by default

src/geom-functions.cpp, src/geom-functions.hpp, src/geom.hpp
=> Fix various small code smells in geometry code

src/flex-lua-geom.cpp, src/geom-from-osm.cpp, src/geom-from-osm.hpp, src/geom-functions.cpp, src/geom-functions.hpp, src/output-flex.cpp, tests/bdd/flex/geometry-multilinestring.feature, tests/bdd/flex/geometry-processing.feature, tests/test-geom-multilinestrings.cpp
=> Some more work in the geometries

src/flex-lua-geom.cpp, src/geom-functions.cpp, src/geom-functions.hpp, tests/test-geom-collections.cpp, tests/test-geom-linestrings.cpp, tests/test-geom-multilinestrings.cpp, tests/test-geom-multipoints.cpp, tests/test-geom-multipolygons.cpp, tests/test-geom-null.cpp, tests/test-geom-points.cpp, tests/test-geom-polygons.cpp
I have implemented this.
Related issue: #1757
The CI is still running, if it passes then it should be ready to merge pending manual inspection
=> length for flex output

src/geom-functions.cpp, src/geom.cpp, src/geom.hpp, tests/test-geom-collections.cpp, tests/test-geom-linestrings.cpp, tests/test-geom-multilinestrings.cpp, tests/test-geom-multipoints.cpp, tests/test-geom-multipolygons.cpp, tests/test-geom-null.cpp, tests/test-geom-points.cpp, tests/test-geom-polygons.cpp
See individual commits for description.
=> Add centroid() implementation for geometry collection

src/geom-from-osm.cpp, src/geom-from-osm.hpp, src/output-flex.cpp, src/output-flex.hpp, tests/bdd/flex/geometry-multipoint.feature, tests/bdd/steps/geometry_factory.py, tests/bdd/steps/steps_osm_data.py, tests/test-geom-multipoints.cpp
From C++ and from Lua (`as_multipoint()`) to complete the set with `as_linestring()` and `as_polygon()`.
=> Add function to create multipoint geometry

src/expire-tiles.cpp, src/expire-tiles.hpp, src/output-flex.cpp, src/output-pgsql.cpp, src/output-pgsql.hpp, src/tile-output.hpp, src/tile.cpp, src/tile.hpp, tests/test-expire-tiles.cpp
To prepare for coming changes.
=> Various refactorings of expire code

src/geom-box.cpp, src/geom-box.hpp, tests/test-geom-box.cpp
Some groundwork for future extentions to the expire code.
=> Add functionality around box_t class and envelope()

src/pgsql.hpp
https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL59-CPP.+Do+not+define+an+unnamed+namespace+in+a+header+file
=> Do not use anonymous namespace in header file

src/db-copy-mgr.hpp
STR34-C
https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87158805
=> Fix signed to unsigned conversion

src/db-check.cpp
Otherwise osm2pgsql might not work correctly.
=> Check that database is using UTF-8 encoding

src/pgsql-capabilities.cpp, src/pgsql.cpp, src/pgsql.hpp, tests/common-pg.hpp, tests/test-db-copy-mgr.cpp, tests/test-pgsql.cpp
=> Pgsql small refactorings

src/pgsql.hpp
Functionality was recently changed in
440579e2bf1fd2aba17ef8dff6102d7ada4f6674
=> Fix doc comment of exec() function

src/options.cpp, tests/test-options-parse.cpp
Use consistently named functions parse_*_param() for all parameters of command line options that are more complex to parse. And test them!
Also add print_version() function.
=> Use parse_*_param() funcs to parse command line option parameters

src/flex-table.cpp, src/middle-pgsql.cpp, src/pgsql-helper.cpp, src/pgsql.cpp, src/pgsql.hpp, src/table.cpp, tests/common-pg.hpp, tests/test-db-copy-mgr.cpp
=> Add a variant of the database exec() command with fmt parameters

src/db-copy-mgr.hpp
Fold expressions are available since C++17.
=> Refactor: Use fold expression for add_columns() function

src/flex-table-column.cpp, src/flex-table.cpp, src/flex-table.hpp, src/output-flex.cpp
For schema, extensions, and tablespaces. See individual commits.
=> Earlier database compatibility checks

src/flex-lua-geom.cpp, src/flex-write.cpp, src/output-pgsql.cpp, src/reprojection.cpp, src/reprojection.hpp
=> Refactor projection use

src/db-copy-mgr.hpp, src/osmtypes.hpp, src/tagtransform-c.cpp, src/util.hpp, tests/test-util.cpp
=> Cleanup int double buffer

src/expire-tiles.cpp, tests/test-expire-tiles.cpp
Various small changes in expire code, see individual commits.
=> Expire code fiddling

src/expire-tiles.cpp, src/flex-table.cpp, src/pgsql.cpp, src/pgsql.hpp, src/table.cpp
Get geometries for expire from database in binary format
=> Pgsql read wkb binary

src/pgsql.hpp, tests/test-pgsql.cpp
Also adds a crucial std::decay_t<> which makes sure this works for all sorts of types.
=> Use C++17 feature constexpr if to simplify pgsql code

.github/actions/win-test/action.yml, src/json-writer.hpp, tests/bdd/flex/tags.feature
=> Fix for UTF-8 characters in JSON

src/output-flex.cpp, src/output-flex.hpp
Some smaller code cleanups in flex output. See individual commits.
=> Cleanups in flex output

tests/data/test_output_flex_nodes.lua, tests/data/test_output_flex_relation_combinations.lua, tests/data/test_output_flex_relations.lua, tests/data/test_output_flex_schema.lua, tests/data/test_output_flex_types.lua
At some point we'll deprecate add_row(), tests that don't explicitly test add_row() should use insert().
=> Replace add_row() by insert() in some tests

src/expire-tiles.cpp, src/expire-tiles.hpp, src/output-flex.cpp, src/output-pgsql.cpp
These are two of the commits from #1902.
=> Small changes in expire code

src/expire-config.hpp, src/expire-tiles.cpp, src/expire-tiles.hpp, src/flex-write.cpp, src/flex-write.hpp, src/output-flex.cpp, src/output-flex.hpp, src/output-pgsql.cpp, src/output-pgsql.hpp, tests/test-expire-from-geometry.cpp, tests/test-expire-tiles.cpp
These are some changes in preparation for more flexible expiry config that can be configured from Lua.
This is the (changed) rest of what was originally in #1902.
=> Various changes in preparation for flexible expiry config

src/pgsql.cpp, src/pgsql.hpp, tests/test-pgsql.cpp
To get the number of INSERTed, UPDATEd, or DELETEed rows.
This is useful for debug logging.
=> Add pgresult_t::affected_rows() function

.github/workflows/ci.yml
Because the image is deprecated.
=> Github actions: Remove check with Ubuntu 18.04

src/expire-output.cpp, src/expire-output.hpp, src/output-flex.cpp
With the rest of the expire output code.
=> Move table creation for expire tables where it belongs

src/geom.hpp, tests/test-geom-points.cpp
The order is more or less arbitrary. This is only so that there is some kind of order for comparing sets of points etc.
=> Add operators to make points sortable

src/logging.cpp, src/logging.hpp, src/thread-pool.cpp
=> Various changes around threads and logging

.github/actions/build-and-test/action.yml, CONTRIBUTING.md, docs/osm2pgsql.md
=> Minor typos

src/pgsql.hpp, tests/test-pgsql.cpp
Prepared statements can now send parameters in binary as well as in the default text format. To do this, wrap the binary data in an instance of the binary_param class, which is just a wrapper of std::string_view used to signal to the exec_prepared() function that this parameter should be sent in binary.
You can mix and match any number of parameters in text or binary format.
It isn't possible any more to use exec_prepared() without any parameters, but that wasn't use (and doesn't make much sense anyway), so no loss there.
=> Add functionality to send data to PostgreSQL in binary

src/output-flex.cpp
=> Bugfix: Also increment insert counter in add_row()

src/expire-output.hpp, src/expire-tiles.hpp, src/flex-index.hpp, src/flex-write.cpp, src/gazetteer-style.hpp, src/gen/gen-base.hpp, src/gen/osm2pgsql-gen.cpp, src/gen/params.hpp, src/middle-pgsql.cpp, src/pgsql-capabilities.hpp, src/pgsql.hpp, src/progress-display.hpp
=> Add missing cstdint header includes to some files

src/input.hpp, src/middle-pgsql.cpp, src/middle-ram.hpp, src/osmdata.hpp, src/osmtypes.hpp, src/pgsql.hpp, src/progress-display.hpp, src/reprojection.hpp, src/thread-pool.hpp
=> Various comment fixes

.clang-tidy, src/gen/gen-tile.hpp, src/gen/osm2pgsql-gen.cpp, src/middle-ram.hpp, src/node-locations.hpp, src/ordered-index.hpp, src/pgsql.hpp, src/progress-display.cpp, src/thread-pool.cpp, src/util.cpp, src/wkb.cpp, tests/test-db-copy-mgr.cpp, tests/test-lua-utils.cpp, tests/test-middle.cpp, tests/test-node-locations.cpp
=> Various cleanups/fixes found by clang-tidy

.github/actions/win-install/action.yml, src/middle-pgsql.cpp, src/middle-pgsql.hpp, tests/test-middle.cpp
Three small things in three independent commits.
=> Small fixes

src/flex-table.cpp, src/gen/osm2pgsql-gen.cpp, src/osm2pgsql.cpp, src/output-flex.cpp
=> Some small fixes and cleanups

src/db-copy.cpp
This forces the DELETEs to use an index scan which is much faster.
The underlying problem here is probably that the DELETEs are called for all OSM objects in the input file, regardless of whether they are even in the table. For most tables most ids will not be in there. So PostgreSQL overestimates the number of "hits" it is going to get and thinks a full table scan is more efficient when in fact an index lookup is much better.
The COPYs used in the same database connection are not affected by this.
In many tests I have done I only see this problem in some cases, but when it hits it can slow down processing considerably. This could explain the occasional slow processing that some people have been reporting over the years and that we could never really nail down (#1674, #1971).
=> Disable sequential scan on database tables in copy threads

src/pgsql-capabilities.cpp, src/pgsql.cpp, tests/test-middle.cpp, tests/test-output-flex-schema.cpp, tests/test-output-flex-tablespace.cpp, tests/test-output-pgsql-tablespace.cpp
Just to make osm2pgsql a tiny bit more robust...
=> Consistently use pg_catalog schema when accessing system tables

flex-config/addresses.lua, flex-config/attributes.lua, flex-config/bbox.lua, flex-config/compatible.lua, flex-config/data-types.lua, flex-config/expire.lua, flex-config/gen/forests.lua, flex-config/generic.lua, flex-config/geometries.lua, flex-config/indexes.lua, flex-config/labelpoint.lua, flex-config/route-relations.lua, flex-config/simple.lua, flex-config/unitable.lua
Mostly making variables local.
=> Various Lua example file cleanups

.github/workflows/luacheck.yml, .luacheckrc, tests/data/test_output_flex.lua, tests/data/test_output_flex_stage2.lua, tests/data/test_output_flex_stage2_alt.lua, tests/data/test_output_flex_uni.lua, tests/data/test_output_flex_validgeom.lua, tests/data/test_output_flex_way.lua, tests/lua/tests.lua
Also fixes some warnings generated by luacheck.
There are two files not checked: `style.lua`, the old pgsql config that I don't want to touch. And `src/init.lua` which does some things setting up the `osm2pgsql` global which other scripts are not allowed to do. I'll leave that for some later time.
=> Add configuration for luacheck and run luacheck in Github actions

src/gen/gen-tile-raster.cpp
This allows, for instance, to only generalize certain types of polygons.
=> Add config option for WHERE clause to tile-raster generalizer

docs/osm2pgsql-replication.1, scripts/osm2pgsql-replication, tests/bdd/command-line/replication.feature
Same schema option as was added for osm2pgsql in #2037.
=> Add --schema option to osm2pgsql-replication

src/flex-lua-expire-output.cpp, src/lua-utils.cpp, src/lua-utils.hpp, tests/bdd/flex/lua-expire-output-definitions.feature
=> Fix architecture-dependent double to integer conversion

src/output-pgsql.cpp, src/table.hpp, src/tagtransform-c.cpp, tests/common-import.hpp, tests/test-output-pgsql-z_order.cpp
=> Various small code cleanups

src/gen/osm2pgsql-gen.cpp, src/osm2pgsql.cpp, src/tagtransform-lua.cpp, tests/test-expire-from-geometry.cpp
=> Clang tidy cleanup

src/middle-pgsql.cpp
Put query for finding parent ways from nodes inside a PL/pgSQL function. The query we had before would sometimes result in really bad performance when the query planner in PostgreQL decides that it needs to use sequential scans on the ways table. This is due to the statistics being way off. By running the query for each node ids on its own we hopefully trick the query planner into always using an index lookup.
See #2056
=> Use roundabout way to find changed ways

src/gen/gen-rivers.cpp, src/gen/gen-tile-builtup.cpp, src/gen/gen-tile-raster.cpp, src/gen/tracer.cpp, src/wkb.cpp, src/wkb.hpp, tests/test-wkb.cpp
Code is only used in the generalization.
Faster code for hex decoder and bit-fiddling in tracer code.
=> Improve performance of some low level code

tests/bdd/flex/lua-expire.feature
Instead of just NULL geometries to make them a bit more realistic.
=> Actually add geometries in the test

tests/bdd/flex/expire.feature, tests/bdd/flex/lua-expire.feature, tests/bdd/flex/relation-changes.feature, tests/bdd/flex/way-add.feature, tests/bdd/flex/way-change.feature, tests/bdd/flex/way-del.feature, tests/bdd/flex/way-relation-add.feature, tests/bdd/flex/way-relation-del.feature, tests/bdd/steps/geometry_factory.py, tests/bdd/steps/steps_osm_data.py, tests/data/test_expire.lua
=> Always test with empty grids in append tests, test expire on zoom level 0

.github/workflows/ci.yml
Version 16 was just released so we should test with it.
=> Github actions: Test with newer PostgreSQL versions (up to 16)

src/expire-output.cpp
This adds two timestamp (with timezone) columns to all expire tables called "first" and "last". When an entry is added, both are set to the current (transaction) timestamp. When an entry already exists a new insert will result in the "last" timestamp being updated.
Having these two timestamps allows various expire/updating strategies, for instance:
* update oldest entry
* update entry that didn't change for the longest time
* update older entries but only if there are no recent changes, which indicates that there might be more changes coming
For backwards compatibility the code detects which table format is used and falls back to the old behaviour if the timestamp columns aren't there.
We are currently not using the timestamps anywhere in osm2pgsql but they can already be used outside …
=> Add first/last timestamps to expire tables

src/gen/osm2pgsql-gen.cpp
Use out parameter with ptr instead.
=> Avoid copy of vector in get_tiles_from_table() function

tests/common-pg.hpp, tests/test-properties.cpp
=> Refactor: Modernize get_count and require_has_table

src/gen/osm2pgsql-gen.cpp
We have a limit of 256 set in line 688 already.
Fixes #2086
=> Increase the max number of jobs for osm2pgsql-gen to 256

.github/actions/win-install/action.yml, .github/workflows/ci.yml
=> Add proj.db to Windows artifact

man/osm2pgsql.1, man/osm2pgsql.md, src/command-line-parser.cpp
It hasn't done anything in a long time and was marked deprecated.
=> Remove --cache-strategy option

src/flex-table.cpp, src/flex-table.hpp, src/geom-from-osm.cpp, tests/bdd/flex/bbox.feature, tests/test-pgsql.cpp
=> Various small cleanups

src/command-line-parser.cpp, src/flex-table-column.cpp
The number of array members was not updated when the contents of the array changed in b699cde.
=> Fix number of array members

src/flex-table-column.cpp
And some other small fixes in the same file.
=> Fix unusual member name in column_type_lookup

man/osm2pgsql.md, src/command-line-parser.cpp, src/middle-ram.cpp, src/middle-ram.hpp, src/node-persistent-cache.hpp, tests/bdd/regression/multipolygon.feature, tests/test-options-parse.cpp
This is useful if memory is tight.
=> Make --flat-nodes also work in non-slim mode

src/db-copy.cpp, src/db-copy.hpp, src/debug-output.cpp, src/debug-output.hpp, src/expire-output.cpp, src/expire-output.hpp, src/flex-lua-index.cpp, src/flex-table-column.cpp, src/flex-table.hpp, src/flex-write.hpp, src/gen/canvas.cpp, src/gen/canvas.hpp, src/gen/gen-base.cpp, src/gen/gen-base.hpp, src/gen/gen-create.cpp, src/gen/gen-create.hpp, src/gen/gen-discrete-isolation.cpp, src/gen/gen-discrete-isolation.hpp, src/gen/gen-rivers.hpp, src/gen/osm2pgsql-gen.cpp, src/gen/tracer.cpp, src/gen/tracer.hpp, src/geom-box.cpp, src/geom-from-osm.cpp, src/geom-functions.hpp, src/lua-utils.cpp, src/middle-ram.hpp, src/node-persistent-cache.cpp, src/osm2pgsql.cpp, src/table.cpp
Found with IWYU, unfortunately that tool also produces a lot of errors which is cumbersome to work through, so this fixes only some of the problems detected.
=> Clean up some includes

man/osm2pgsql.md, src/expire-tiles.cpp, src/geom-area-assembler.hpp
=> Various small fixes

src/command-line-parser.cpp, tests/test-options-parse.cpp
=> Improved parsing of --bbox command line option

src/middle-pgsql.cpp
It seems removing thise code was forgotten in
515dfb25e900fa781f97145246fb280e0d93f187
=> Remove forgotten code still supporting old middle format

src/output-flex.cpp
The code that deals with functions called on the Lua OSM object given as parameter to the process callbacks is somewhat strange. The result is that calling "object.as_point()" etc. will work, but the correct Lua way to do this is "object:as_point()". This adds a check to all the functions that detects this case and prints a warning. It will also check that those functions are not called with any additional arguments.
Checking for this now, users will hopefully fix this. This gives us the opportunity later to change or code to be more in line with usual Lua syntax.
This will only print a warning once per function.
=> Check that Lua functions on OSM object are called correctly

.clang-tidy, src/gen/osm2pgsql-gen.cpp, src/lua-utils.cpp, src/output-flex.cpp, src/properties.cpp, src/wkb.cpp
...by using anonymous namespaces.
Enables the clang-tidy check.
=> Refactors final cases of use of "static"

src/expire-config.hpp, src/lua-setup.hpp
They were not in line with the file names.
=> Fix include guard names
